import { cpSync, existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { ChangeManagementEngine } from "../src/change-management-engine.js";
import type { ChangeDecision, ChangeTarget, CreateMaterialChange } from "../src/change-management-types.js";
import { EngineeringFoundationEngine } from "../src/engineering-engine.js";
import type { EngineeringFoundationUpdate } from "../src/engineering-types.js";
import { ProductStartEngine } from "../src/engine.js";
import { LivingRoadmapEngine } from "../src/living-roadmap-engine.js";
import { MilestoneDefinitionEngine } from "../src/milestone-definition-engine.js";
import type { DefinitionUpdate } from "../src/milestone-definition-types.js";
import { parseCliArguments } from "../src/cli-arguments.js";
import type { ProductStartUpdate } from "../src/types.js";

const sourceRoot = resolve(import.meta.dirname, "../..");
const fixture = join(sourceRoot, "evaluation/scenarios/product-start/large-mixed-project/fixture");
const productSetup = join(sourceRoot, "evaluation/scenarios/product-start/large-mixed-project/setup/v1/product-update.json");
const workspaces: string[] = [];
let productEngine: ProductStartEngine;
let engineeringEngine: EngineeringFoundationEngine;
let roadmapEngine: LivingRoadmapEngine;
let definitionEngine: MilestoneDefinitionEngine;
let changeEngine: ChangeManagementEngine;

beforeAll(async () => { productEngine = await ProductStartEngine.create(sourceRoot); engineeringEngine = await EngineeringFoundationEngine.create(sourceRoot); roadmapEngine = await LivingRoadmapEngine.create(sourceRoot); definitionEngine = await MilestoneDefinitionEngine.create(sourceRoot); changeEngine = await ChangeManagementEngine.create(sourceRoot); });
afterAll(() => { workspaces.forEach((root) => rmSync(root, { recursive: true, force: true })); });

function engineeringUpdates(): EngineeringFoundationUpdate[] { const reference = readFileSync(join(sourceRoot, "skills/loopy/references/engine/Engineering-Foundation-Apply.md"), "utf8"); return [...reference.matchAll(/<!-- engineering-apply-example -->\n```json\n([\s\S]*?)\n```/g)].map((match) => JSON.parse(match[1]) as EngineeringFoundationUpdate); }
async function confirmedProduct(): Promise<string> { const root = mkdtempSync(join(tmpdir(), "loopy-change-")); workspaces.push(root); cpSync(fixture, root, { recursive: true }); await productEngine.initialize(root, "Harbor", { participantResponsibilities: ["product"] }); productEngine.applyUpdate(root, JSON.parse(readFileSync(productSetup, "utf8")) as ProductStartUpdate); await productEngine.recordProductReview(root); await productEngine.confirmProduct(root); changeEngine.initialize(root); return root; }
async function committedDefinition(): Promise<{ root: string; definitionId: string }> { const root = await confirmedProduct(); engineeringEngine.initialize(root, { participantResponsibilities: ["engineering"] }); for (const update of engineeringUpdates()) engineeringEngine.applyUpdate(root, update); engineeringEngine.recordReview(root); engineeringEngine.confirm(root); roadmapEngine.initialize(root); roadmapEngine.applyOperation(root, { type: "set-dependencies", candidateId: "candidate-1", dependencies: [], actor: { name: "Priya", responsibility: "product" } }); roadmapEngine.applyOperation(root, { type: "select", candidateIds: ["candidate-1"], actor: { name: "Priya", responsibility: "product" } }); const state = definitionEngine.initialize(root); const definitionId = state.definitions[0].id; const update: DefinitionUpdate = { type: "update", definitionId, actor: { name: "Loopy", perspectives: ["product", "engineering"] }, content: { outcome: "Operators recover customer access without support intervention.", requirements: ["Authorized operators can complete account recovery."], inScope: ["Operator recovery"], nonGoals: ["Fraud adjudication"], acceptance: ["Given an eligible locked account, an authorized operator restores access and the customer signs in; ineligible recovery is rejected with a reason."], dependencies: [{ name: "Identity service", kind: "required-before", consequence: "implementation", note: "Required during implementation." }], feasibilityAndConstraints: ["Preserve access controls"], risks: ["Sensitive account state"], assumptions: ["Identity remains authoritative"], unknowns: [] }, coherence: { status: "coherent", basis: "Outcome, scope, consequences, and acceptance are consistent." }, requiredPerspectives: ["product", "engineering"] }; definitionEngine.applyUpdate(root, update); definitionEngine.review(root, [definitionId]); definitionEngine.confirm(root, [{ definitionId, participant: "Emi", perspectives: ["engineering"], commit: false }]); definitionEngine.confirm(root, [{ definitionId, participant: "Priya", perspectives: ["product"], commit: true }]); return { root, definitionId }; }
function productTarget(root: string, field: "product.summary" | "product.purpose", value: string): ChangeTarget { const state = productEngine.loadState(root); return { kind: "product", field, baseRevision: state.revision, value, artifactPath: "docs/loopy/Project-Definition.md", currentMeaning: field === "product.summary" ? state.product.summary : state.product.purpose, proposedMeaning: value }; }
function proposal(root: string, title: string, targets: ChangeTarget[], perspectives: Array<"product" | "engineering"> = ["product"]): CreateMaterialChange { return { title, reason: "New confirmed information changes the accepted boundary.", targets, downstreamConsequences: ["Affected lifecycle work must use the revised boundary."], unaffectedWork: ["Unlisted Milestones and decisions remain unchanged."], participants: perspectives.map((perspective) => ({ name: perspective === "product" ? "Priya" : "Emi", perspective })), unknowns: [], deferrals: [], requiredPerspectives: perspectives, coherence: { status: "coherent", basis: "The Host traced the replacement and its bounded consequences." }, authorityRequested: "Accept the complete proposed meaning and atomically reconcile only its named targets.", earliestStage: targets.some((item) => item.kind === "product") ? "product-start" : "milestone-definition", nextAction: { participant: perspectives.join(" and "), action: `Review ${title}`, reason: "The material boundary and impact require the named responsibility decisions." } }; }
function accept(changeId: string, perspectives: Array<"product" | "engineering"> = ["product"], participant = "Priya"): ChangeDecision { return { changeId, participant, perspectives, decision: "accept", basis: "Yes, use this revised meaning and apply it." }; }
function routine(target: ChangeTarget, summary = "Applied a confirmed meaning-preserving correction.") { return { category: "equivalent-wording" as const, summary, actor: "Loopy", meaningPreserved: true as const, meaningUncertainty: "none" as const, classificationBasis: "The Host resolved the wording difference and confirmed that no agreed meaning changes.", target }; }
function snapshot(root: string, paths: string[]): Record<string, string> { return Object.fromEntries(paths.map((path) => [path, readFileSync(join(root, path), "utf8")])); }

describe("Change Management", () => {
  it("applies routine corrections without Change.md while preserving concise history", async () => { const root = await confirmedProduct(); const target = productTarget(root, "product.summary", "Harbor helps support teams understand and recover customer access."); const state = changeEngine.applyRoutine(root, { category: "equivalent-wording", summary: "Clarified equivalent Product summary wording.", actor: "Priya", meaningPreserved: true, meaningUncertainty: "none", classificationBasis: "The wording is clearer while retaining the confirmed people, need, outcome, and boundary.", target }); expect(state.changes).toHaveLength(0); expect(state.routineHistory).toHaveLength(1); expect(state.routineHistory[0].classificationBasis).toContain("retaining the confirmed people"); expect(productEngine.loadState(root).product.summary).toBe(target.value); expect(existsSync(join(root, "docs/loopy/changes"))).toBe(false); expect(readFileSync(join(root, "LOOPY.md"), "utf8")).toContain("routine correction preserved agreed meaning"); });

  it("rejects a routine operation without the explicit meaning-preserved guard", async () => { const root = await confirmedProduct(); const before = readFileSync(join(root, ".loopy/change-management/state.json"), "utf8"); expect(() => changeEngine.applyRoutine(root, { category: "equivalent-wording", summary: "Unproven equivalent wording.", actor: "Priya", meaningPreserved: false, target: productTarget(root, "product.summary", "Potentially changed meaning.") } as any)).toThrow("agreed meaning is preserved"); expect(readFileSync(join(root, ".loopy/change-management/state.json"), "utf8")).toBe(before); });

  it("keeps uncertain subtle meaning expansion material instead of accepting it as routine", async () => { const root = await confirmedProduct(); const before = snapshot(root, [".loopy/change-management/state.json", ".loopy/start-or-adopt/state.json", "LOOPY.md", "docs/loopy/Project-Definition.md"]); const request = routine(productTarget(root, "product.summary", "Harbor automatically recovers every customer's access."), "Proposed small wording expansion."); expect(() => changeEngine.applyRoutine(root, { ...request, meaningUncertainty: "unresolved" } as any)).toThrow("no material meaning uncertainty remains"); expect(snapshot(root, Object.keys(before))).toEqual(before); });

  it("applies a declared routine correction to a committed Definition without material receipts", async () => { const { root, definitionId } = await committedDefinition(); const before = definitionEngine.loadState(root).definitions[0]; const target: ChangeTarget = { kind: "milestone-definition", targetId: definitionId, field: "content.nonGoals", baseRevision: before.revision, value: ["Adjudicating suspected fraud"], artifactPath: before.artifactPath, currentMeaning: before.content.nonGoals[0], proposedMeaning: "Equivalent wording for the existing fraud-adjudication non-goal." }; const state = changeEngine.applyRoutine(root, routine(target)); const after = definitionEngine.loadState(root).definitions[0]; expect(after.phase).toBe("committed"); expect(after.content.nonGoals).toEqual(["Adjudicating suspected fraud"]); expect(after.receipts.map(({ participant, perspective, revision }) => ({ participant, perspective, revision }))).toEqual(before.receipts.map(({ participant, perspective }) => ({ participant, perspective, revision: after.revision }))); expect(after.history).toHaveLength(before.history.length + 1); expect(after.history.at(-1)?.summary).toContain("declared meaning-preserving correction"); expect(state.changes).toHaveLength(0); expect(state.nextActions).toHaveLength(1); expect(existsSync(join(root, "docs/loopy/changes"))).toBe(false); });

  it("keeps a material proposal separate until one natural-language acceptance reconciles it", async () => { const root = await confirmedProduct(); const before = productEngine.loadState(root).product.purpose; let state = changeEngine.propose(root, proposal(root, "Clarify recovery purpose", [productTarget(root, "product.purpose", "Enable support teams to restore eligible customer access safely.")])); const change = state.changes[0]; expect(change.history.map((item) => item.operation)).toEqual(["create"]); expect(productEngine.loadState(root).product.purpose).toBe(before); const draftView = readFileSync(join(root, change.artifactPath), "utf8"); expect(draftView).toContain("Current and proposed meaning"); expect(draftView).not.toContain("change-1"); state = changeEngine.review(root, change.id); state = changeEngine.decide(root, accept(change.id)); expect(state.changes[0].status).toBe("accepted"); expect(state.changes[0].history.map((item) => item.operation)).toEqual(["create", "review", "accept"]); expect(productEngine.loadState(root).product.purpose).toContain("restore eligible customer access"); expect(state.nextActions).toHaveLength(1); expect(readFileSync(join(root, "LOOPY.md"), "utf8")).toContain("accepted"); expect(readFileSync(join(root, change.artifactPath), "utf8")).toContain("clear natural-language intent"); });

  it("reconciles a cross-responsibility committed Definition change and preserves prior versions", async () => { const { root, definitionId } = await committedDefinition(); const definition = definitionEngine.loadState(root).definitions[0]; const beforeHistory = definition.history.length; const target: ChangeTarget = { kind: "milestone-definition", targetId: definitionId, field: "content.acceptance", baseRevision: definition.revision, value: ["Given an eligible locked account, an authorized operator restores access, the customer signs in, and an audit event is visible; ineligible recovery is rejected with a reason."], artifactPath: definition.artifactPath, currentMeaning: definition.content.acceptance[0], proposedMeaning: "Recovery acceptance additionally requires a visible audit event." }; let state = changeEngine.propose(root, proposal(root, "Require recovery audit evidence", [target], ["product", "engineering"])); const change = state.changes[0]; expect(definitionEngine.loadState(root).definitions[0].content.acceptance).toEqual(definition.content.acceptance); changeEngine.review(root, change.id); state = changeEngine.decide(root, { changeId: change.id, participant: "Priya", perspectives: ["product"], decision: "accept", basis: "Product agrees to this revised acceptance boundary." }); expect(state.changes[0].status).toBe("ready"); expect(state.changes[0].receipts).toEqual([{ participant: "Priya", perspective: "product", revision: change.revision }]); state = changeEngine.decide(root, { changeId: change.id, participant: "Emi", perspectives: ["engineering"], decision: "accept", basis: "Engineering agrees to the same reviewed boundary." }); const revised = definitionEngine.loadState(root).definitions[0]; expect(revised.content.acceptance[0]).toContain("audit event"); expect(revised.phase).toBe("committed"); expect(revised.history).toHaveLength(beforeHistory + 1); expect(revised.history.at(-1)?.operation).toBe("change-management"); expect(state.changes[0].status).toBe("accepted"); expect(state.changes[0].receipts.map(({ participant, perspective }) => ({ participant, perspective }))).toEqual([{ participant: "Priya", perspective: "product" }, { participant: "Emi", perspective: "engineering" }]); });

  it("accumulates separate same-revision receipts in reverse order and rejects synthetic identity", async () => { const { root, definitionId } = await committedDefinition(); const definition = definitionEngine.loadState(root).definitions[0]; const target: ChangeTarget = { kind: "milestone-definition", targetId: definitionId, field: "content.risks", baseRevision: definition.revision, value: [...definition.content.risks, "Audit delivery may lag recovery."], artifactPath: definition.artifactPath, currentMeaning: definition.content.risks.join("; "), proposedMeaning: "The Definition records the additional audit-delivery risk." }; let state = changeEngine.propose(root, proposal(root, "Record recovery audit risk", [target], ["product", "engineering"])); const change = state.changes[0]; changeEngine.review(root, change.id); const beforeSynthetic = readFileSync(join(root, ".loopy/change-management/state.json"), "utf8"); expect(() => changeEngine.decide(root, { changeId: change.id, participant: "Priya and Emi", perspectives: ["product", "engineering"], explicitlyRepresents: ["product", "engineering"], decision: "accept", basis: "Combine their answers." })).toThrow("not recorded as representing"); expect(readFileSync(join(root, ".loopy/change-management/state.json"), "utf8")).toBe(beforeSynthetic); state = changeEngine.decide(root, { changeId: change.id, participant: "Emi", perspectives: ["engineering"], decision: "accept", basis: "Engineering agrees." }); expect(state.changes[0].receipts).toEqual([{ participant: "Emi", perspective: "engineering", revision: change.revision }]); state = changeEngine.decide(root, { changeId: change.id, participant: "Priya", perspectives: ["product"], decision: "accept", basis: "Product agrees and accepts the same reviewed proposal." }); expect(state.changes[0].status).toBe("accepted"); expect(state.changes[0].receipts.map(({ participant, perspective }) => ({ participant, perspective }))).toEqual([{ participant: "Emi", perspective: "engineering" }, { participant: "Priya", perspective: "product" }]); });

  it("allows one real participant to cover multiple explicitly represented perspectives", async () => { const { root, definitionId } = await committedDefinition(); const definition = definitionEngine.loadState(root).definitions[0]; const target: ChangeTarget = { kind: "milestone-definition", targetId: definitionId, field: "content.assumptions", baseRevision: definition.revision, value: [...definition.content.assumptions, "The same accountable lead covers Product and Engineering."], artifactPath: definition.artifactPath, currentMeaning: definition.content.assumptions.join("; "), proposedMeaning: "Record the confirmed cross-responsibility assumption." }; const input = proposal(root, "Record accountable lead assumption", [target], ["product", "engineering"]); input.participants = [{ name: "Alex", perspective: "product" }, { name: "Alex", perspective: "engineering" }]; let state = changeEngine.propose(root, input); const change = state.changes[0]; changeEngine.review(root, change.id); state = changeEngine.decide(root, { changeId: change.id, participant: "Alex", perspectives: ["product", "engineering"], explicitlyRepresents: ["product", "engineering"], decision: "accept", basis: "I explicitly represent both responsibilities and accept this revision." }); expect(state.changes[0].status).toBe("accepted"); expect(state.changes[0].receipts).toEqual([{ participant: "Alex", perspective: "product", revision: change.revision }, { participant: "Alex", perspective: "engineering", revision: change.revision }]); });

  it("synchronizes downstream anchors for an accepted Product-only change without changing their meaning", async () => { const { root } = await committedDefinition(); const beforeEngineering = engineeringEngine.loadState(root); const beforeRoadmap = roadmapEngine.loadState(root); const beforeDefinition = definitionEngine.loadState(root); let state = changeEngine.propose(root, proposal(root, "Product-only purpose clarification", [productTarget(root, "product.purpose", "Enable safe recovery for eligible customer accounts.")])); const change = state.changes[0]; changeEngine.review(root, change.id); state = changeEngine.decide(root, accept(change.id)); const product = productEngine.loadState(root); const engineering = engineeringEngine.loadState(root); const roadmap = roadmapEngine.loadState(root); const definition = definitionEngine.loadState(root); expect(engineering.engineering).toEqual(beforeEngineering.engineering); expect(roadmap.candidates).toEqual(beforeRoadmap.candidates); expect(definition.definitions).toEqual(beforeDefinition.definitions); expect(engineering.productRevision).toBe(product.revision); expect(roadmap.productRevision).toBe(product.revision); expect(definition.productRevision).toBe(product.revision); expect(state.changes[0].status).toBe("accepted"); });

  it("atomically reconciles exact Product, Engineering, Roadmap, and Definition targets", async () => { const { root, definitionId } = await committedDefinition(); const product = productEngine.loadState(root); const engineering = engineeringEngine.loadState(root); const roadmap = roadmapEngine.loadState(root); const definition = definitionEngine.loadState(root).definitions[0]; const targets: ChangeTarget[] = [
      { kind: "product", field: "product.constraints", baseRevision: product.revision, value: [...product.product.constraints, "Recovery audit events are retained."], artifactPath: "docs/loopy/Project-Definition.md", currentMeaning: "No explicit recovery-audit retention constraint.", proposedMeaning: "Recovery audit events are retained." },
      { kind: "engineering", field: "engineering.summary", baseRevision: engineering.revision, value: `${engineering.engineering.summary} Recovery audit retention is part of the confirmed foundation.`, artifactPath: "docs/loopy/Engineering-Guide.md", currentMeaning: engineering.engineering.summary, proposedMeaning: "Engineering guidance includes recovery audit retention." },
      { kind: "roadmap-candidate", targetId: "candidate-1", field: "rationale", baseRevision: roadmap.revision, value: "Customer recovery now includes the accepted audit-retention consequence.", artifactPath: "docs/loopy/Roadmap.md", currentMeaning: roadmap.candidates.find((item) => item.id === "candidate-1")!.rationale, proposedMeaning: "Roadmap rationale includes the accepted audit consequence." },
      { kind: "milestone-definition", targetId: definitionId, field: "content.constraints", baseRevision: definition.revision, value: [], artifactPath: definition.artifactPath, currentMeaning: "The Definition uses feasibility and constraints.", proposedMeaning: "No separate content.constraints field is introduced." },
    ];
    // A non-existent field proves target validation happens before proposal or artifact writes.
    const before = readFileSync(join(root, ".loopy/change-management/state.json"), "utf8"); expect(() => changeEngine.propose(root, proposal(root, "Invalid cross-foundation audit change", targets, ["product", "engineering"]))).toThrow("field does not exist"); expect(readFileSync(join(root, ".loopy/change-management/state.json"), "utf8")).toBe(before);
    let state = changeEngine.propose(root, proposal(root, "Cross-foundation audit change", targets.filter((item) => !(item.kind === "milestone-definition" && item.field === "content.constraints")), ["product", "engineering"])); const valid = state.changes[0]; changeEngine.review(root, valid.id); changeEngine.decide(root, { changeId: valid.id, participant: "Emi", perspectives: ["engineering"], decision: "accept", basis: "Engineering accepts all named technical consequences." }); state = changeEngine.decide(root, { changeId: valid.id, participant: "Priya", perspectives: ["product"], decision: "accept", basis: "Product accepts and authorizes reconciliation of the same reviewed proposal." }); expect(productEngine.loadState(root).product.constraints).toContain("Recovery audit events are retained."); expect(engineeringEngine.loadState(root).engineering.summary).toContain("Recovery audit retention"); expect(roadmapEngine.loadState(root).candidates.find((item) => item.id === "candidate-1")!.rationale).toContain("audit-retention"); expect(state.nextActions).toHaveLength(1); });

  it("blocks essential unknowns but permits explicit safe-to-wait unknowns", async () => { const root = await confirmedProduct(); const blocked = proposal(root, "Unknown promise boundary", [productTarget(root, "product.purpose", "Serve an expanded customer group.")]); blocked.unknowns = [{ description: "The affected contractual promise is unknown.", blocking: true, consequence: "Acceptance could contradict an external promise.", revisitWhen: "The contract owner provides the current promise." }]; blocked.coherence = { status: "blocked", basis: "An external promise boundary is essential." }; const blockedState = changeEngine.propose(root, blocked); expect(blockedState.changes[0].status).toBe("blocked"); expect(() => changeEngine.review(root, blockedState.changes[0].id)).toThrow("essential unknown"); const safe = proposal(root, "Clarify recovery purpose", [productTarget(root, "product.purpose", "Restore eligible access safely.")]); safe.unknowns = [{ description: "Final training copy is not chosen.", blocking: false, consequence: "Wording may be refined without changing this boundary.", revisitWhen: "Training material is drafted." }]; const safeState = changeEngine.propose(root, safe); expect(() => changeEngine.review(root, safeState.changes.at(-1)!.id)).not.toThrow(); });

  it("rejects and withdraws without mutating accepted meaning and removes them from active view", async () => { const root = await confirmedProduct(); const original = productEngine.loadState(root).product.purpose; let state = changeEngine.propose(root, proposal(root, "Rejected purpose", [productTarget(root, "product.purpose", "Rejected replacement.")])); const rejected = state.changes[0]; changeEngine.decide(root, { changeId: rejected.id, participant: "Priya", perspectives: ["product"], decision: "reject", basis: "Keep the accepted purpose." }); state = changeEngine.propose(root, proposal(root, "Withdrawn purpose", [productTarget(root, "product.purpose", "Withdrawn replacement.")])); const withdrawn = state.changes.at(-1)!; state = changeEngine.decide(root, { changeId: withdrawn.id, participant: "Priya", perspectives: ["product"], decision: "withdraw", basis: "The proposer withdrew it." }); expect(productEngine.loadState(root).product.purpose).toBe(original); const home = readFileSync(join(root, "LOOPY.md"), "utf8"); expect(home).toContain("No active material changes."); expect(home).toContain("Rejected purpose"); expect(state.changes.map((item) => item.status)).toEqual(["rejected", "withdrawn"]); });

  it("defers without canonical mutation and uses deterministic collision-safe readable paths", async () => { const root = await confirmedProduct(); const original = productEngine.loadState(root).product.purpose; let state = changeEngine.propose(root, proposal(root, "Purpose choice", [productTarget(root, "product.purpose", "First proposed purpose.")])); const first = state.changes[0]; state = changeEngine.decide(root, { changeId: first.id, participant: "Priya", perspectives: ["product"], decision: "defer", basis: "Wait for the next Product review.", reason: "Revisit when the next Product review supplies the missing judgment." }); expect(state.changes[0].status).toBe("deferred"); expect(productEngine.loadState(root).product.purpose).toBe(original); state = changeEngine.propose(root, proposal(root, "Purpose choice", [productTarget(root, "product.purpose", "Second proposed purpose.")])); expect(state.changes.map((item) => item.artifactPath)).toEqual(["docs/loopy/changes/purpose-choice/Change.md", "docs/loopy/changes/purpose-choice-2/Change.md"]); expect(state.nextActions).toHaveLength(1); });

  it("allows independent proposals and rejects an overlapping stale proposal without mutation", async () => { const root = await confirmedProduct(); const baseSummary = productTarget(root, "product.summary", "A clearer Harbor summary."); const basePurpose = productTarget(root, "product.purpose", "A clearer Harbor purpose."); let state = changeEngine.propose(root, proposal(root, "Summary change", [baseSummary])); const first = state.changes[0]; state = changeEngine.propose(root, proposal(root, "Independent purpose change", [basePurpose])); const independent = state.changes[1]; state = changeEngine.propose(root, proposal(root, "Overlapping summary change", [{ ...baseSummary, value: "A competing summary.", proposedMeaning: "A competing summary." }])); const overlap = state.changes[2]; changeEngine.review(root, first.id); changeEngine.review(root, independent.id); changeEngine.review(root, overlap.id); changeEngine.decide(root, accept(first.id)); changeEngine.decide(root, accept(independent.id)); const before = readFileSync(join(root, ".loopy/change-management/state.json"), "utf8"); expect(() => changeEngine.decide(root, accept(overlap.id))).toThrow("stale because its exact canonical target changed"); expect(readFileSync(join(root, ".loopy/change-management/state.json"), "utf8")).toBe(before); });

  it("revalidates exact Product, Engineering, Roadmap, and Definition targets immediately before acceptance", async () => {
    for (const kind of ["product", "engineering", "roadmap-candidate", "milestone-definition"] as const) {
      const { root, definitionId } = await committedDefinition(); const product = productEngine.loadState(root); const engineering = engineeringEngine.loadState(root); const roadmap = roadmapEngine.loadState(root); const definition = definitionEngine.loadState(root).definitions[0];
      const target: ChangeTarget = kind === "product" ? { kind, field: "product.summary", baseRevision: product.revision, value: "Materially revised Harbor summary.", artifactPath: "docs/loopy/Project-Definition.md", currentMeaning: product.product.summary, proposedMeaning: "A revised Product summary." }
        : kind === "engineering" ? { kind, field: "engineering.summary", baseRevision: engineering.revision, value: "Materially revised Engineering summary.", artifactPath: "docs/loopy/Engineering-Guide.md", currentMeaning: engineering.engineering.summary, proposedMeaning: "A revised Engineering summary." }
        : kind === "roadmap-candidate" ? { kind, targetId: "candidate-1", field: "rationale", baseRevision: roadmap.revision, value: "Materially revised Roadmap rationale.", artifactPath: "docs/loopy/Roadmap.md", currentMeaning: roadmap.candidates.find((item) => item.id === "candidate-1")!.rationale, proposedMeaning: "A revised Roadmap rationale." }
        : { kind, targetId: definitionId, field: "content.risks", baseRevision: definition.revision, value: ["Materially revised risk."], artifactPath: definition.artifactPath, currentMeaning: definition.content.risks.join("; "), proposedMeaning: "A revised Definition risk." };
      const perspectives: Array<"product" | "engineering"> = kind === "engineering" ? ["engineering"] : kind === "milestone-definition" ? ["product", "engineering"] : ["product"];
      let state = changeEngine.propose(root, proposal(root, `Stale ${kind} target`, [target], perspectives)); const change = state.changes[0]; changeEngine.review(root, change.id);
      if (kind === "milestone-definition") changeEngine.decide(root, { changeId: change.id, participant: "Priya", perspectives: ["product"], decision: "accept", basis: "Product agrees to the reviewed proposal." });
      const currentRevision = kind === "product" ? productEngine.loadState(root).revision : kind === "engineering" ? engineeringEngine.loadState(root).revision : kind === "roadmap-candidate" ? roadmapEngine.loadState(root).revision : definitionEngine.loadState(root).definitions[0].revision;
      const correction: ChangeTarget = { ...target, baseRevision: currentRevision, value: kind === "product" ? "Harbor support recovery visibility." : kind === "engineering" ? "Engineering guidance for Harbor recovery." : kind === "roadmap-candidate" ? "Customer recovery outcome rationale." : ["Sensitive recovery state."], currentMeaning: target.currentMeaning, proposedMeaning: "Equivalent wording confirmed independently of the proposal." };
      changeEngine.applyRoutine(root, routine(correction, `Applied an intervening ${kind} correction.`));
      state = changeEngine.loadState(root); const paths = [".loopy/change-management/state.json", ".loopy/start-or-adopt/state.json", ".loopy/engineering-foundation/state.json", ".loopy/living-roadmap/state.json", ".loopy/milestone-definition/state.json", "LOOPY.md", "docs/loopy/Project-Definition.md", "docs/loopy/Engineering-Guide.md", "docs/loopy/Roadmap.md", definition.artifactPath, state.changes[0].artifactPath]; const before = snapshot(root, paths);
      const finalDecision = kind === "engineering" ? { changeId: change.id, participant: "Emi", perspectives: ["engineering"] as const, decision: "accept" as const, basis: "Engineering accepts." } : kind === "milestone-definition" ? { changeId: change.id, participant: "Emi", perspectives: ["engineering"] as const, decision: "accept" as const, basis: "Engineering supplies the final receipt." } : accept(change.id);
      expect(() => changeEngine.decide(root, finalDecision)).toThrow("stale because its exact canonical target changed"); expect(snapshot(root, paths)).toEqual(before);
    }
  });

  it("rolls back a stale multi-target acceptance without consuming accumulated receipts", async () => { const { root } = await committedDefinition(); const product = productEngine.loadState(root); const engineering = engineeringEngine.loadState(root); const targets: ChangeTarget[] = [productTarget(root, "product.summary", "Revised cross-foundation summary."), { kind: "engineering", field: "engineering.summary", baseRevision: engineering.revision, value: "Revised cross-foundation technical summary.", artifactPath: "docs/loopy/Engineering-Guide.md", currentMeaning: engineering.engineering.summary, proposedMeaning: "A revised technical summary." }]; let state = changeEngine.propose(root, proposal(root, "Stale multi-target change", targets, ["product", "engineering"])); const change = state.changes[0]; changeEngine.review(root, change.id); changeEngine.decide(root, { changeId: change.id, participant: "Priya", perspectives: ["product"], decision: "accept", basis: "Product agrees." }); const currentEngineering = engineeringEngine.loadState(root); changeEngine.applyRoutine(root, routine({ ...targets[1], baseRevision: currentEngineering.revision, value: "Equivalent corrected Engineering summary." }, "Applied an intervening Engineering correction.")); state = changeEngine.loadState(root); const paths = [".loopy/change-management/state.json", ".loopy/start-or-adopt/state.json", ".loopy/engineering-foundation/state.json", ".loopy/living-roadmap/state.json", ".loopy/milestone-definition/state.json", "LOOPY.md", "docs/loopy/Project-Definition.md", "docs/loopy/Engineering-Guide.md", "docs/loopy/Roadmap.md", state.changes[0].artifactPath]; const before = snapshot(root, paths); expect(() => changeEngine.decide(root, { changeId: change.id, participant: "Emi", perspectives: ["engineering"], decision: "accept", basis: "Engineering supplies the final receipt." })).toThrow("stale because its exact canonical target changed"); expect(snapshot(root, paths)).toEqual(before); expect(changeEngine.loadState(root).changes[0].receipts).toEqual([{ participant: "Priya", perspective: "product", revision: change.revision }]); });

  it("renders one active Change entry per affected artifact and one project next action", async () => { const { root, definitionId } = await committedDefinition(); const definition = definitionEngine.loadState(root).definitions[0]; const targets: ChangeTarget[] = [{ kind: "milestone-definition", targetId: definitionId, field: "content.risks", baseRevision: definition.revision, value: [...definition.content.risks, "Audit lag"], artifactPath: definition.artifactPath, currentMeaning: definition.content.risks.join("; "), proposedMeaning: "Add audit lag risk." }, { kind: "milestone-definition", targetId: definitionId, field: "content.assumptions", baseRevision: definition.revision, value: [...definition.content.assumptions, "Audit storage remains available"], artifactPath: definition.artifactPath, currentMeaning: definition.content.assumptions.join("; "), proposedMeaning: "Add audit storage assumption." }]; const state = changeEngine.propose(root, proposal(root, "One linked Definition change", targets, ["product", "engineering"])); const definitionView = readFileSync(join(root, definition.artifactPath), "utf8"); const home = readFileSync(join(root, "LOOPY.md"), "utf8"); expect(definitionView.match(/## Proposed change/g)).toHaveLength(1); expect(definitionView.match(/One linked Definition change/g)).toHaveLength(1); expect(home.match(/\[One linked Definition change\]/g)).toHaveLength(1); expect(home.match(/## Next action/g)).toHaveLength(1); expect(state.nextActions).toHaveLength(1); });

  it("rolls back atomic reconciliation failure and creates no later-stage artifacts", async () => { const root = await confirmedProduct(); const state = changeEngine.propose(root, proposal(root, "Atomic purpose change", [productTarget(root, "product.purpose", "An atomic revised purpose.")])); const change = state.changes[0]; changeEngine.review(root, change.id); const beforeState = readFileSync(join(root, ".loopy/change-management/state.json"), "utf8"); const beforeProduct = readFileSync(join(root, ".loopy/start-or-adopt/state.json"), "utf8"); const failing = await ChangeManagementEngine.create(sourceRoot, { beforeCommit: (path) => { if (path === "docs/loopy/Project-Definition.md") throw new Error("injected reconciliation failure"); } }); expect(() => failing.decide(root, accept(change.id))).toThrow("injected reconciliation failure"); expect(readFileSync(join(root, ".loopy/change-management/state.json"), "utf8")).toBe(beforeState); expect(readFileSync(join(root, ".loopy/start-or-adopt/state.json"), "utf8")).toBe(beforeProduct); for (const forbidden of ["Plan.md", "Proof.md", "Demo.md", "Release.md"]) expect(existsSync(join(root, forbidden))).toBe(false); });

  it("rejects partial-acceptance input and out-of-contract artifact paths without mutation", async () => { const root = await confirmedProduct(); const state = changeEngine.propose(root, proposal(root, "Bounded purpose change", [productTarget(root, "product.purpose", "A bounded revised purpose.")])); const change = state.changes[0]; changeEngine.review(root, change.id); const before = readFileSync(join(root, ".loopy/change-management/state.json"), "utf8"); expect(() => changeEngine.decide(root, { ...accept(change.id), targetIds: ["some-target"] } as any)).toThrow("Partial acceptance is not supported"); expect(readFileSync(join(root, ".loopy/change-management/state.json"), "utf8")).toBe(before); const bad = proposal(root, "Escaping target", [{ ...productTarget(root, "product.summary", "Equivalent summary."), artifactPath: "../outside.md" }]); expect(() => changeEngine.propose(root, bad)).toThrow("exact contained human artifact path"); expect(readFileSync(join(root, ".loopy/change-management/state.json"), "utf8")).toBe(before); });

  it("persists ordinary proposal updates privately and publishes on pause, status, and explicit render", async () => { const root = await confirmedProduct(); let state = changeEngine.propose(root, proposal(root, "Cadence change", [productTarget(root, "product.purpose", "A revised cadence purpose.")])); const change = state.changes[0]; const published = readFileSync(join(root, change.artifactPath), "utf8"); state = changeEngine.update(root, { changeId: change.id, reason: "A refined but still incomplete material reason." , coherence: { status: "draft", basis: "" } }); expect(readFileSync(join(root, change.artifactPath), "utf8")).toBe(published); expect(await changeEngine.detectStaleViews(root)).not.toEqual([]); changeEngine.interrupt(root, change.id, "resolve the remaining consequence"); expect(readFileSync(join(root, change.artifactPath), "utf8")).toContain("refined but still incomplete"); expect(await changeEngine.detectStaleViews(root)).toEqual([]); writeFileSync(join(root, "LOOPY.md"), "stale\n", "utf8"); const before = readFileSync(join(root, ".loopy/change-management/state.json"), "utf8"); await expect(changeEngine.resume(root)).rejects.toThrow("explicitly repair"); expect(readFileSync(join(root, ".loopy/change-management/state.json"), "utf8")).toBe(before); changeEngine.renderCurrent(root); await changeEngine.resume(root); expect(changeEngine.status(root).session.status).toBe("active"); });

  it("preserves synchronized Change Management views through earlier lifecycle renderers", async () => { const { root } = await committedDefinition(); const state = changeEngine.propose(root, proposal(root, "Shared-view purpose change", [productTarget(root, "product.purpose", "A revised shared-view purpose.")])); const change = state.changes[0]; await productEngine.renderCurrent(root); engineeringEngine.renderCurrent(root); roadmapEngine.renderCurrent(root); definitionEngine.renderCurrent(root); const home = readFileSync(join(root, "LOOPY.md"), "utf8"); expect(home).toContain("## Change Management"); expect(home).toContain("Shared-view purpose change"); expect(readFileSync(join(root, change.artifactPath), "utf8")).toContain("**Status:** draft"); expect(await changeEngine.detectStaleViews(root)).toEqual([]); });

  it("keeps Change Management inside the single skill and distinguishes mechanics from behavioral proof", async () => { const skill = readFileSync(join(sourceRoot, "skills/loopy/SKILL.md"), "utf8"); const interview = readFileSync(join(sourceRoot, "skills/loopy/references/interviews/Change-Management.md"), "utf8"); const engineGuide = readFileSync(join(sourceRoot, "skills/loopy/references/engine/Change-Management-Apply.md"), "utf8"); const scenario = readFileSync(join(sourceRoot, "evaluation/scenarios/change-management/Scenario.md"), "utf8"); expect(skill).toContain("references/interviews/Change-Management.md"); expect(interview).toContain("Never expose this route as a separate skill or command"); expect(interview).toContain("A clear natural-language final response can accept"); expect(interview).toContain("does not partially accept one proposal"); expect(interview).toContain("Ordinary proposal updates persist canonical `.loopy` state without repeatedly publishing"); expect(interview).toContain("Do not declare a correction routine while its meaning is uncertain"); expect(interview).toContain("Do not invent a combined participant identity"); expect(engineGuide).toContain("meaningUncertainty: none"); expect(engineGuide).toContain("rechecks every exact target against its captured base value and revision"); expect(scenario).toContain("do not prove the Host AI's behavioral quality"); expect(changeEngine.contract.proposal_is_not_canonical).toBe(true); expect(changeEngine.contract.affected_only_atomic_reconciliation).toBe(true); expect(changeEngine.contract.routine_requires_resolved_meaning_declaration).toBe(true); expect(parseCliArguments(["change-propose", "--workspace", "/tmp/project", "--input", "/tmp/change.json"]).command).toBe("change-propose"); expect(() => parseCliArguments(["change-decide", "--workspace", "/tmp/project"])).toThrow("--input"); });
});
