import { createHash } from "node:crypto";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { ProductStartEngine } from "../src/engine.js";
import { EngineeringFoundationEngine } from "../src/engineering-engine.js";
import { LivingRoadmapEngine } from "../src/living-roadmap-engine.js";
import { MilestoneDefinitionEngine } from "../src/milestone-definition-engine.js";
import { MilestonePlanningEngine } from "../src/milestone-planning-engine.js";
import { MilestoneBuildEngine } from "../src/milestone-build-engine.js";
import { MILESTONE_DEMO_STATE_PATH, MilestoneDemoEngine } from "../src/milestone-demo-engine.js";
import type { EngineeringFoundationUpdate } from "../src/engineering-types.js";
import type { DefinitionUpdate } from "../src/milestone-definition-types.js";
import type { MilestonePlan, PlanningUpdate } from "../src/milestone-planning-types.js";
import type { BuildActivation, BuildWorkUpdate, EvaluationInput, ModelChoice, TaskAssignmentInput } from "../src/milestone-build-types.js";
import type { DemoActivation, DemoDecision, DemoObservation } from "../src/milestone-demo-types.js";
import type { ProductStartUpdate } from "../src/types.js";
import { parseCliArguments } from "../src/cli-arguments.js";
import { parse } from "yaml";

const sourceRoot = resolve(import.meta.dirname, "../..");
const fixture = join(sourceRoot, "evaluation/scenarios/product-start/large-mixed-project/fixture");
const productSetup = join(sourceRoot, "evaluation/scenarios/product-start/large-mixed-project/setup/v1/product-update.json");
const roots: string[] = [];
const A = "a".repeat(64), B = "b".repeat(64), C = "c".repeat(64), W = "e".repeat(64), ENV = "9".repeat(64), TARGET = "7".repeat(64), DEMO_EVIDENCE = "Exact controlled target and observable result.\n", DEMO_EVIDENCE_HASH = createHash("sha256").update(DEMO_EVIDENCE).digest("hex");
let product: ProductStartEngine, engineering: EngineeringFoundationEngine, roadmap: LivingRoadmapEngine, definition: MilestoneDefinitionEngine, planning: MilestonePlanningEngine, build: MilestoneBuildEngine, demo: MilestoneDemoEngine;

beforeAll(async () => { product = await ProductStartEngine.create(sourceRoot); engineering = await EngineeringFoundationEngine.create(sourceRoot); roadmap = await LivingRoadmapEngine.create(sourceRoot); definition = await MilestoneDefinitionEngine.create(sourceRoot); planning = await MilestonePlanningEngine.create(sourceRoot); build = await MilestoneBuildEngine.create(sourceRoot); demo = await MilestoneDemoEngine.create(sourceRoot); });
afterAll(() => roots.forEach((root) => rmSync(root, { recursive: true, force: true })));

function engineeringUpdates(): EngineeringFoundationUpdate[] { const reference = readFileSync(join(sourceRoot, "skills/loopy/references/engine/Engineering-Foundation-Apply.md"), "utf8"); return [...reference.matchAll(/<!-- engineering-apply-example -->\n```json\n([\s\S]*?)\n```/g)].map((match) => JSON.parse(match[1])); }
function planUpdate(planId: string): PlanningUpdate { const workUnits = [{ key: "foundation", title: "Establish the outcome path", contribution: "Makes the outcome observable.", affectedAreas: ["delivery path"], responsibility: "Engineering", completionObservation: "The supported result is observable.", checks: ["Outcome path check"], workspace: "same-directory" as const, order: 1 }, { key: "boundary", title: "Verify the acceptance boundary", contribution: "Preserves supported and rejected behavior.", affectedAreas: ["checks and evidence"], responsibility: "Engineering", completionObservation: "Accepted and rejected paths are evidenced.", checks: ["Acceptance boundary check"], workspace: "same-directory" as const, order: 2 }]; const final = { checkpoint: "Integrated Milestone evaluation", evaluationType: "final-integrated-independent" as const, workUnits: ["foundation", "boundary"], trigger: "After every Work Unit composes into one frozen candidate", reason: "The full committed boundary requires independent integrated evaluation.", correctionCycleLimit: 1, required: true }; return { planId, actor: { name: "Emi", responsibility: "engineering" }, content: { approach: ["Deliver the bounded outcome, then evaluate the integrated candidate."], workUnits, dependencies: [{ from: "foundation", to: "boundary", kind: "required-before", note: "The outcome path precedes boundary verification." }], parallelism: [], parallelClaims: [{ workUnits: ["foundation", "boundary"], disposition: "blocked", conflicts: ["required-before dependency"], basis: "Boundary verification follows implementation." }], checksAndEvidence: ["Preserve exact command output"], evaluationBoundaries: [final], risks: ["Integration behavior"], unknowns: [], releaseImpact: [] }, participants: [{ name: "Emi", responsibility: "Engineering" }], workspaceDisposition: { mode: "same-directory", location: "", basis: "The controlled units share one project." }, guideTriggers: [], coherence: { status: "coherent", basis: "The bounded approach and evaluation budget remain inside the Definition." } }; }
function models(): ModelChoice[] { return (["orchestrator", "builder", "focused-evaluator", "final-evaluator"] as const).map((role) => ({ role, host: "available-local-host", model: `role-model-${role}`, settingsProfile: "balanced", available: true as const, recommended: true, qualification: "tested" as const, unverifiedNotice: null })); }
function activation(root: string, plan: MilestonePlan, units: string[], source: string): BuildActivation { return { planId: plan.id, participant: "Morgan", responsibilities: ["engineering", "build orchestration"], workUnits: units, workspace: { mode: "same-directory", location: root, fingerprint: W }, allowedTools: ["editor", "test-runner"], sourceControlOperations: ["edit", "check"], externalSystems: [], modelChoices: models(), costChoice: "Use the confirmed local budget.", sourceFingerprint: source, evaluationBudget: plan.content.evaluationBoundaries }; }
function assignment(buildId: string, role: TaskAssignmentInput["role"], participant: string, units: string[], checkpoint: string | null, source: string): TaskAssignmentInput { const evaluator = role.endsWith("evaluator"); return { buildId, role, participant, responsibility: evaluator ? "independent evaluation" : "engineering", workUnits: units, checkpoint, host: "available-local-host", model: `role-model-${role}`, settingsProfile: "balanced", sourceFingerprint: source, workspaceFingerprint: W, taskContextIdentity: `${role}-${participant}-${checkpoint ?? units.join("-")}`, evaluationWorkspace: evaluator ? { location: `/tmp/loopy-${role}-${participant}`, fingerprint: "f".repeat(64), clean: true, disposable: true } : null, recommendationBasis: "The current bounded work fits this available model." }; }
function work(root: string, buildId: string, key: string, before: string, after: string): BuildWorkUpdate { return { buildId, workUnitKey: key, participant: "Blair", responsibility: "engineering", status: "completed", tool: "editor", sourceControlOperation: "edit", externalSystem: null, workspaceLocation: root, workspaceFingerprint: W, sourceFingerprintBefore: before, sourceFingerprintAfter: after, summary: `Completed ${key} inside the Plan boundary.`, evidence: [{ key: `work-${key}-${after[0]}`, kind: "command", summary: `${key} check`, reference: `inert://${key}/${after[0]}`, result: "passed" }], effect: { status: "completed", detail: "The controlled inert result completed." }, boundaryDisposition: "within-plan", coordination: { checked: true, conflicts: [] } }; }

async function readyBuild() {
  const root = mkdtempSync(join(tmpdir(), "loopy-demo-")); roots.push(root); cpSync(fixture, root, { recursive: true });
  mkdirSync(join(root, "demo-evidence"), { recursive: true }); writeFileSync(join(root, "demo-evidence/observation.txt"), DEMO_EVIDENCE);
  await product.initialize(root, "Harbor", { participantResponsibilities: ["product"] }); product.applyUpdate(root, JSON.parse(readFileSync(productSetup, "utf8")) as ProductStartUpdate); await product.recordProductReview(root); await product.confirmProduct(root);
  engineering.initialize(root, { participantResponsibilities: ["engineering"] }); for (const update of engineeringUpdates()) engineering.applyUpdate(root, update); engineering.recordReview(root); engineering.confirm(root);
  roadmap.initialize(root); roadmap.applyOperation(root, { type: "set-dependencies", candidateId: "candidate-1", dependencies: [], actor: { name: "Emi", responsibility: "engineering" } }); roadmap.applyOperation(root, { type: "select", candidateIds: ["candidate-1"], actor: { name: "Priya", responsibility: "product" } });
  let definitions = definition.initialize(root), item = definitions.definitions[0]; definition.applyUpdate(root, { type: "update", definitionId: item.id, actor: { name: "Loopy", perspectives: ["product", "engineering"] }, content: { outcome: item.content.outcome, requirements: ["Deliver the committed customer recovery outcome."], inScope: ["The supported recovery path"], nonGoals: ["Unrelated Product changes"], acceptance: ["A supported recovery reaches the intended customer-visible result.", "An unsupported recovery is rejected with a readable reason."], dependencies: item.content.dependencies, feasibilityAndConstraints: ["Preserve confirmed guidance"], risks: ["Integration behavior"], assumptions: ["Foundations remain current"], unknowns: [] }, coherence: { status: "coherent", basis: "Outcome, scope, feasibility, and observable acceptance agree." }, requiredPerspectives: ["product", "engineering"] } as DefinitionUpdate); definitions = definition.loadState(root); definition.review(root, [item.id]); definition.confirm(root, [{ definitionId: item.id, participant: "Emi", perspectives: ["engineering"], commit: false }]); definition.confirm(root, [{ definitionId: item.id, participant: "Priya", perspectives: ["product"], commit: true }]);
  let planningState = planning.initialize(root, [item.id]); planningState = planning.applyUpdate(root, planUpdate(planningState.plans[0].id)); planningState = planning.review(root, { planIds: [planningState.plans[0].id] }); const plan = planningState.plans[0];
  let buildState = build.initialize(root, activation(root, plan, ["foundation"], A)), current = buildState.builds[0]; build.assignTask(root, assignment(current.id, "builder", "Blair", ["foundation"], null, A)); build.recordWork(root, work(root, current.id, "foundation", A, B)); build.activate(root, activation(root, plan, ["boundary"], B)); build.assignTask(root, assignment(current.id, "builder", "Blair", ["boundary"], null, B)); build.recordWork(root, work(root, current.id, "boundary", B, C)); build.assignTask(root, assignment(current.id, "final-evaluator", "Quinn", ["foundation", "boundary"], "Integrated Milestone evaluation", C)); buildState = build.freezeCandidate(root, { buildId: current.id, kind: "integrated", checkpoint: "Integrated Milestone evaluation", workUnits: ["foundation", "boundary"], sourceFingerprint: C, workspaceFingerprint: W, parentCandidateId: null }); current = buildState.builds[0]; const candidate = current.candidates[0], defined = definition.loadState(root).definitions[0], checks = [...new Set([...plan.content.checksAndEvidence, ...plan.content.workUnits.flatMap((unit) => unit.checks)])], evidenceKey = "final-observation";
  const evaluation: EvaluationInput = { buildId: current.id, candidateId: candidate.id, checkpoint: "Integrated Milestone evaluation", assignmentId: "assignment-3", evaluator: "Quinn", responsibility: "independent evaluation", charter: { definitionRevision: defined.revision, planRevision: plan.revision, candidateId: candidate.id, candidateFingerprint: C, workUnits: ["foundation", "boundary"], acceptanceCriteria: defined.content.acceptance, plannedChecks: checks, allowedTools: ["test-runner"], neutralPosture: "unproven" }, verdict: "pass", evidence: [{ key: evidenceKey, kind: "observation", summary: "Independent integrated observations", reference: "inert://final/evaluation", result: "passed" }], acceptanceCoverage: defined.content.acceptance.map((criterion) => ({ item: criterion, evidenceIds: [evidenceKey], status: "supported" })), checkCoverage: checks.map((check) => ({ item: check, evidenceIds: [evidenceKey], status: "supported" })), findings: [], limitations: [], skips: [], unproven: [] };
  buildState = build.recordEvaluation(root, evaluation); current = buildState.builds[0]; return { root, plan, defined, build: current, candidate: current.candidates[0] };
}

function demoActivation(ready: Awaited<ReturnType<typeof readyBuild>>, modes: DemoActivation["modes"] = ["human-guided", "ai-operated-recorded"]): DemoActivation { return { buildId: ready.build.id, candidateId: ready.candidate.id, modes, method: { surface: "customer-visible status interaction", summary: "Guide the recovery path and preserve a recorded request/result trace.", basis: "The committed outcome has an observable user path and a non-visual rejected-path response." }, authority: { participant: "Dana", perspectiveContext: "Customer outcome judgment and direct observation", candidateId: ready.candidate.id, sourceFingerprint: C, workspaceFingerprint: W, environment: { name: "Controlled local demonstration", fingerprint: ENV }, target: { name: "Exact controlled candidate target", fingerprint: TARGET, verificationBasis: "Verify the served target marker and candidate-bound content before observation." }, tools: ["browser-capable observer", "request-response observer"], actions: ["Operate the controlled recovery examples", "Capture linked observations"], scope: ["The committed customer-recovery outcome"], externalSystems: [], externalEffects: [], consequentialPermissions: [], accessibilityNeeds: ["Provide a text equivalent for visual observations"], productMutationAllowed: false }, scenarios: [{ key: "recovery", title: "Supported recovery", whatToObserve: "The customer sees the intended recovery result.", mode: modes[0], replayable: false, order: 1 }] }; }
function observation(demoId: string, criteria: string[], readiness: DemoObservation["readiness"] = { status: "ready-for-judgment", basis: "Every criterion has an inspectable observable disposition." }): DemoObservation { const active = readiness.status === "active", targetKey = active ? "target-active" : "target-final"; const evidence: DemoObservation["evidence"] = [{ key: targetKey, kind: "observation", summary: "Verified the operated target identity", reference: "demo-evidence/observation.txt", referenceKind: "workspace-file", fingerprint: DEMO_EVIDENCE_HASH, result: "passed", operator: "human", tool: "browser-capable observer", action: "Operate the controlled recovery examples", externalSystem: null }, ...(active ? [] : [{ key: "demo-observation", kind: "observation" as const, summary: "Observed supported and rejected recovery behavior", reference: "demo-evidence/observation.txt", referenceKind: "workspace-file" as const, fingerprint: DEMO_EVIDENCE_HASH, result: "passed" as const, operator: "human" as const, tool: "browser-capable observer", action: "Operate the controlled recovery examples", externalSystem: null }])]; return { demoId, sourceFingerprint: C, workspaceFingerprint: W, environmentFingerprint: ENV, targetVerification: { expectedTargetFingerprint: TARGET, observedTargetFingerprint: TARGET, method: "Compared the served target marker with the authorized target identity.", evidenceIds: [targetKey] }, productMutation: "none", scenario: { key: "recovery", status: active ? "in-progress" : "demonstrated", result: active ? "The guided interaction is underway." : "The supported and rejected paths were observed.", limitations: [], partialEffects: [] }, evidence, coverage: active ? [] : criteria.map((criterion) => ({ criterion, status: "demonstrated", scenarioKeys: ["recovery"], evidenceIds: ["demo-observation"], note: "Observed against the exact frozen candidate." })), whatDemonstrated: "The supported recovery and readable rejection paths", observedResult: active ? "Observation is in progress" : "The committed observable boundary was demonstrated", limitations: [], unproven: [], readiness }; }
function decision(ready: Awaited<ReturnType<typeof readyBuild>>, demoId: string, revision: number, kind: DemoDecision["decision"] = "accept", route?: DemoDecision["correctionRoute"]): DemoDecision { return { demoId, candidateId: ready.candidate.id, sourceFingerprint: C, workspaceFingerprint: W, environmentFingerprint: ENV, reviewedRevision: revision, actorKind: "human", participant: "Avery", perspectiveContext: "Customer operations judgment informed by the observable result", personalJudgment: true, naturalLanguageIntent: kind === "accept" ? "This outcome is acceptable." : kind === "request-correction" ? "Please correct this result." : "Defer this decision.", decision: kind, acceptedOutcome: kind === "accept" ? ready.defined.content.outcome : undefined, acceptedBoundary: kind === "accept" ? ready.defined.content.acceptance : undefined, correctionRoute: route, reason: kind === "accept" ? "The exact demonstrated outcome meets the committed boundary." : "The current result should not be accepted yet.", revisitWhen: kind === "defer" ? "the customer operations review is available" : undefined }; }
function snapshot(root: string, demoPath: string) { return Object.fromEntries([MILESTONE_DEMO_STATE_PATH, "LOOPY.md", "docs/loopy/Roadmap.md", demoPath].filter((path) => existsSync(join(root, path))).map((path) => [path, readFileSync(join(root, path), "utf8")])); }

describe("Milestone Demonstrate and Accept", () => {
  it("enters only from the exact ready candidate and current published anchors", async () => { const ready = await readyBuild(); const input = demoActivation(ready); input.candidateId = "candidate-missing"; input.authority.candidateId = "candidate-missing"; await expect(demo.initialize(ready.root, input)).rejects.toThrow("exact current integrated"); expect(existsSync(join(ready.root, MILESTONE_DEMO_STATE_PATH))).toBe(false); writeFileSync(join(ready.root, ready.build.artifactPath), "stale proof\n"); await expect(demo.initialize(ready.root, demoActivation(ready))).rejects.toThrow("views are stale"); expect(existsSync(join(ready.root, MILESTONE_DEMO_STATE_PATH))).toBe(false); });

  it("publishes a digestible exact-candidate Demo for human-guided and recorded modes", async () => { const ready = await readyBuild(), state = await demo.initialize(ready.root, demoActivation(ready)), item = state.demos[0], view = readFileSync(join(ready.root, item.artifactPath), "utf8"), opening = view.split("\n").slice(0, 18).join("\n"); expect(opening).toContain("Requested outcome | What was demonstrated | Result | Important limitations or unproven behavior | Human decision or next action"); expect(opening).toContain(ready.defined.content.outcome); expect(opening).not.toContain(C); expect(view).toContain("Human-guided live and AI-operated recorded"); expect(view).toContain("Commands, logs, screenshots, recordings, hashes"); expect(readFileSync(join(ready.root, "LOOPY.md"), "utf8").match(/^## Next action$/gm)).toHaveLength(1); expect(readFileSync(join(ready.root, "docs/loopy/Roadmap.md"), "utf8")).toContain("Demonstration and Acceptance status"); });

  it("supports human-guided, AI-operated recorded, and combined mode choices", async () => { for (const modes of [["human-guided"], ["ai-operated-recorded"], ["human-guided", "ai-operated-recorded"]] as DemoActivation["modes"][]) { const ready = await readyBuild(), input = demoActivation(ready, modes); input.scenarios[0].mode = modes[0]; const state = await demo.initialize(ready.root, input); expect(state.demos[0].modes).toEqual(modes); } });

  it("binds recorded evidence to the authorized operator, action, tool, environment, and verified target", async () => { const ready = await readyBuild(), input = demoActivation(ready, ["ai-operated-recorded"]); input.scenarios[0].mode = "ai-operated-recorded"; let state = await demo.initialize(ready.root, input), item = state.demos[0], recorded = observation(item.id, ready.defined.content.acceptance); recorded.evidence.forEach((entry) => { entry.operator = "host-ai"; }); state = demo.observe(ready.root, recorded); expect(state.demos[0].evidence[0]).toMatchObject({ operator: "host-ai", tool: "browser-capable observer", action: "Operate the controlled recovery examples", environmentFingerprint: ENV, targetFingerprint: TARGET }); const other = await readyBuild(), humanInput = demoActivation(other, ["human-guided"]); let otherState = await demo.initialize(other.root, humanInput), otherItem = otherState.demos[0], wrong = observation(otherItem.id, other.defined.content.acceptance); wrong.evidence[0].operator = "host-ai"; const before = snapshot(other.root, otherItem.artifactPath); expect(() => demo.observe(other.root, wrong)).toThrow("operator must match"); expect(snapshot(other.root, otherItem.artifactPath)).toEqual(before); });

  it("rejects an operated-target collision as a Demo environment failure without candidate-failure mutation", async () => { const ready = await readyBuild(); let state = await demo.initialize(ready.root, demoActivation(ready)), item = state.demos[0], before = snapshot(ready.root, item.artifactPath), wrong = observation(item.id, ready.defined.content.acceptance); wrong.targetVerification.observedTargetFingerprint = "8".repeat(64); expect(() => demo.observe(ready.root, wrong)).toThrow("Demo environment/target failure"); expect(snapshot(ready.root, item.artifactPath)).toEqual(before); expect(demo.loadState(ready.root).demos[0].scenarios[0].status).toBe("planned"); state = demo.block(ready.root, { demoId: item.id, reason: "The operated target identity did not match the authorized exact candidate.", nextParticipant: "Demo participant", nextAction: "Correct and verify the Demo target before retrying" }); expect(state.demos[0].phase).toBe("blocked"); expect(state.nextActions[0].action).toContain("verify the Demo target"); expect(state.nextActions[0].action).not.toContain("Build"); });

  it("normalizes contained evidence for the nested Demo and marks ephemeral references inaccessible", async () => { const ready = await readyBuild(); let state = await demo.initialize(ready.root, demoActivation(ready)), item = state.demos[0]; state = demo.observe(ready.root, observation(item.id, ready.defined.content.acceptance)); const recorded = state.demos[0].evidence.find((entry) => entry.id === "demo-observation")!; expect(recorded).toMatchObject({ referenceKind: "workspace-file", accessibility: "inspectable", reference: "../../../../demo-evidence/observation.txt" }); expect(existsSync(resolve(join(ready.root, item.artifactPath, ".."), recorded.reference))).toBe(true); expect(readFileSync(join(ready.root, item.artifactPath), "utf8")).toContain("[Open evidence](<../../../../demo-evidence/observation.txt>)"); const other = await readyBuild(); let otherState = await demo.initialize(other.root, demoActivation(other)), otherItem = otherState.demos[0], inaccessible = observation(otherItem.id, other.defined.content.acceptance); inaccessible.evidence[1].reference = "browser-session://observation"; inaccessible.evidence[1].referenceKind = "ephemeral"; inaccessible.coverage.forEach((row) => { row.status = "inaccessible"; }); inaccessible.readiness = { status: "blocked", basis: "The observation is unavailable outside the originating session." }; otherState = demo.observe(other.root, inaccessible); expect(otherState.demos[0].evidence[1].accessibility).toBe("inaccessible"); expect(readFileSync(join(other.root, otherItem.artifactPath), "utf8")).toContain("Unavailable outside the originating session"); });

  it("rejects missing or fingerprint-mismatched workspace evidence without mutation", async () => { for (const defect of ["missing", "fingerprint"] as const) { const ready = await readyBuild(), state = await demo.initialize(ready.root, demoActivation(ready)), item = state.demos[0], before = snapshot(ready.root, item.artifactPath), update = observation(item.id, ready.defined.content.acceptance); if (defect === "missing") update.evidence[0].reference = "demo-evidence/missing.txt"; else update.evidence[0].fingerprint = "1".repeat(64); expect(() => demo.observe(ready.root, update)).toThrow(defect === "missing" ? "does not exist" : "fingerprint does not match"); expect(snapshot(ready.root, item.artifactPath)).toEqual(before); } });

  it("persists ordinary observations privately and publishes current review readiness", async () => { const ready = await readyBuild(); let state = await demo.initialize(ready.root, demoActivation(ready)), item = state.demos[0], published = readFileSync(join(ready.root, item.artifactPath), "utf8"); state = demo.observe(ready.root, observation(item.id, ready.defined.content.acceptance, { status: "active", basis: "The live observation is still in progress." })); expect(readFileSync(join(ready.root, item.artifactPath), "utf8")).toBe(published); expect(await demo.detectStaleViews(ready.root)).toContain(item.artifactPath); demo.renderCurrent(ready.root); state = demo.observe(ready.root, observation(item.id, ready.defined.content.acceptance)); item = state.demos[0]; expect(item.phase).toBe("ready-for-judgment"); const current = readFileSync(join(ready.root, item.artifactPath), "utf8"); expect(current).toContain("The supported recovery and readable rejection paths"); expect(current).toContain("[Open evidence](<../../../../demo-evidence/observation.txt>)"); expect(current).toContain("ready for judgment"); });

  it("reuses exact authority but requires explicit reauthorization for consequential changes", async () => { const ready = await readyBuild(); let state = await demo.initialize(ready.root, demoActivation(ready)), item = state.demos[0], before = snapshot(ready.root, item.artifactPath); expect(() => demo.authorize(ready.root, { demoId: item.id, explicitAuthorization: true, authority: item.authority, reason: "No change" })).toThrow("already reusable"); expect(snapshot(ready.root, item.artifactPath)).toEqual(before); expect(() => demo.observe(ready.root, { ...observation(item.id, ready.defined.content.acceptance), environmentFingerprint: "7".repeat(64) })).toThrow("drift invalidates"); expect(snapshot(ready.root, item.artifactPath)).toEqual(before); const changed = structuredClone(item.authority); changed.environment = { name: "Second controlled environment", fingerprint: "8".repeat(64) }; expect(() => demo.authorize(ready.root, { demoId: item.id, explicitAuthorization: false as true, authority: changed, reason: "Use the alternate environment" })).toThrow("explicit authorization"); state = demo.authorize(ready.root, { demoId: item.id, explicitAuthorization: true, authority: changed, reason: "The human explicitly authorized the alternate controlled environment." }); expect(state.demos[0].authority.environment.name).toBe("Second controlled environment"); });

  it("rejects failed evidence, product mutation, forbidden authority, and unpermitted effects without mutation", async () => { const unsafe = await readyBuild(), bad = demoActivation(unsafe); bad.authority.actions = ["Deploy the demonstrated result"]; await expect(demo.initialize(unsafe.root, bad)).rejects.toThrow("outside Demo authority"); expect(existsSync(join(unsafe.root, MILESTONE_DEMO_STATE_PATH))).toBe(false); const ready = await readyBuild(); let state = await demo.initialize(ready.root, demoActivation(ready)), item = state.demos[0], before = snapshot(ready.root, item.artifactPath); const failed = observation(item.id, ready.defined.content.acceptance); failed.evidence[1].result = "failed"; expect(() => demo.observe(ready.root, failed)).toThrow("passing independently inspectable evidence"); expect(snapshot(ready.root, item.artifactPath)).toEqual(before); expect(() => demo.observe(ready.root, { ...observation(item.id, ready.defined.content.acceptance), productMutation: "changed" as "none" })).toThrow("cannot mutate"); expect(snapshot(ready.root, item.artifactPath)).toEqual(before); const authority = structuredClone(item.authority); authority.externalEffects = ["Create a customer-visible record"]; expect(() => demo.authorize(ready.root, { demoId: item.id, explicitAuthorization: true, authority, reason: "Try an effect" })).toThrow("explicit consequential permission"); expect(snapshot(ready.root, item.artifactPath)).toEqual(before); });

  it("records unavailable or unsafe Demo conditions as a visible blocker with one next action", async () => { const ready = await readyBuild(); let state = await demo.initialize(ready.root, demoActivation(ready)), item = state.demos[0]; state = demo.block(ready.root, { demoId: item.id, reason: "The required controlled observer is unavailable without broader access.", nextParticipant: "Human", nextAction: "Choose a safe equivalent method or authorize the missing observer" }); expect(state.demos[0].phase).toBe("blocked"); expect(state.nextActions).toHaveLength(1); expect(readFileSync(join(ready.root, item.artifactPath), "utf8")).toContain("required controlled observer is unavailable"); expect(readFileSync(join(ready.root, "LOOPY.md"), "utf8")).toContain("Choose a safe equivalent method"); });

  it("keeps explicitly authorized partial external effects and unproven behavior visible", async () => { const ready = await readyBuild(), input = demoActivation(ready); input.authority.externalSystems = ["controlled sandbox service"]; input.authority.externalEffects = ["Create one disposable sandbox record"]; input.authority.consequentialPermissions = ["Avery authorized one disposable sandbox record for this Demo"]; let state = await demo.initialize(ready.root, input), item = state.demos[0], update = observation(item.id, ready.defined.content.acceptance); update.scenario.status = "failed"; update.scenario.result = "The sandbox returned a partial result."; update.scenario.partialEffects = ["One disposable sandbox record may remain."]; update.evidence[1].result = "partial"; update.evidence[1].externalSystem = "controlled sandbox service"; update.coverage = ready.defined.content.acceptance.map((criterion) => ({ criterion, status: "unproven", scenarioKeys: ["recovery"], evidenceIds: ["demo-observation"], note: "The partial result does not establish the criterion." })); update.limitations = ["The external response was incomplete."]; update.unproven = ["The committed recovery boundary remains unproven."]; update.readiness = { status: "blocked", basis: "A partial external effect requires review before another action." }; state = demo.observe(ready.root, update); expect(state.demos[0].phase).toBe("blocked"); const view = readFileSync(join(ready.root, item.artifactPath), "utf8"); expect(view).toContain("One disposable sandbox record may remain"); expect(view).toContain("committed recovery boundary remains unproven"); expect(view).not.toContain("| demonstrated |"); });

  it("separates simulated and proxy input from genuine human judgment and acceptance", async () => { const ready = await readyBuild(); let state = await demo.initialize(ready.root, demoActivation(ready)), item = state.demos[0]; state = demo.observe(ready.root, observation(item.id, ready.defined.content.acceptance)); item = state.demos[0]; let before = snapshot(ready.root, item.artifactPath), proxy = decision(ready, item.id, item.revision); proxy.actorKind = "proxy-ai"; expect(() => demo.decide(ready.root, proxy)).toThrow("cannot claim personal human judgment"); expect(snapshot(ready.root, item.artifactPath)).toEqual(before); proxy.personalJudgment = false; state = demo.decide(ready.root, proxy); item = state.demos[0]; expect(item.phase).toBe("ready-for-judgment"); expect(item.decision).toBeNull(); expect(item.advisoryInputs[0]).toMatchObject({ actorKind: "proxy-ai", personalJudgment: false }); let view = readFileSync(join(ready.root, item.artifactPath), "utf8"); expect(view).toContain("Advisory input (not human judgment)"); expect(view).toContain("Proxy AI"); expect(view).toContain("No human decision recorded"); const simulated = decision(ready, item.id, item.revision, "defer"); simulated.actorKind = "simulated-participant"; simulated.personalJudgment = false; state = demo.decide(ready.root, simulated); expect(state.demos[0].phase).toBe("ready-for-judgment"); expect(state.demos[0].advisoryInputs).toHaveLength(2); item = state.demos[0]; const wrong = decision(ready, item.id, item.revision); wrong.acceptedBoundary = [ready.defined.content.acceptance[0]]; before = snapshot(ready.root, item.artifactPath); expect(() => demo.decide(ready.root, wrong)).toThrow("exact committed outcome"); expect(snapshot(ready.root, item.artifactPath)).toEqual(before); state = demo.decide(ready.root, decision(ready, item.id, item.revision)); expect(state.demos[0].phase).toBe("accepted"); expect(state.demos[0].decision).toMatchObject({ human: "Avery", personalJudgment: true, candidateId: ready.candidate.id }); const human = readFileSync(join(ready.root, item.artifactPath), "utf8"), home = readFileSync(join(ready.root, "LOOPY.md"), "utf8"), road = readFileSync(join(ready.root, "docs/loopy/Roadmap.md"), "utf8"); expect(human).toContain("Complete but unreleased"); expect(human).toContain("Customer operations judgment"); expect(home).toContain(`**Complete but not released:** [${ready.build.title}]`); expect(road).toContain(`| ${ready.build.title} | Complete |`); expect(home.match(/^## Next action$/gm)).toHaveLength(1); expect(road.match(/^## Next action$/gm)).toHaveLength(1); expect(human).not.toContain("Released Milestone"); before = snapshot(ready.root, item.artifactPath); expect(() => demo.decide(ready.root, decision(ready, item.id, state.demos[0].revision, "request-correction", "build"))).toThrow("final human disposition"); expect(snapshot(ready.root, item.artifactPath)).toEqual(before); });

  it("preserves decisions and routes correction or deferral deterministically", async () => { for (const route of ["build", "planning", "change-management"] as const) { const ready = await readyBuild(); let state = await demo.initialize(ready.root, demoActivation(ready)), item = state.demos[0]; state = demo.observe(ready.root, observation(item.id, ready.defined.content.acceptance)); item = state.demos[0]; state = demo.decide(ready.root, decision(ready, item.id, item.revision, "request-correction", route)); expect(state.demos[0].phase).toBe("correction-requested"); expect(state.nextActions[0].action.toLowerCase()).toContain(route === "build" ? "build and prove" : route === "planning" ? "milestone planning" : "change management"); expect(state.demos[0].history.map((entry) => entry.operation)).toContain("correction"); } const ready = await readyBuild(); let state = await demo.initialize(ready.root, demoActivation(ready)), item = state.demos[0]; state = demo.decide(ready.root, decision(ready, item.id, item.revision, "defer")); expect(state.demos[0].phase).toBe("deferred"); expect(state.nextActions[0].action).toContain("customer operations review"); });

  it("preserves interruption, stale-view safety, and explicit non-replayable restart", async () => { const ready = await readyBuild(); let state = await demo.initialize(ready.root, demoActivation(ready)), item = state.demos[0]; state = demo.observe(ready.root, observation(item.id, ready.defined.content.acceptance, { status: "active", basis: "The live scenario is underway." })); item = state.demos[0]; state = demo.interrupt(ready.root, item.id, "Continue the direct observation"); writeFileSync(join(ready.root, item.artifactPath), "stale\n"); await expect(demo.resume(ready.root, { sourceFingerprint: C, workspaceFingerprint: W, environmentFingerprint: ENV, restartScenarioKeys: ["recovery"] })).rejects.toThrow("views are stale"); demo.renderCurrent(ready.root); const before = snapshot(ready.root, item.artifactPath); await expect(demo.resume(ready.root, { sourceFingerprint: C, workspaceFingerprint: W, environmentFingerprint: ENV, restartScenarioKeys: [] })).rejects.toThrow("non-replayable"); expect(snapshot(ready.root, item.artifactPath)).toEqual(before); state = await demo.resume(ready.root, { sourceFingerprint: C, workspaceFingerprint: W, environmentFingerprint: ENV, restartScenarioKeys: ["recovery"] }); expect(state.session.status).toBe("active"); expect(state.demos[0].scenarios[0]).toMatchObject({ status: "planned", result: expect.stringContaining("Restart required") }); });

  it("invalidates changed foundations without mutating Demo state or its artifact", async () => { const ready = await readyBuild(); const state = await demo.initialize(ready.root, demoActivation(ready)), item = state.demos[0], demoState = readFileSync(join(ready.root, MILESTONE_DEMO_STATE_PATH), "utf8"), demoView = readFileSync(join(ready.root, item.artifactPath), "utf8"); roadmap.applyOperation(ready.root, { type: "add", candidate: { title: "Later outcome", outcome: "A later outcome remains visible.", priority: "Later", rationale: "Keep future work visible.", nextShapingStep: "Clarify later." }, actor: { name: "Priya", responsibility: "product" } }); expect(() => demo.status(ready.root)).toThrow(/foundation revisions changed|foundations changed|invalid/); expect(readFileSync(join(ready.root, MILESTONE_DEMO_STATE_PATH), "utf8")).toBe(demoState); expect(readFileSync(join(ready.root, item.artifactPath), "utf8")).toBe(demoView); });

  it("rolls back state and synchronized views when atomic publication fails", async () => { const ready = await readyBuild(), prior = Object.fromEntries(["LOOPY.md", "docs/loopy/Roadmap.md", ready.build.artifactPath].map((path) => [path, readFileSync(join(ready.root, path), "utf8")])); const failing = await MilestoneDemoEngine.create(sourceRoot, { beforeCommit: (path) => { if (path === "docs/loopy/Roadmap.md") throw new Error("simulated publication failure"); } }); await expect(failing.initialize(ready.root, demoActivation(ready))).rejects.toThrow("simulated publication failure"); expect(existsSync(join(ready.root, MILESTONE_DEMO_STATE_PATH))).toBe(false); for (const [path, content] of Object.entries(prior)) expect(readFileSync(join(ready.root, path), "utf8")).toBe(content); });

  it("registers the bounded internal CLI routes", () => { for (const command of ["demo-init", "demo-observe", "demo-decide", "demo-render", "demo-status"]) expect(parseCliArguments([command, "--workspace", "/tmp/project", ...(command === "demo-init" || command === "demo-observe" || command === "demo-decide" ? ["--input", "/tmp/input.json"] : [])]).command).toBe(command); });

  it("registers one self-sufficient internal skill route without overstating proof", () => { const skill = readFileSync(join(sourceRoot, "skills/loopy/SKILL.md"), "utf8"), interview = readFileSync(join(sourceRoot, "skills/loopy/references/interviews/Milestone-Demonstrate-and-Accept.md"), "utf8"), apply = readFileSync(join(sourceRoot, "skills/loopy/references/engine/Milestone-Demonstrate-and-Accept-Apply.md"), "utf8"), payloads = readFileSync(join(sourceRoot, "skills/loopy/references/engine/Milestone-Demonstrate-and-Accept-Payloads.md"), "utf8"), registry = parse(readFileSync(join(sourceRoot, "capabilities/registry.yaml"), "utf8")) as { capabilities: Array<{ id: string; status: string; human_artifacts: string[] }> }; expect(skill).toContain("references/interviews/Milestone-Demonstrate-and-Accept.md"); expect(interview).toContain("simulated participant input"); expect(interview).toContain("Demo environment/target failure"); expect(apply).toContain("runtime/dist/engine/src/cli.js"); expect(apply).toContain("Milestone-Demonstrate-and-Accept-Payloads.md"); for (const field of ["targetVerification", "referenceKind", "actorKind", "personalJudgment", "correctionRoute", "restartScenarioKeys"]) expect(payloads).toContain(`\"${field}\"`); for (const operation of ["demo-init", "demo-activate", "demo-authorize", "demo-observe", "demo-decide", "demo-block", "demo-interrupt", "demo-resume", "demo-render", "demo-status", "demo-stale"]) expect(`${apply}\n${payloads}`).toContain(operation); expect(payloads).not.toContain("TypeScript"); expect(registry.capabilities.find((item) => item.id === "milestone-demonstrate-and-accept")).toEqual(expect.objectContaining({ status: "implemented-unverified", human_artifacts: expect.arrayContaining(["docs/loopy/milestones/*/Demo.md"]) })); expect(demo.contract).toMatchObject({ verified_demo_target_required: true, durable_evidence_references_required: true, proxy_ai_cannot_accept: true, simulated_input_is_not_human_judgment: true, release_authority_out_of_scope: true }); });
});
