import { cpSync, existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { ProductStartEngine } from "../src/engine.js";
import { EngineeringFoundationEngine } from "../src/engineering-engine.js";
import { LivingRoadmapEngine } from "../src/living-roadmap-engine.js";
import { MilestoneDefinitionEngine } from "../src/milestone-definition-engine.js";
import { MilestonePlanningEngine } from "../src/milestone-planning-engine.js";
import { MILESTONE_BUILD_STATE_PATH, MilestoneBuildEngine } from "../src/milestone-build-engine.js";
import type { EngineeringFoundationUpdate } from "../src/engineering-types.js";
import type { DefinitionUpdate } from "../src/milestone-definition-types.js";
import type { MilestonePlan, PlanningUpdate } from "../src/milestone-planning-types.js";
import type { BuildActivation, BuildWorkUpdate, EvaluationInput, ModelChoice, TaskAssignmentInput } from "../src/milestone-build-types.js";
import type { ProductStartUpdate } from "../src/types.js";
import { parseCliArguments } from "../src/cli-arguments.js";

const sourceRoot=resolve(import.meta.dirname,"../.."),fixture=join(sourceRoot,"evaluation/scenarios/product-start/large-mixed-project/fixture"),productSetup=join(sourceRoot,"evaluation/scenarios/product-start/large-mixed-project/setup/v1/product-update.json"),roots:string[]=[];let product:ProductStartEngine,engineering:EngineeringFoundationEngine,roadmap:LivingRoadmapEngine,definition:MilestoneDefinitionEngine,planning:MilestonePlanningEngine,build:MilestoneBuildEngine;
const A="a".repeat(64),B="b".repeat(64),C="c".repeat(64),D="d".repeat(64),W="e".repeat(64);
beforeAll(async()=>{product=await ProductStartEngine.create(sourceRoot);engineering=await EngineeringFoundationEngine.create(sourceRoot);roadmap=await LivingRoadmapEngine.create(sourceRoot);definition=await MilestoneDefinitionEngine.create(sourceRoot);planning=await MilestonePlanningEngine.create(sourceRoot);build=await MilestoneBuildEngine.create(sourceRoot)});afterAll(()=>roots.forEach(root=>rmSync(root,{recursive:true,force:true})));
function engineeringUpdates():EngineeringFoundationUpdate[]{const ref=readFileSync(join(sourceRoot,"skills/loopy/references/engine/Engineering-Foundation-Apply.md"),"utf8");return[...ref.matchAll(/<!-- engineering-apply-example -->\n```json\n([\s\S]*?)\n```/g)].map(m=>JSON.parse(m[1]))}
function planUpdate(planId:string,focused=false,parallel=false):PlanningUpdate{const workUnits=[{key:"foundation",title:"Establish the outcome path",contribution:"Makes the outcome observable.",affectedAreas:["delivery path"],responsibility:"Engineering",completionObservation:"The supported result is observable.",checks:["Outcome path check"],workspace:"same-directory" as const,order:1},{key:"boundary",title:"Verify the acceptance boundary",contribution:"Preserves supported and rejected behavior.",affectedAreas:["checks and evidence"],responsibility:"Engineering",completionObservation:"Accepted and rejected paths are evidenced.",checks:["Acceptance boundary check"],workspace:"same-directory" as const,order:2}];const final={checkpoint:"Integrated Milestone evaluation",evaluationType:"final-integrated-independent" as const,workUnits:["foundation","boundary"],trigger:"After every Work Unit composes into one frozen candidate",reason:"The full committed boundary requires independent integrated evaluation.",correctionCycleLimit:1,required:true};return{planId,actor:{name:"Emi",responsibility:"engineering"},content:{approach:["Deliver the bounded outcome, then evaluate the integrated candidate."],workUnits,dependencies:parallel?[]:[{from:"foundation",to:"boundary",kind:"required-before",note:"The outcome path precedes boundary verification."}],parallelism:[],parallelClaims:parallel?[{workUnits:["foundation","boundary"],disposition:"safe",conflicts:[],basis:"The controlled fixture declares disjoint affected areas."}]:[{workUnits:["foundation","boundary"],disposition:"blocked",conflicts:["required-before dependency"],basis:"Boundary verification follows implementation."}],checksAndEvidence:["Preserve exact command output"],evaluationBoundaries:[...(focused?[{checkpoint:"Shared-interface checkpoint",evaluationType:"focused-independent" as const,workUnits:["foundation"],trigger:"After the shared path changes",reason:"A focused integration risk merits independent evaluation.",correctionCycleLimit:0,required:true}]:[]),final],risks:["Integration behavior"],unknowns:[],releaseImpact:[]},participants:[{name:"Emi",responsibility:"Engineering"}],workspaceDisposition:{mode:"same-directory",location:"",basis:"The controlled units share one project."},guideTriggers:[],coherence:{status:"coherent",basis:"The bounded approach and evaluation budget remain inside the Definition."}}}
async function setup(options:{focused?:boolean;parallel?:boolean}={}){const root=mkdtempSync(join(tmpdir(),"loopy-build-"));roots.push(root);cpSync(fixture,root,{recursive:true});await product.initialize(root,"Harbor",{participantResponsibilities:["product"]});product.applyUpdate(root,JSON.parse(readFileSync(productSetup,"utf8"))as ProductStartUpdate);await product.recordProductReview(root);await product.confirmProduct(root);engineering.initialize(root,{participantResponsibilities:["engineering"]});for(const update of engineeringUpdates())engineering.applyUpdate(root,update);engineering.recordReview(root);engineering.confirm(root);roadmap.initialize(root);roadmap.applyOperation(root,{type:"set-dependencies",candidateId:"candidate-1",dependencies:[],actor:{name:"Emi",responsibility:"engineering"}});roadmap.applyOperation(root,{type:"select",candidateIds:["candidate-1"],actor:{name:"Priya",responsibility:"product"}});let definitions=definition.initialize(root),item=definitions.definitions[0];definition.applyUpdate(root,{type:"update",definitionId:item.id,actor:{name:"Loopy",perspectives:["product","engineering"]},content:{outcome:item.content.outcome,requirements:["Deliver the committed customer recovery outcome."],inScope:["The supported recovery path"],nonGoals:["Unrelated Product changes"],acceptance:["A supported recovery reaches the intended customer-visible result.","An unsupported recovery is rejected with a readable reason."],dependencies:item.content.dependencies,feasibilityAndConstraints:["Preserve confirmed guidance"],risks:["Integration behavior"],assumptions:["Foundations remain current"],unknowns:[]},coherence:{status:"coherent",basis:"Outcome, scope, feasibility, and observable acceptance agree."},requiredPerspectives:["product","engineering"]}as DefinitionUpdate);definitions=definition.loadState(root);definition.review(root,[item.id]);definition.confirm(root,[{definitionId:item.id,participant:"Emi",perspectives:["engineering"],commit:false}]);definition.confirm(root,[{definitionId:item.id,participant:"Priya",perspectives:["product"],commit:true}]);let ps=planning.initialize(root,[item.id]);ps=planning.applyUpdate(root,planUpdate(ps.plans[0].id,options.focused,options.parallel));ps=planning.review(root,{planIds:[ps.plans[0].id]});return{root,plan:ps.plans[0],definition:definition.loadState(root).definitions[0]}}
function models(untested=false):ModelChoice[]{return(["orchestrator","builder","focused-evaluator","final-evaluator"]as const).map(role=>({role,host:"available-local-host",model:`role-model-${role}`,settingsProfile:"balanced",available:true as const,recommended:true,qualification:untested?"untested" as const:"tested" as const,unverifiedNotice:untested?"Unverified for Loopy release compatibility.":null}))}
function activation(root:string,plan:MilestonePlan,workUnits:string[],source=A,untested=false):BuildActivation{return{planId:plan.id,participant:"Morgan",responsibilities:["engineering","build orchestration"],workUnits,workspace:{mode:"same-directory",location:root,fingerprint:W},allowedTools:["editor","test-runner"],sourceControlOperations:["edit","check"],externalSystems:[],modelChoices:models(untested),costChoice:"Prefer quality within the confirmed local budget.",sourceFingerprint:source,evaluationBudget:plan.content.evaluationBoundaries}}
function assignment(buildId:string,role:TaskAssignmentInput["role"],participant:string,workUnits:string[],checkpoint:string|null,source=role==="final-evaluator"?C:role==="focused-evaluator"?B:A):TaskAssignmentInput{const evaluator=role.endsWith("evaluator");return{buildId,role,participant,responsibility:evaluator?"independent evaluation":"engineering",workUnits,checkpoint,host:"available-local-host",model:`role-model-${role}`,settingsProfile:"balanced",sourceFingerprint:source,workspaceFingerprint:W,taskContextIdentity:`${role}-${participant}-${checkpoint??workUnits.join("-")}`,evaluationWorkspace:evaluator?{location:`/tmp/loopy-${role}-${participant}`,fingerprint:(role==="final-evaluator"?"f":"1").repeat(64),clean:true,disposable:true}:null,recommendationBasis:"The current Plan risk and bounded context fit this available model."}}
function workInput(root:string,buildId:string,key:string,participant:string,before:string,after:string,status:BuildWorkUpdate["status"]="completed"):BuildWorkUpdate{return{buildId,workUnitKey:key,participant,responsibility:"engineering",status,tool:"editor",sourceControlOperation:"edit",externalSystem:null,workspaceLocation:root,workspaceFingerprint:W,sourceFingerprintBefore:before,sourceFingerprintAfter:after,summary:`Completed ${key} inside the Plan boundary.`,evidence:[{key:`work-${key}-${after[0]}`,kind:"command",summary:`${key} focused check`,reference:`inert://${key}/${after[0]}`,result:"passed"}],effect:{status:"completed",detail:"The controlled local edit completed."},boundaryDisposition:"within-plan",coordination:{checked:true,conflicts:[]}}}
function snapshot(root:string,proofPath:string){return Object.fromEntries([MILESTONE_BUILD_STATE_PATH,"LOOPY.md","docs/loopy/Roadmap.md",proofPath].map(path=>[path,readFileSync(join(root,path),"utf8")]))}
function charter(plan:MilestonePlan,definitionRevision:number,candidateId:string,fingerprint:string,workUnits:string[],acceptance:string[]){return{definitionRevision,planRevision:plan.revision,candidateId,candidateFingerprint:fingerprint,workUnits,acceptanceCriteria:acceptance,plannedChecks:[...new Set([...plan.content.checksAndEvidence,...plan.content.workUnits.flatMap(u=>u.checks)])],allowedTools:["test-runner"],neutralPosture:"unproven" as const}}
function evaluation(buildId:string,plan:MilestonePlan,definitionRevision:number,candidateId:string,fingerprint:string,acceptance:string[],verdict:EvaluationInput["verdict"]="pass"):EvaluationInput{const checks=[...new Set([...plan.content.checksAndEvidence,...plan.content.workUnits.flatMap(u=>u.checks)])],evidence=[{key:`evaluation-${candidateId}`,kind:"observation" as const,summary:"Independent integrated observations",reference:`inert://${candidateId}/evaluation`,result:verdict==="pass"?"passed" as const:"failed" as const}];return{buildId,candidateId,checkpoint:"Integrated Milestone evaluation",assignmentId:"assignment-3",evaluator:"Quinn",responsibility:"independent evaluation",charter:charter(plan,definitionRevision,candidateId,fingerprint,["foundation","boundary"],acceptance),verdict,evidence,acceptanceCoverage:acceptance.map(item=>({item,evidenceIds:[evidence[0].key],status:verdict==="pass"?"supported" as const:"failed" as const})),checkCoverage:checks.map(item=>({item,evidenceIds:[evidence[0].key],status:verdict==="pass"?"supported" as const:"failed" as const})),findings:verdict==="pass"?[]:["The integrated behavior did not meet the boundary."],limitations:[],skips:[],unproven:[]}}
async function completeWork(root:string,plan:MilestonePlan,untested=false){let state=build.initialize(root,activation(root,plan,["foundation"],A,untested)),id=state.builds[0].id;state=build.assignTask(root,assignment(id,"builder","Blair",["foundation"],null,A));state=build.recordWork(root,workInput(root,id,"foundation","Blair",A,B));state=build.activate(root,activation(root,plan,["boundary"],B,untested));state=build.assignTask(root,assignment(id,"builder","Blair",["boundary"],null,B));state=build.recordWork(root,workInput(root,id,"boundary","Blair",B,C));return state}

describe("Milestone Build and Prove",()=>{
  it("requires a ready Plan and an exact bounded grant before creating Build state",async()=>{const{root,plan}=await setup();const bad=activation(root,plan,["boundary"]);expect(()=>build.initialize(root,bad)).toThrow("not ready");expect(existsSync(join(root,MILESTONE_BUILD_STATE_PATH))).toBe(false);const forbidden={...activation(root,plan,["foundation"]),sourceControlOperations:["edit","check","push"] as any};expect(()=>build.initialize(root,forbidden)).toThrow("outside Build authority");expect(existsSync(join(root,MILESTONE_BUILD_STATE_PATH))).toBe(false)});
  it("rejects unassigned, ungranted, stale-source, wrong-tool, and premature dependent work without mutation",async()=>{const{root,plan}=await setup();const state=build.initialize(root,activation(root,plan,["foundation"])),id=state.builds[0].id,proof=state.builds[0].artifactPath,before=snapshot(root,proof);expect(()=>build.recordWork(root,workInput(root,id,"foundation","Blair",A,B))).toThrow("builder assignment");expect(snapshot(root,proof)).toEqual(before);expect(()=>build.assignTask(root,assignment(id,"builder","Blair",["foundation"],null,D))).toThrow("exact current granted source");expect(snapshot(root,proof)).toEqual(before);build.assignTask(root,assignment(id,"builder","Blair",["foundation"],null));const afterAssign=snapshot(root,proof);expect(()=>build.recordWork(root,{...workInput(root,id,"foundation","Blair",A,B),tool:"unknown"})).toThrow("outside the active grant");expect(snapshot(root,proof)).toEqual(afterAssign);expect(()=>build.recordWork(root,workInput(root,id,"foundation","Blair",D,B))).toThrow("Source snapshot changed");expect(snapshot(root,proof)).toEqual(afterAssign);expect(()=>build.recordWork(root,workInput(root,id,"boundary","Blair",A,B))).toThrow();expect(snapshot(root,proof)).toEqual(afterAssign)});
  it("persists ordinary Build state privately and publishes readable synchronized status on demand",async()=>{const{root,plan}=await setup();let state=build.initialize(root,activation(root,plan,["foundation"],A,true)),id=state.builds[0].id,proof=state.builds[0].artifactPath,published=readFileSync(join(root,proof),"utf8");state=build.assignTask(root,assignment(id,"builder","Blair",["foundation"],null));state=build.recordWork(root,workInput(root,id,"foundation","Blair",A,B));expect(readFileSync(join(root,proof),"utf8")).toBe(published);expect(await build.detectStaleViews(root)).toContain(proof);build.renderCurrent(root);const view=readFileSync(join(root,proof),"utf8");expect(view).toContain("Establish the outcome path | completed");expect(view).toContain("Unverified for Loopy release compatibility");expect(view).toContain("Evidence is the attributed record");expect(readFileSync(join(root,"LOOPY.md"),"utf8").match(/^## Next action$/gm)).toHaveLength(1);expect(readFileSync(join(root,"docs/loopy/Roadmap.md"),"utf8")).toContain("Milestone Build and Prove active")});
  it("enforces sequential default and allows concurrency only for an explicit safe claim",async()=>{const blocked=await setup();let state=build.initialize(blocked.root,activation(blocked.root,blocked.plan,["foundation"])),id=state.builds[0].id;build.assignTask(blocked.root,assignment(id,"builder","Blair",["foundation"],null));build.recordWork(blocked.root,workInput(blocked.root,id,"foundation","Blair",A,B,"in-progress"));expect(()=>build.activate(blocked.root,activation(blocked.root,blocked.plan,["boundary"],B))).toThrow("not ready");const safe=await setup({parallel:true});state=build.initialize(safe.root,activation(safe.root,safe.plan,["foundation","boundary"]));id=state.builds[0].id;build.assignTask(safe.root,assignment(id,"builder","Blair",["foundation"],null));build.assignTask(safe.root,assignment(id,"builder","Casey",["boundary"],null));build.recordWork(safe.root,workInput(safe.root,id,"foundation","Blair",A,B,"in-progress"));state=build.recordWork(safe.root,workInput(safe.root,id,"boundary","Casey",B,C,"in-progress"));expect(state.builds[0].workUnits.filter(u=>u.status==="in-progress")).toHaveLength(2)});
  it("requires independent exact-charter final evaluation and complete declared coverage before Demonstration readiness",async()=>{const{root,plan,definition:defined}=await setup();let state=await completeWork(root,plan,true),b=state.builds[0];state=build.assignTask(root,assignment(b.id,"final-evaluator","Quinn",["foundation","boundary"],"Integrated Milestone evaluation"));state=build.freezeCandidate(root,{buildId:b.id,kind:"integrated",checkpoint:"Integrated Milestone evaluation",workUnits:["foundation","boundary"],sourceFingerprint:C,workspaceFingerprint:W,parentCandidateId:null});b=state.builds[0];const bad=evaluation(b.id,plan,defined.revision,b.candidates[0].id,C,defined.content.acceptance);bad.acceptanceCoverage=[];const before=snapshot(root,b.artifactPath);expect(()=>build.recordEvaluation(root,bad)).toThrow("complete supported declared coverage");expect(snapshot(root,b.artifactPath)).toEqual(before);state=build.recordEvaluation(root,evaluation(b.id,plan,defined.revision,b.candidates[0].id,C,defined.content.acceptance));expect(state.builds[0].phase).toBe("ready-for-demonstration");expect(state.nextActions[0].action).toContain("Begin Demonstration");const proof=readFileSync(join(root,b.artifactPath),"utf8");expect(proof).toContain("ready for demonstration");expect(proof).toContain(`source snapshot \`${C}\``);expect(proof).toContain("available-local-host / role-model-final-evaluator / balanced");expect(proof).toContain("A supported recovery reaches");expect(proof).toContain("Ready for Demonstration is not Confirmation")});
  it("forbids a builder from independently evaluating their own frozen candidate",async()=>{const{root,plan,definition:defined}=await setup();let state=await completeWork(root,plan),b=state.builds[0];state=build.assignTask(root,assignment(b.id,"final-evaluator","Blair",["foundation","boundary"],"Integrated Milestone evaluation"));state=build.freezeCandidate(root,{buildId:b.id,kind:"integrated",checkpoint:"Integrated Milestone evaluation",workUnits:["foundation","boundary"],sourceFingerprint:C,workspaceFingerprint:W,parentCandidateId:null});b=state.builds[0];const input=evaluation(b.id,plan,defined.revision,b.candidates[0].id,C,defined.content.acceptance);input.assignmentId="assignment-3";input.evaluator="Blair";const before=snapshot(root,b.artifactPath);expect(()=>build.recordEvaluation(root,input)).toThrow("cannot evaluate a candidate they built");expect(snapshot(root,b.artifactPath)).toEqual(before)});
  it("counts focused correction cycles, pauses at zero, and requires explicit judgment to increase",async()=>{const{root,plan,definition:defined}=await setup({focused:true});let state=build.initialize(root,activation(root,plan,["foundation"])),b=state.builds[0];state=build.assignTask(root,assignment(b.id,"builder","Blair",["foundation"],null));state=build.recordWork(root,workInput(root,b.id,"foundation","Blair",A,B));state=build.assignTask(root,assignment(b.id,"focused-evaluator","Quinn",["foundation"],"Shared-interface checkpoint"));state=build.freezeCandidate(root,{buildId:b.id,kind:"focused",checkpoint:"Shared-interface checkpoint",workUnits:["foundation"],sourceFingerprint:B,workspaceFingerprint:W,parentCandidateId:null});b=state.builds[0];const failed=evaluation(b.id,plan,defined.revision,b.candidates[0].id,B,defined.content.acceptance,"fail");failed.checkpoint="Shared-interface checkpoint";failed.assignmentId="assignment-2";failed.charter.workUnits=["foundation"];state=build.recordEvaluation(root,failed);expect(state.builds[0].phase).toBe("paused");expect(state.builds[0].evaluationBudget[0]).toMatchObject({attempts:1,correctionCycles:0,status:"failed"});const raised=plan.content.evaluationBoundaries.map(x=>({...x,correctionCycleLimit:x.checkpoint==="Shared-interface checkpoint"?1:x.correctionCycleLimit})),before=snapshot(root,b.artifactPath);expect(()=>build.adjustBudget(root,{buildId:b.id,participant:"Riley",boundaries:raised,explicitIncreaseJudgment:false,reason:"Try one bounded correction."})).toThrow("explicit Human judgment");expect(snapshot(root,b.artifactPath)).toEqual(before);state=build.adjustBudget(root,{buildId:b.id,participant:"Riley",boundaries:raised,explicitIncreaseJudgment:true,reason:"Authorize one corrected candidate and reevaluation."});expect(state.builds[0].phase).toBe("active")});
  it("preserves failed evidence and requires explicit correction lineage",async()=>{const{root,plan,definition:defined}=await setup({focused:true});let state=build.initialize(root,activation(root,plan,["foundation"])),b=state.builds[0];build.assignTask(root,assignment(b.id,"builder","Blair",["foundation"],null));build.recordWork(root,workInput(root,b.id,"foundation","Blair",A,B));build.assignTask(root,assignment(b.id,"focused-evaluator","Quinn",["foundation"],"Shared-interface checkpoint"));state=build.freezeCandidate(root,{buildId:b.id,kind:"focused",checkpoint:"Shared-interface checkpoint",workUnits:["foundation"],sourceFingerprint:B,workspaceFingerprint:W,parentCandidateId:null});b=state.builds[0];const failed=evaluation(b.id,plan,defined.revision,b.candidates[0].id,B,defined.content.acceptance,"fail");failed.checkpoint="Shared-interface checkpoint";failed.assignmentId="assignment-2";failed.charter.workUnits=["foundation"];build.recordEvaluation(root,failed);const raised=plan.content.evaluationBoundaries.map(x=>({...x,correctionCycleLimit:x.checkpoint==="Shared-interface checkpoint"?1:x.correctionCycleLimit}));build.adjustBudget(root,{buildId:b.id,participant:"Riley",boundaries:raised,explicitIncreaseJudgment:true,reason:"One bounded correction."});build.assignTask(root,assignment(b.id,"builder","Blair",["foundation"],null,B));build.recordWork(root,workInput(root,b.id,"foundation","Blair",B,D));const before=build.loadState(root);expect(()=>build.freezeCandidate(root,{buildId:b.id,kind:"focused",checkpoint:"Shared-interface checkpoint",workUnits:["foundation"],sourceFingerprint:D,workspaceFingerprint:W,parentCandidateId:null})).toThrow("lineage");state=build.freezeCandidate(root,{buildId:b.id,kind:"focused",checkpoint:"Shared-interface checkpoint",workUnits:["foundation"],sourceFingerprint:D,workspaceFingerprint:W,parentCandidateId:before.builds[0].candidates[0].id});expect(state.builds[0].candidates[1].parentCandidateId).toBe(state.builds[0].candidates[0].id);expect(state.builds[0].evidence.some(e=>e.result==="failed")).toBe(true)});
  it("routes Plan and Definition drift without silently reusing authority",async()=>{const{root,plan}=await setup();const state=build.initialize(root,activation(root,plan,["foundation"])),b=state.builds[0];planning.applyUpdate(root,{planId:plan.id,actor:{name:"Emi",responsibility:"engineering"},content:{risks:["Revalidated integration behavior"]},coherence:{status:"coherent",basis:"The delivery boundary is unchanged."}});let ps=planning.loadState(root);planning.review(root,{planIds:[plan.id]});ps=planning.loadState(root);const before=readFileSync(join(root,MILESTONE_BUILD_STATE_PATH),"utf8");expect(()=>build.status(root)).toThrow("foundations changed");expect(readFileSync(join(root,MILESTONE_BUILD_STATE_PATH),"utf8")).toBe(before);const ds=definition.loadState(root),rs=roadmap.loadState(root),es=engineering.loadState(root),pr=product.loadState(root);const revalidated=build.revalidate(root,{buildId:b.id,participant:"Emi",responsibility:"engineering",reviewedAnchors:{productRevision:pr.revision,engineeringRevision:es.revision,roadmapRevision:rs.revision,definitionStateRevision:ds.revision,planningStateRevision:ps.revision,changeRevision:null,definitionRevision:b.definitionRevision,planRevision:ps.plans[0].revision},sourceFingerprint:A,workspaceFingerprint:W,basis:"The Plan risk wording changed without changing the committed Definition or delivery approach."});expect(revalidated.builds[0].phase).toBe("paused");expect(revalidated.session.resumeAction).toContain("new exact-scope execution grant")});
  it("checks stale views before resume and reuses grants only with exact source/workspace anchors",async()=>{const{root,plan}=await setup();let state=build.initialize(root,activation(root,plan,["foundation"])),b=state.builds[0];state=build.interrupt(root,b.id,"Continue the first Work Unit");writeFileSync(join(root,b.artifactPath),"stale\n");const before=readFileSync(join(root,MILESTONE_BUILD_STATE_PATH),"utf8");await expect(build.resume(root,{sourceFingerprint:A,workspaceFingerprint:W})).rejects.toThrow("build-render");expect(readFileSync(join(root,MILESTONE_BUILD_STATE_PATH),"utf8")).toBe(before);build.renderCurrent(root);await expect(build.resume(root,{sourceFingerprint:B,workspaceFingerprint:W})).rejects.toThrow("exact source");state=await build.resume(root,{sourceFingerprint:A,workspaceFingerprint:W});expect(state.session.status).toBe("active")});
  it("rolls back canonical state and synchronized views when publication fails",async()=>{const{root,plan,definition:defined}=await setup();let state=await completeWork(root,plan),b=state.builds[0];build.assignTask(root,assignment(b.id,"final-evaluator","Quinn",["foundation","boundary"],"Integrated Milestone evaluation"));state=build.freezeCandidate(root,{buildId:b.id,kind:"integrated",checkpoint:"Integrated Milestone evaluation",workUnits:["foundation","boundary"],sourceFingerprint:C,workspaceFingerprint:W,parentCandidateId:null});b=state.builds[0];const before=snapshot(root,b.artifactPath),failing=await MilestoneBuildEngine.create(sourceRoot,{beforeCommit:path=>{if(path===b.artifactPath)throw new Error("injected Proof publication failure")}});expect(()=>failing.recordEvaluation(root,evaluation(b.id,plan,defined.revision,b.candidates[0].id,C,defined.content.acceptance))).toThrow("injected Proof publication failure");expect(snapshot(root,b.artifactPath)).toEqual(before)});
  it("registers the single-skill contract and complete CLI route without later-stage authority",()=>{expect(build.contract.scoped_execution_grant_required).toBe(true);expect(build.contract.final_integrated_pass_required).toBe(true);for(const command of["build-init","build-activate","build-assign","build-work","build-freeze","build-evaluate","build-adjust-budget","build-revalidate","build-render","build-interrupt","build-resume","build-stale","build-status"]){const args=[command,"--workspace","/tmp/project",...(["build-render","build-stale","build-status"].includes(command)?[]:command==="build-interrupt"?["--build-id","build-1","--resume-action","continue"]:["--input","/tmp/input.json"] )];expect(parseCliArguments(args).command).toBe(command)}expect(readFileSync(join(sourceRoot,"MILESTONE-BUILD-AND-PROVE-EXPERIENCE.md"),"utf8")).toContain("human Milestone Acceptance")});
});

describe("Slice 7 correction cycle 1 regressions",()=>{
  it("rejects a later eligible unordered Work Unit without an explicit safe parallel group and does not mutate",async()=>{
    const prepared=await setup({parallel:true});
    planning.applyUpdate(prepared.root,{planId:prepared.plan.id,actor:{name:"Emi",responsibility:"engineering"},content:{parallelClaims:[{workUnits:["foundation","boundary"],disposition:"blocked",conflicts:["sequential default"],basis:"No explicit safe-parallel group exists."}]},coherence:{status:"coherent",basis:"Both units are eligible but retain sequential-by-default execution."}});
    planning.review(prepared.root,{planIds:[prepared.plan.id]});
    const plan=planning.loadState(prepared.root).plans[0];
    const state=build.initialize(prepared.root,activation(prepared.root,plan,["foundation","boundary"])),id=state.builds[0].id,proof=state.builds[0].artifactPath;
    build.assignTask(prepared.root,assignment(id,"builder","Casey",["boundary"],null));
    const before=snapshot(prepared.root,proof);
    expect(()=>build.recordWork(prepared.root,workInput(prepared.root,id,"boundary","Casey",A,B))).toThrow("first eligible Work Unit");
    expect(snapshot(prepared.root,proof)).toEqual(before);
  });

  it("rejects a redundant active assignment before it can replace Work Unit ownership and does not mutate",async()=>{
    const{root,plan}=await setup();
    const state=build.initialize(root,activation(root,plan,["foundation"])),id=state.builds[0].id,proof=state.builds[0].artifactPath;
    build.assignTask(root,assignment(id,"builder","Blair",["foundation"],null));
    const before=snapshot(root,proof);
    expect(()=>build.assignTask(root,assignment(id,"builder","Casey",["foundation"],null))).toThrow("redundant assignment");
    expect(snapshot(root,proof)).toEqual(before);
  });

  it("rejects failed raw evidence presented as supported final coverage and does not mutate",async()=>{
    const{root,plan,definition:defined}=await setup();
    let state=await completeWork(root,plan),b=state.builds[0];
    build.assignTask(root,assignment(b.id,"final-evaluator","Quinn",["foundation","boundary"],"Integrated Milestone evaluation"));
    state=build.freezeCandidate(root,{buildId:b.id,kind:"integrated",checkpoint:"Integrated Milestone evaluation",workUnits:["foundation","boundary"],sourceFingerprint:C,workspaceFingerprint:W,parentCandidateId:null});b=state.builds[0];
    const input=evaluation(b.id,plan,defined.revision,b.candidates[0].id,C,defined.content.acceptance,"pass");input.evidence[0].result="failed";
    const before=snapshot(root,b.artifactPath);
    expect(()=>build.recordEvaluation(root,input)).toThrow("passing raw evidence");
    expect(snapshot(root,b.artifactPath)).toEqual(before);
  });

  it("rejects prior builder evidence as exact-candidate final support and does not mutate",async()=>{
    const{root,plan,definition:defined}=await setup();
    let state=await completeWork(root,plan),b=state.builds[0];
    build.assignTask(root,assignment(b.id,"final-evaluator","Quinn",["foundation","boundary"],"Integrated Milestone evaluation"));
    state=build.freezeCandidate(root,{buildId:b.id,kind:"integrated",checkpoint:"Integrated Milestone evaluation",workUnits:["foundation","boundary"],sourceFingerprint:C,workspaceFingerprint:W,parentCandidateId:null});b=state.builds[0];
    const input=evaluation(b.id,plan,defined.revision,b.candidates[0].id,C,defined.content.acceptance,"pass");input.evidence=[];
    for(const coverage of[...input.acceptanceCoverage,...input.checkCoverage])coverage.evidenceIds=["work-foundation-b"];
    const before=snapshot(root,b.artifactPath);
    expect(()=>build.recordEvaluation(root,input)).toThrow("independent final evaluator");
    expect(snapshot(root,b.artifactPath)).toEqual(before);
  });
});

describe("Slice 7 final bounded correction regressions",()=>{
  it("rejects assignment while interrupted and after ready for Demonstration without mutation",async()=>{
    const interrupted=await setup();
    let state=build.initialize(interrupted.root,activation(interrupted.root,interrupted.plan,["foundation"])),b=state.builds[0];
    build.interrupt(interrupted.root,b.id,"Wait for an explicit resume");
    let before=snapshot(interrupted.root,b.artifactPath);
    expect(()=>build.assignTask(interrupted.root,assignment(b.id,"builder","Blair",["foundation"],null))).toThrow("exact active Build session");
    expect(snapshot(interrupted.root,b.artifactPath)).toEqual(before);

    const ready=await setup();state=await completeWork(ready.root,ready.plan);b=state.builds[0];
    build.assignTask(ready.root,assignment(b.id,"final-evaluator","Quinn",["foundation","boundary"],"Integrated Milestone evaluation"));
    state=build.freezeCandidate(ready.root,{buildId:b.id,kind:"integrated",checkpoint:"Integrated Milestone evaluation",workUnits:["foundation","boundary"],sourceFingerprint:C,workspaceFingerprint:W,parentCandidateId:null});b=state.builds[0];
    state=build.recordEvaluation(ready.root,evaluation(b.id,ready.plan,ready.definition.revision,b.candidates[0].id,C,ready.definition.content.acceptance));b=state.builds[0];
    expect(b.phase).toBe("ready-for-demonstration");before=snapshot(ready.root,b.artifactPath);
    expect(()=>build.assignTask(ready.root,assignment(b.id,"builder","Blair",["foundation"],null,C))).toThrow("ready for Demonstration");
    expect(snapshot(ready.root,b.artifactPath)).toEqual(before);
  });

  it("rejects an unchanged correction candidate without consuming lineage or budget",async()=>{
    const{root,plan,definition:defined}=await setup({focused:true});
    let state=build.initialize(root,activation(root,plan,["foundation"])),b=state.builds[0];
    build.assignTask(root,assignment(b.id,"builder","Blair",["foundation"],null));build.recordWork(root,workInput(root,b.id,"foundation","Blair",A,B));
    build.assignTask(root,assignment(b.id,"focused-evaluator","Quinn",["foundation"],"Shared-interface checkpoint"));
    state=build.freezeCandidate(root,{buildId:b.id,kind:"focused",checkpoint:"Shared-interface checkpoint",workUnits:["foundation"],sourceFingerprint:B,workspaceFingerprint:W,parentCandidateId:null});b=state.builds[0];
    const failed=evaluation(b.id,plan,defined.revision,b.candidates[0].id,B,defined.content.acceptance,"fail");failed.checkpoint="Shared-interface checkpoint";failed.assignmentId="assignment-2";failed.charter.workUnits=["foundation"];build.recordEvaluation(root,failed);
    const raised=plan.content.evaluationBoundaries.map(x=>({...x,correctionCycleLimit:x.checkpoint==="Shared-interface checkpoint"?1:x.correctionCycleLimit}));
    state=build.adjustBudget(root,{buildId:b.id,participant:"Riley",boundaries:raised,explicitIncreaseJudgment:true,reason:"Allow one genuinely corrected candidate."});b=state.builds[0];
    const before=snapshot(root,b.artifactPath),parent=b.candidates[0].id;
    expect(()=>build.freezeCandidate(root,{buildId:b.id,kind:"focused",checkpoint:"Shared-interface checkpoint",workUnits:["foundation"],sourceFingerprint:B,workspaceFingerprint:W,parentCandidateId:parent})).toThrow("must change the exact source or workspace");
    expect(snapshot(root,b.artifactPath)).toEqual(before);
  });

  it("records a separate clean disposable evaluator workspace and fresh task context",async()=>{
    const{root,plan}=await setup();let state=await completeWork(root,plan),b=state.builds[0];
    const valid=assignment(b.id,"final-evaluator","Quinn",["foundation","boundary"],"Integrated Milestone evaluation"),invalid={...valid,evaluationWorkspace:{location:root,fingerprint:W,clean:true as const,disposable:true as const}};
    let before=snapshot(root,b.artifactPath);
    expect(()=>build.assignTask(root,invalid)).toThrow("separate clean disposable evaluator workspace");
    expect(snapshot(root,b.artifactPath)).toEqual(before);
    state=build.assignTask(root,valid);b=state.builds[0];const recorded=b.assignments.at(-1)!;
    expect(recorded).toMatchObject({taskContextIdentity:valid.taskContextIdentity,evaluationWorkspace:valid.evaluationWorkspace});
    before=snapshot(root,b.artifactPath);
    expect(()=>build.assignTask(root,valid)).toThrow("fresh evaluator task or context identity");
    expect(snapshot(root,b.artifactPath)).toEqual(before);
    build.renderCurrent(root);const proof=readFileSync(join(root,b.artifactPath),"utf8");
    expect(proof).toContain("Independent evaluation provenance");expect(proof).toContain(valid.taskContextIdentity);expect(proof).toContain(valid.evaluationWorkspace!.location);expect(proof).toContain(valid.evaluationWorkspace!.fingerprint);
  });
});
