import { readFile } from "node:fs/promises";
import { parse } from "yaml";
import { ContractError } from "./contract.js";
import { changeHistoryHash, changeSnapshotHash, routineHistoryHash } from "./change-management-meaning.js";
import { CHANGE_PERSPECTIVES, CHANGE_STATUSES, CHANGE_TARGET_KINDS, ROUTINE_CATEGORIES, type ChangeManagementContract, type ChangeManagementState, type ChangeTarget, type MaterialChange } from "./change-management-types.js";

function object(value: unknown, label: string): asserts value is Record<string, any> { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new ContractError(`${label} must be an object.`); }
function keys(value: Record<string, any>, allowed: readonly string[], label: string): void { const extras = Object.keys(value).filter((key) => !allowed.includes(key)); if (extras.length) throw new ContractError(`${label} contains unknown properties: ${extras.join(", ")}.`); }
function text(value: unknown, label: string): asserts value is string { if (typeof value !== "string" || !/[\p{L}\p{N}]/u.test(value)) throw new ContractError(`${label} must contain letters or numbers.`); }
function texts(value: unknown, label: string): asserts value is string[] { if (!Array.isArray(value)) throw new ContractError(`${label} must be an array.`); value.forEach((item, index) => text(item, `${label}[${index}]`)); }
function integer(value: unknown, label: string): asserts value is number { if (!Number.isInteger(value) || (value as number) < 0) throw new ContractError(`${label} must be a non-negative integer.`); }
function enumeration(value: unknown, allowed: readonly string[], label: string): void { if (!allowed.includes(value as string)) throw new ContractError(`${label} is invalid.`); }
function nextAction(value: unknown, label: string): void { object(value, label); keys(value, ["participant", "action", "reason"], label); text(value.participant, `${label}.participant`); text(value.action, `${label}.action`); text(value.reason, `${label}.reason`); }

export async function loadChangeManagementContract(path: string): Promise<ChangeManagementContract> {
  const value = parse(await readFile(path, "utf8")) as unknown; object(value, "Change Management contract");
  const fields = ["version", "id", "proposal_is_not_canonical", "exact_base_revisions", "no_partial_acceptance", "natural_language_authority", "one_acceptance_reconciles", "affected_only_atomic_reconciliation", "overlapping_changes_are_ordered", "append_only_hash_linked_history", "ordinary_updates_may_defer_publication", "rejected_operations_do_not_mutate", "later_stages_out_of_scope", "routine_requires_resolved_meaning_declaration"];
  keys(value, fields, "Change Management contract");
  if (value.version !== 1 || value.id !== "change-management" || fields.slice(2).some((field) => value[field] !== true)) throw new ContractError("Change Management contract does not preserve the accepted boundary.");
  return value as ChangeManagementContract;
}

export function validateChangeTarget(value: unknown, label: string): asserts value is ChangeTarget {
  object(value, label); keys(value, ["kind", "targetId", "field", "baseRevision", "value", "artifactPath", "currentMeaning", "proposedMeaning", "baseValueHash"], label);
  enumeration(value.kind, CHANGE_TARGET_KINDS, `${label}.kind`); if (value.targetId !== undefined) text(value.targetId, `${label}.targetId`);
  text(value.field, `${label}.field`); integer(value.baseRevision, `${label}.baseRevision`); text(value.artifactPath, `${label}.artifactPath`);
  text(value.currentMeaning, `${label}.currentMeaning`); text(value.proposedMeaning, `${label}.proposedMeaning`);
  if (value.baseValueHash !== undefined && (typeof value.baseValueHash !== "string" || !/^[a-f0-9]{64}$/.test(value.baseValueHash))) throw new ContractError(`${label}.baseValueHash is invalid.`);
  if (["roadmap-candidate", "milestone-definition"].includes(value.kind) && !value.targetId) throw new ContractError(`${label}.targetId is required.`);
}

function validateChange(value: unknown, label: string): asserts value is MaterialChange {
  object(value, label); keys(value, ["id", "title", "artifactPath", "status", "revision", "reviewedRevision", "reason", "targets", "downstreamConsequences", "unaffectedWork", "participants", "unknowns", "deferrals", "requiredPerspectives", "receipts", "coherence", "authorityRequested", "earliestStage", "nextAction", "dispositionReason", "history", "historyHead"], label);
  for (const field of ["id", "title", "artifactPath", "reason", "authorityRequested"] as const) text(value[field], `${label}.${field}`);
  enumeration(value.status, CHANGE_STATUSES, `${label}.status`); integer(value.revision, `${label}.revision`);
  if (value.reviewedRevision !== null) integer(value.reviewedRevision, `${label}.reviewedRevision`);
  if (!Array.isArray(value.targets) || !value.targets.length) throw new ContractError(`${label}.targets must not be empty.`); value.targets.forEach((target: unknown, index: number) => validateChangeTarget(target, `${label}.targets[${index}]`));
  const targetKeys = value.targets.map((target: ChangeTarget) => `${target.kind}:${target.targetId ?? ""}:${target.field}`); if (new Set(targetKeys).size !== targetKeys.length) throw new ContractError(`${label} targets must be unique.`);
  for (const field of ["downstreamConsequences", "unaffectedWork", "deferrals"] as const) texts(value[field], `${label}.${field}`);
  if (!Array.isArray(value.participants)) throw new ContractError(`${label}.participants must be an array.`); value.participants.forEach((item: unknown, index: number) => { object(item, `${label}.participants[${index}]`); keys(item, ["name", "perspective"], `${label}.participants[${index}]`); text(item.name, `${label}.participants[${index}].name`); enumeration(item.perspective, CHANGE_PERSPECTIVES, `${label}.participants[${index}].perspective`); });
  if (!Array.isArray(value.unknowns)) throw new ContractError(`${label}.unknowns must be an array.`); value.unknowns.forEach((item: unknown, index: number) => { object(item, `${label}.unknowns[${index}]`); keys(item, ["description", "blocking", "consequence", "revisitWhen"], `${label}.unknowns[${index}]`); text(item.description, `${label}.unknowns[${index}].description`); if (typeof item.blocking !== "boolean") throw new ContractError(`${label}.unknowns[${index}].blocking must be boolean.`); text(item.consequence, `${label}.unknowns[${index}].consequence`); text(item.revisitWhen, `${label}.unknowns[${index}].revisitWhen`); });
  if (!Array.isArray(value.requiredPerspectives) || !value.requiredPerspectives.length) throw new ContractError(`${label}.requiredPerspectives must not be empty.`); value.requiredPerspectives.forEach((item: unknown) => enumeration(item, CHANGE_PERSPECTIVES, `${label}.requiredPerspectives`)); if (new Set(value.requiredPerspectives).size !== value.requiredPerspectives.length) throw new ContractError(`${label}.requiredPerspectives must be unique.`);
  if (!Array.isArray(value.receipts)) throw new ContractError(`${label}.receipts must be an array.`); value.receipts.forEach((item: unknown, index: number) => { object(item, `${label}.receipts[${index}]`); keys(item, ["participant", "perspective", "revision"], `${label}.receipts[${index}]`); text(item.participant, `${label}.receipts[${index}].participant`); enumeration(item.perspective, CHANGE_PERSPECTIVES, `${label}.receipts[${index}].perspective`); if (item.revision !== value.revision) throw new ContractError(`${label} receipts must match the current revision.`); if (!value.requiredPerspectives.includes(item.perspective)) throw new ContractError(`${label} receipt perspective is not required.`); if (!value.participants.some((participant: any) => participant.name === item.participant && participant.perspective === item.perspective)) throw new ContractError(`${label} receipt does not match an explicitly represented participant perspective.`); }); if (new Set(value.receipts.map((item: any) => item.perspective)).size !== value.receipts.length) throw new ContractError(`${label} receipts must be unique by perspective.`);
  object(value.coherence, `${label}.coherence`); keys(value.coherence, ["status", "basis"], `${label}.coherence`); enumeration(value.coherence.status, ["draft", "blocked", "coherent"], `${label}.coherence.status`); if (typeof value.coherence.basis !== "string" || (value.coherence.status !== "draft" && !value.coherence.basis.trim())) throw new ContractError(`${label}.coherence.basis is invalid.`);
  enumeration(value.earliestStage, ["product-start", "engineering-foundation", "living-roadmap", "milestone-definition"], `${label}.earliestStage`); nextAction(value.nextAction, `${label}.nextAction`); if (typeof value.dispositionReason !== "string") throw new ContractError(`${label}.dispositionReason must be a string.`);
  if (!Array.isArray(value.history)) throw new ContractError(`${label}.history must be an array.`); let previous: string | null = null;
  value.history.forEach((entry: unknown, index: number) => { object(entry, `${label}.history[${index}]`); keys(entry, ["version", "operation", "summary", "beforeHash", "afterHash", "previousHash", "contentHash"], `${label}.history[${index}]`); if (entry.version !== index + 1) throw new ContractError(`${label} history versions must be sequential.`); enumeration(entry.operation, ["create", "update", "review", "agree", "accept", "reject", "withdraw", "defer", "pause", "resume", "render"], `${label}.history[${index}].operation`); text(entry.summary, `${label}.history[${index}].summary`); for (const field of ["beforeHash", "afterHash", "contentHash"] as const) if (typeof entry[field] !== "string" || !/^[a-f0-9]{64}$/.test(entry[field])) throw new ContractError(`${label}.history[${index}].${field} is invalid.`); const { contentHash, ...withoutHash } = entry; if (entry.previousHash !== previous || changeHistoryHash(withoutHash as any) !== contentHash) throw new ContractError(`${label} history integrity failed.`); previous = contentHash; });
  if (value.historyHead !== previous) throw new ContractError(`${label} history anchor is invalid.`); if (value.history.length && value.history.at(-1).afterHash !== changeSnapshotHash(value as MaterialChange)) throw new ContractError(`${label} does not match its history.`);
}

export function validateChangeManagementState(value: unknown): asserts value is ChangeManagementState {
  object(value, "Change Management state"); keys(value, ["schemaVersion", "stage", "workspaceClass", "workspaceRoot", "revision", "nextChangeNumber", "changes", "routineHistory", "routineHistoryHead", "nextActions", "session", "generatedViews"], "Change Management state");
  if (value.schemaVersion !== 1 || value.stage !== "change-management" || value.workspaceClass !== "human-project") throw new ContractError("Change Management state has an invalid schema or workspace class.");
  text(value.workspaceRoot, "workspaceRoot"); integer(value.revision, "revision"); integer(value.nextChangeNumber, "nextChangeNumber");
  if (!Array.isArray(value.changes)) throw new ContractError("changes must be an array."); value.changes.forEach((change, index) => validateChange(change, `changes[${index}]`));
  for (const field of ["id", "artifactPath"] as const) if (new Set(value.changes.map((item: any) => item[field])).size !== value.changes.length) throw new ContractError(`Change ${field} values must be unique.`);
  if (!Array.isArray(value.routineHistory)) throw new ContractError("routineHistory must be an array."); let previous: string | null = null; value.routineHistory.forEach((entry: unknown, index: number) => { object(entry, `routineHistory[${index}]`); keys(entry, ["version", "category", "summary", "classificationBasis", "target", "actor", "stateHash", "previousHash", "contentHash"], `routineHistory[${index}]`); if (entry.version !== index + 1) throw new ContractError("Routine history versions must be sequential."); enumeration(entry.category, ROUTINE_CATEGORIES, `routineHistory[${index}].category`); text(entry.summary, `routineHistory[${index}].summary`); text(entry.classificationBasis, `routineHistory[${index}].classificationBasis`); validateChangeTarget(entry.target, `routineHistory[${index}].target`); text(entry.actor, `routineHistory[${index}].actor`); if (typeof entry.stateHash !== "string" || !/^[a-f0-9]{64}$/.test(entry.stateHash)) throw new ContractError("Routine state hash is invalid."); const { contentHash, ...withoutHash } = entry; if (entry.previousHash !== previous || routineHistoryHash(withoutHash as any) !== contentHash) throw new ContractError("Routine history integrity failed."); previous = contentHash; }); if (value.routineHistoryHead !== previous) throw new ContractError("Routine history anchor is invalid.");
  if (!Array.isArray(value.nextActions) || value.nextActions.length !== 1) throw new ContractError("Change Management requires exactly one next action."); nextAction(value.nextActions[0], "nextActions[0]");
  object(value.session, "session"); keys(value.session, ["status", "changeId", "resumeAction"], "session"); enumeration(value.session.status, ["active", "interrupted"], "session.status"); if (value.session.changeId !== null) text(value.session.changeId, "session.changeId"); if (value.session.resumeAction !== null) text(value.session.resumeAction, "session.resumeAction");
  object(value.generatedViews, "generatedViews"); for (const [path, metadata] of Object.entries(value.generatedViews)) { object(metadata, `generatedViews.${path}`); keys(metadata, ["revision", "sha256"], `generatedViews.${path}`); integer(metadata.revision, `generatedViews.${path}.revision`); if (typeof metadata.sha256 !== "string" || !/^[a-f0-9]{64}$/.test(metadata.sha256)) throw new ContractError(`generatedViews.${path}.sha256 is invalid.`); }
}

export function materialReadinessGaps(change: MaterialChange): string[] {
  const gaps: string[] = [];
  if (change.coherence.status !== "coherent") gaps.push("Host-AI coherence assessment");
  if (!change.downstreamConsequences.length) gaps.push("downstream impact");
  if (!change.unaffectedWork.length) gaps.push("explicitly unaffected work");
  if (change.unknowns.some((item) => item.blocking)) gaps.push("essential unknown");
  if (!change.requiredPerspectives.length) gaps.push("required perspectives");
  if (change.requiredPerspectives.some((perspective) => !change.participants.some((participant) => participant.perspective === perspective))) gaps.push("participant for each required perspective");
  return gaps;
}
