import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { ContractError, validateState } from "./contract.js";
import { loadChangeManagementContract, materialReadinessGaps, validateChangeManagementState, validateChangeTarget } from "./change-management-contract.js";
import { changeHistoryHash, changeSnapshotHash, routineHistoryHash } from "./change-management-meaning.js";
import { CHANGE_PERSPECTIVES, ROUTINE_CATEGORIES, type ChangeDecision, type ChangeHistoryEntry, type ChangeManagementArtifacts, type ChangeManagementContract, type ChangeManagementState, type ChangePerspective, type ChangeTarget, type CreateMaterialChange, type MaterialChange, type RoutineChangeRequest, type UpdateMaterialChange } from "./change-management-types.js";
import { validateEngineeringState } from "./engineering-contract.js";
import { engineeringChangeHash, engineeringChangeSnapshotHash, engineeringConfirmationHash } from "./engineering-meaning.js";
import type { EngineeringChangeRevision, EngineeringConfirmedRevision, EngineeringFoundationState } from "./engineering-types.js";
import { ProductStartEngine } from "./engine.js";
import { validateLivingRoadmapState } from "./living-roadmap-contract.js";
import { livingRoadmapHistoryHash, livingRoadmapSnapshotHash } from "./living-roadmap-meaning.js";
import type { LivingRoadmapHistoryEntry, LivingRoadmapState } from "./living-roadmap-types.js";
import { validateMilestoneDefinitionState } from "./milestone-definition-contract.js";
import { definitionHistoryHash, definitionSnapshotHash } from "./milestone-definition-meaning.js";
import type { DefinitionHistoryEntry, MilestoneDefinitionState } from "./milestone-definition-types.js";
import { confirmationRevisionHash } from "./meaning.js";
import { CHANGE_MANAGEMENT_STATE_PATH, ENGINEERING_PROJECT_STATE_PATH, LIVING_ROADMAP_STATE_PATH, loadMilestoneDefinitionStateIfPresent, renderProjectViews, writeProjectViews } from "./project-views.js";
import type { ConfirmedRevision, ProductStartState } from "./types.js";
import { canonicalWorkspaceRoot, resolveInsideWorkspace, sha256, type FileSetWriteHooks, WorkspaceError, writeFileSetInsideWorkspace } from "./workspace.js";

const terminal = new Set(["accepted", "rejected", "withdrawn"]);
const emptyHash = createHash("sha256").update("none").digest("hex");
function clone<T>(value: T): T { return structuredClone(value); }
function text(value: string, label: string): string { if (!/[\p{L}\p{N}]/u.test(value)) throw new ContractError(`${label} must contain letters or numbers.`); return value.trim(); }
function slug(value: string): string { return value.normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "change"; }
function targetKey(target: ChangeTarget): string { return `${target.kind}:${target.targetId ?? ""}:${target.field}`; }
function unique<T>(values: T[]): T[] { return [...new Set(values)]; }
function stateHash(states: LifecycleStates): string { return sha256(JSON.stringify(states)); }

interface LifecycleStates { product: ProductStartState; engineering?: EngineeringFoundationState; roadmap?: LivingRoadmapState; definition?: MilestoneDefinitionState }

export class ChangeManagementEngine {
  readonly sourceRoot: string;
  readonly templateRoot: string;
  readonly contract: ChangeManagementContract;
  readonly productEngine: ProductStartEngine;
  private readonly writeHooks: FileSetWriteHooks;

  private constructor(sourceRoot: string, contract: ChangeManagementContract, productEngine: ProductStartEngine, writeHooks: FileSetWriteHooks) {
    this.sourceRoot = sourceRoot; this.templateRoot = join(sourceRoot, "templates"); this.contract = contract; this.productEngine = productEngine; this.writeHooks = writeHooks;
  }
  static async create(sourceRoot: string, writeHooks: FileSetWriteHooks = {}): Promise<ChangeManagementEngine> {
    const root = canonicalWorkspaceRoot(sourceRoot); const [contract, productEngine] = await Promise.all([loadChangeManagementContract(join(root, "engine/contracts/interviews/change-management.yaml")), ProductStartEngine.create(root)]);
    return new ChangeManagementEngine(root, contract, productEngine, writeHooks);
  }

  initialize(workspaceRoot: string): ChangeManagementState {
    const root = canonicalWorkspaceRoot(workspaceRoot); if (root === this.sourceRoot) throw new WorkspaceError("Loopy source cannot become its own Human project.");
    if (existsSync(resolveInsideWorkspace(root, CHANGE_MANAGEMENT_STATE_PATH))) throw new ContractError("Change Management already exists. Use change-status or propose another change.");
    const product = this.productEngine.loadState(root); if (product.phase !== "product-foundation-confirmed") throw new ContractError("Change Management requires confirmed or committed lifecycle meaning.");
    const state: ChangeManagementState = { schemaVersion: 1, stage: "change-management", workspaceClass: "human-project", workspaceRoot: root, revision: 0, nextChangeNumber: 1, changes: [], routineHistory: [], routineHistoryHead: null, nextActions: [{ participant: "Human", action: "Describe the correction or change", reason: "Loopy will distinguish routine maintenance from a material change before mutating accepted meaning." }], session: { status: "active", changeId: null, resumeAction: null }, generatedViews: {} };
    this.write(root, state, this.loadLifecycle(root)); return clone(state);
  }

  loadState(workspaceRoot: string): ChangeManagementState {
    const root = canonicalWorkspaceRoot(workspaceRoot); const value = JSON.parse(readFileSync(resolveInsideWorkspace(root, CHANGE_MANAGEMENT_STATE_PATH), "utf8")) as unknown; validateChangeManagementState(value); if (value.workspaceRoot !== root) throw new WorkspaceError("Change Management state does not belong to the target workspace."); return value;
  }

  propose(workspaceRoot: string, input: CreateMaterialChange): ChangeManagementState {
    this.validateCreate(input); const current = this.loadState(workspaceRoot); const lifecycle = this.loadLifecycle(workspaceRoot); input.targets.forEach((target) => this.assertCurrentBase(lifecycle, target));
    const targets = input.targets.map((target) => this.captureTargetBase(lifecycle, target));
    const next = clone(current); const base = slug(input.title); let readable = base; let suffix = 1;
    while (next.changes.some((item) => item.artifactPath === `docs/loopy/changes/${readable}/Change.md`) || existsSync(resolveInsideWorkspace(workspaceRoot, `docs/loopy/changes/${readable}/Change.md`))) readable = `${base}-${++suffix}`;
    const change: MaterialChange = { id: `change-${next.nextChangeNumber++}`, title: text(input.title, "title"), artifactPath: `docs/loopy/changes/${readable}/Change.md`, status: "draft", revision: 0, reviewedRevision: null, reason: text(input.reason, "reason"), targets, downstreamConsequences: clone(input.downstreamConsequences), unaffectedWork: clone(input.unaffectedWork), participants: clone(input.participants), unknowns: clone(input.unknowns), deferrals: clone(input.deferrals), requiredPerspectives: unique(input.requiredPerspectives), receipts: [], coherence: clone(input.coherence), authorityRequested: text(input.authorityRequested, "authorityRequested"), earliestStage: input.earliestStage, nextAction: clone(input.nextAction), dispositionReason: "", history: [], historyHead: null };
    this.rephase(change); this.appendHistory(clone(change), change, "create", `Created material change proposal ${change.title}.`, emptyHash); next.changes.push(change); next.revision += 1; next.nextActions = [clone(change.nextAction)]; next.session = { status: "active", changeId: change.id, resumeAction: null };
    this.write(workspaceRoot, next, lifecycle); return clone(next);
  }

  update(workspaceRoot: string, input: UpdateMaterialChange): ChangeManagementState {
    const current = this.loadState(workspaceRoot); const next = clone(current); const change = this.find(next, input.changeId); this.requireMutable(change); const before = clone(change);
    const fields: Array<keyof Omit<UpdateMaterialChange, "changeId">> = ["reason", "targets", "downstreamConsequences", "unaffectedWork", "participants", "unknowns", "deferrals", "requiredPerspectives", "coherence", "authorityRequested", "earliestStage", "nextAction"];
    let changed = false; for (const field of fields) if (input[field] !== undefined) { (change as any)[field] = clone(input[field]); changed = true; }
    if (!changed) throw new ContractError("Change update must change at least one field."); this.validateCreate(change); const lifecycle = this.loadLifecycle(workspaceRoot); if (input.targets) { change.targets.forEach((target) => this.assertCurrentBase(lifecycle, target)); change.targets = change.targets.map((target) => this.captureTargetBase(lifecycle, target)); } else change.targets.forEach((target) => this.assertCurrentOrIndependentBase(current, lifecycle, change, target));
    change.revision += 1; change.reviewedRevision = null; change.receipts = []; this.rephase(change); this.appendHistory(before, change, "update", `Updated material change proposal ${change.title}.`); next.revision += 1; next.nextActions = [clone(change.nextAction)];
    if (change.status === "blocked" || materialReadinessGaps(change).length === 0) this.write(workspaceRoot, next, lifecycle); else this.writeStateOnly(workspaceRoot, next); return clone(next);
  }

  review(workspaceRoot: string, changeId: string): ChangeManagementState {
    const current = this.loadState(workspaceRoot); const next = clone(current); const change = this.find(next, changeId); this.requireMutable(change); const lifecycle = this.loadLifecycle(workspaceRoot); const gaps = [...materialReadinessGaps(change), ...this.responsibilityGaps(change, lifecycle)]; if (gaps.length) throw new ContractError(`Change is not reviewable: ${unique(gaps).join(", ")}. Host AI remains responsible for semantic classification and impact completeness.`);
    change.targets.forEach((target) => this.assertCurrentOrIndependentBase(current, lifecycle, change, target)); const before = clone(change); change.reviewedRevision = change.revision; change.status = "ready"; this.appendHistory(before, change, "review", `Reviewed ${change.title} at proposal revision ${change.revision}.`); next.revision += 1; next.nextActions = [{ participant: change.requiredPerspectives.join(" and "), action: `Decide ${change.title}`, reason: "The complete proposal, impact, and authority request are ready; a clear final response may accept and reconcile it once." }]; this.write(workspaceRoot, next, lifecycle); return clone(next);
  }

  decide(workspaceRoot: string, decision: ChangeDecision): ChangeManagementState {
    const decisionExtras = Object.keys(decision as unknown as Record<string, unknown>).filter((key) => !["changeId", "participant", "perspectives", "decision", "basis", "reason", "explicitlyRepresents"].includes(key));
    if (decisionExtras.length) throw new ContractError(`Change decision contains unknown properties: ${decisionExtras.join(", ")}. Partial acceptance is not supported.`);
    if (!["accept", "reject", "withdraw", "defer"].includes(decision.decision)) throw new ContractError("Change decision must be accept, reject, withdraw, or defer.");
    const current = this.loadState(workspaceRoot); const next = clone(current); const change = this.find(next, decision.changeId); this.requireMutable(change); text(decision.participant, "participant"); text(decision.basis, "basis"); if (!decision.perspectives.length) throw new ContractError("A decision must identify represented responsibility perspectives.");
    const perspectives = unique(decision.perspectives); if (perspectives.some((item) => !CHANGE_PERSPECTIVES.includes(item))) throw new ContractError("Change decision contains an invalid responsibility perspective.");
    if (perspectives.length > 1) { const represented = unique(decision.explicitlyRepresents ?? []); if (represented.length !== perspectives.length || perspectives.some((item) => !represented.includes(item))) throw new ContractError("One participant may cover multiple perspectives only after explicitly representing each perspective."); }
    for (const perspective of perspectives) { if (!change.requiredPerspectives.includes(perspective)) throw new ContractError(`${perspective} is not required for this change.`); if (!change.participants.some((item) => item.name === decision.participant.trim() && item.perspective === perspective)) throw new ContractError(`${decision.participant.trim()} is not recorded as representing ${perspective} for this proposal.`); }
    const lifecycle = this.loadLifecycle(workspaceRoot);
    if (decision.decision === "accept") change.targets.forEach((target) => this.assertCurrentOrIndependentBase(current, lifecycle, change, target));
    const before = clone(change);
    if (decision.decision === "accept") {
      for (const perspective of perspectives) { change.receipts = change.receipts.filter((item) => item.perspective !== perspective); change.receipts.push({ participant: decision.participant.trim(), perspective, revision: change.revision }); }
      const gaps = materialReadinessGaps(change); if (gaps.length || change.reviewedRevision !== change.revision) throw new ContractError(`Change cannot be accepted: ${[...gaps, ...(change.reviewedRevision !== change.revision ? ["current proposal review"] : [])].join(", ")}.`);
      const missing = change.requiredPerspectives.filter((perspective) => !change.receipts.some((receipt) => receipt.perspective === perspective && receipt.revision === change.revision));
      if (missing.length) { change.status = "ready"; change.nextAction = { participant: missing.join(" and "), action: `Review and decide ${change.title}`, reason: `Current-revision agreement remains required from ${missing.join(" and ")}.` }; this.appendHistory(before, change, "agree", `Recorded ${perspectives.join(" and ")} agreement from ${decision.participant.trim()} for ${change.title}.`); next.revision += 1; next.nextActions = [clone(change.nextAction)]; next.session = { status: "active", changeId: change.id, resumeAction: null }; this.write(workspaceRoot, next, lifecycle); return clone(next); }
      const reconciled = this.reconcile(lifecycle, change); change.status = "accepted"; change.dispositionReason = decision.reason?.trim() || `Accepted from clear natural-language intent: ${decision.basis.trim()}`; change.nextAction = { participant: this.stageParticipant(change.earliestStage), action: `Continue from ${change.earliestStage.replaceAll("-", " ")} for the affected decisions`, reason: "The approved meaning is reconciled; the underlying product change has not been planned or implemented." }; this.appendHistory(before, change, "accept", `Accepted and atomically reconciled ${change.title}.`); next.revision += 1; next.nextActions = [clone(change.nextAction)]; next.session = { status: "active", changeId: null, resumeAction: null }; this.write(workspaceRoot, next, reconciled); return clone(next);
    }
    const operation = decision.decision === "reject" ? "reject" : decision.decision === "withdraw" ? "withdraw" : "defer"; change.status = decision.decision === "reject" ? "rejected" : decision.decision === "withdraw" ? "withdrawn" : "deferred"; change.dispositionReason = text(decision.reason ?? decision.basis, "disposition reason"); change.nextAction = decision.decision === "defer" ? { participant: "Change participant", action: `Revisit ${change.title} when its deferral condition occurs`, reason: change.dispositionReason } : { participant: "Human", action: "Continue with the current accepted lifecycle state", reason: `${change.title} did not change canonical intent.` }; this.appendHistory(before, change, operation, `${change.status} ${change.title}.`); next.revision += 1; next.nextActions = [clone(change.nextAction)]; next.session = { status: "active", changeId: null, resumeAction: null }; this.write(workspaceRoot, next, lifecycle); return clone(next);
  }

  applyRoutine(workspaceRoot: string, request: RoutineChangeRequest): ChangeManagementState {
    if (!ROUTINE_CATEGORIES.includes(request.category)) throw new ContractError("Routine correction category is invalid.");
    if (request.meaningPreserved !== true || request.meaningUncertainty !== "none") throw new ContractError("Routine correction requires an explicit Host-AI declaration that agreed meaning is preserved and no material meaning uncertainty remains."); text(request.classificationBasis, "classificationBasis"); text(request.summary, "summary"); text(request.actor, "actor"); validateChangeTarget(request.target, "target");
    const current = this.loadState(workspaceRoot); const lifecycle = this.loadLifecycle(workspaceRoot); this.assertCurrentBase(lifecycle, request.target); const reconciled = this.applyTargets(lifecycle, [request.target], [], true); const next = clone(current); const withoutHash = { version: next.routineHistory.length + 1, category: request.category, summary: request.summary.trim(), classificationBasis: request.classificationBasis.trim(), target: clone(request.target), actor: request.actor.trim(), stateHash: stateHash(reconciled), previousHash: next.routineHistoryHead }; const entry = { ...withoutHash, contentHash: routineHistoryHash(withoutHash) }; next.routineHistory.push(entry); next.routineHistoryHead = entry.contentHash; next.revision += 1; next.nextActions = [{ participant: "Human", action: "Continue with the current lifecycle work", reason: "The routine correction preserved agreed meaning and required no approval." }]; this.write(workspaceRoot, next, reconciled); return clone(next);
  }

  interrupt(workspaceRoot: string, changeId: string, resumeAction: string): ChangeManagementState { const current = this.loadState(workspaceRoot); const next = clone(current); const change = this.find(next, changeId); this.requireMutable(change); const before = clone(change); change.status = "paused"; change.nextAction = { participant: "Change participant", action: `Resume: ${text(resumeAction, "resumeAction")}`, reason: "The proposal and decision frontier are preserved." }; this.appendHistory(before, change, "pause", `Paused ${change.title}.`); next.revision += 1; next.nextActions = [clone(change.nextAction)]; next.session = { status: "interrupted", changeId, resumeAction: resumeAction.trim() }; this.write(workspaceRoot, next, this.loadLifecycle(workspaceRoot)); return clone(next); }
  async resume(workspaceRoot: string): Promise<ChangeManagementState> { const current = this.loadState(workspaceRoot); if (current.session.status !== "interrupted" || !current.session.changeId) throw new ContractError("Change Management is not interrupted."); const stale = await this.detectStaleViews(workspaceRoot); if (stale.length) throw new ContractError(`Change Management views are stale: ${stale.join(", ")}. Detect and explicitly repair them with change-render before resuming.`); const next = clone(current); const change = this.find(next, current.session.changeId); const before = clone(change); change.status = "draft"; this.rephase(change); change.nextAction = { participant: "Change participant", action: current.session.resumeAction!, reason: "Continue from the preserved proposal frontier." }; this.appendHistory(before, change, "resume", `Resumed ${change.title}.`); next.revision += 1; next.nextActions = [clone(change.nextAction)]; next.session = { status: "active", changeId: change.id, resumeAction: null }; this.write(workspaceRoot, next, this.loadLifecycle(workspaceRoot)); return clone(next); }
  renderCurrent(workspaceRoot: string): ChangeManagementArtifacts { const state = this.loadState(workspaceRoot); return this.write(workspaceRoot, state, this.loadLifecycle(workspaceRoot)); }
  status(workspaceRoot: string): ChangeManagementState { const state = this.loadState(workspaceRoot); this.write(workspaceRoot, state, this.loadLifecycle(workspaceRoot)); return clone(state); }
  async detectStaleViews(workspaceRoot: string): Promise<string[]> { const state = this.loadState(workspaceRoot); const expected = this.render(state, this.loadLifecycle(workspaceRoot)); const stale: string[] = []; for (const [path, content] of Object.entries(expected)) { const recorded = state.generatedViews[path]; if (!recorded || recorded.revision !== state.revision || recorded.sha256 !== sha256(content)) { stale.push(path); continue; } try { if (await readFile(resolveInsideWorkspace(workspaceRoot, path), "utf8") !== content) stale.push(path); } catch { stale.push(path); } } return stale; }

  private validateCreate(input: CreateMaterialChange | MaterialChange): void { text(input.reason, "reason"); text(input.authorityRequested, "authorityRequested"); if (!Array.isArray(input.targets) || !input.targets.length) throw new ContractError("A material change requires at least one affected target; partial acceptance is not supported, so split separable proposals first."); input.targets.forEach((target, index) => validateChangeTarget(target, `targets[${index}]`)); if (new Set(input.targets.map(targetKey)).size !== input.targets.length) throw new ContractError("Affected targets must be unique."); if (!Array.isArray(input.requiredPerspectives) || !input.requiredPerspectives.length || input.requiredPerspectives.some((item) => !CHANGE_PERSPECTIVES.includes(item))) throw new ContractError("A material change requires valid responsibility perspectives."); }
  private find(state: ChangeManagementState, id: string): MaterialChange { const change = state.changes.find((item) => item.id === id); if (!change) throw new ContractError(`Unknown change identity: ${id}.`); return change; }
  private requireMutable(change: MaterialChange): void { if (terminal.has(change.status)) throw new ContractError(`A ${change.status} change cannot be mutated.`); }
  private rephase(change: MaterialChange): void { if (terminal.has(change.status) || change.status === "paused" || change.status === "deferred") return; change.status = change.coherence.status === "blocked" || change.unknowns.some((item) => item.blocking) ? "blocked" : change.reviewedRevision === change.revision && materialReadinessGaps(change).length === 0 ? "ready" : "draft"; }
  private appendHistory(before: MaterialChange, after: MaterialChange, operation: ChangeHistoryEntry["operation"], summary: string, explicitBefore?: string): void { const withoutHash: Omit<ChangeHistoryEntry, "contentHash"> = { version: after.history.length + 1, operation, summary, beforeHash: explicitBefore ?? changeSnapshotHash(before), afterHash: changeSnapshotHash(after), previousHash: after.historyHead }; const entry = { ...withoutHash, contentHash: changeHistoryHash(withoutHash) }; after.history.push(entry); after.historyHead = entry.contentHash; }
  private stageParticipant(stage: MaterialChange["earliestStage"]): string { return stage === "product-start" || stage === "living-roadmap" ? "Product" : stage === "engineering-foundation" ? "Engineering" : "Milestone participants"; }
  private responsibilityGaps(change: MaterialChange, states: LifecycleStates): string[] { const gaps: string[] = []; if (change.targets.some((target) => target.kind === "product") && !change.requiredPerspectives.includes("product")) gaps.push("Product perspective for Product meaning"); if (change.targets.some((target) => target.kind === "engineering") && !change.requiredPerspectives.includes("engineering")) gaps.push("Engineering perspective for Engineering meaning"); for (const target of change.targets.filter((item) => item.kind === "milestone-definition")) { const definition = states.definition?.definitions.find((item) => item.id === target.targetId); if (definition) for (const perspective of definition.requiredPerspectives) if (!change.requiredPerspectives.includes(perspective)) gaps.push(`${perspective} perspective for the committed Definition boundary`); } return gaps; }

  private loadLifecycle(workspaceRoot: string): LifecycleStates { const root = canonicalWorkspaceRoot(workspaceRoot); const product = this.productEngine.loadState(root); const engineeringPath = resolveInsideWorkspace(root, ENGINEERING_PROJECT_STATE_PATH); const roadmapPath = resolveInsideWorkspace(root, LIVING_ROADMAP_STATE_PATH); const engineering = existsSync(engineeringPath) ? JSON.parse(readFileSync(engineeringPath, "utf8")) as EngineeringFoundationState : undefined; const roadmap = existsSync(roadmapPath) ? JSON.parse(readFileSync(roadmapPath, "utf8")) as LivingRoadmapState : undefined; if (engineering) validateEngineeringState(this.productEngine.engineeringContract, engineering); if (roadmap) validateLivingRoadmapState(this.productEngine.livingRoadmapContract, roadmap); const definition = loadMilestoneDefinitionStateIfPresent(root); return { product, engineering, roadmap, definition }; }
  private stageRevision(states: LifecycleStates, target: ChangeTarget): number { if (target.kind === "product") return states.product.revision; if (target.kind === "engineering") { if (!states.engineering) throw new ContractError("Engineering foundation does not exist."); return states.engineering.revision; } if (target.kind === "roadmap-candidate") { if (!states.roadmap) throw new ContractError("Living Roadmap does not exist."); return states.roadmap.revision; } if (!states.definition) throw new ContractError("Milestone Definition state does not exist."); const definition = states.definition.definitions.find((item) => item.id === target.targetId); if (!definition) throw new ContractError(`Unknown Definition target: ${target.targetId}.`); return definition.revision; }
  private assertCurrentBase(states: LifecycleStates, target: ChangeTarget): void { this.assertArtifact(states, target); if (this.stageRevision(states, target) !== target.baseRevision) throw new ContractError(`${targetKey(target)} does not match its declared base revision.`); }
  private assertCurrentOrIndependentBase(state: ChangeManagementState, states: LifecycleStates, change: MaterialChange, target: ChangeTarget): void { this.assertArtifact(states, target); const revision = this.stageRevision(states, target); if (revision < target.baseRevision) throw new ContractError(`${targetKey(target)} has an impossible future base revision.`); if (!target.baseValueHash || target.baseValueHash !== this.targetValueHash(states, target)) throw new ContractError(`${targetKey(target)} is stale because its exact canonical target changed; reassess it against the current base revision.`); const overlap = state.changes.some((other) => other.id !== change.id && other.status === "accepted" && other.targets.some((item) => targetKey(item) === targetKey(target) && item.baseRevision >= target.baseRevision)); if (overlap) throw new ContractError(`${targetKey(target)} conflicts with an accepted overlapping change; reassess it against the current base revision.`); }
  private assertArtifact(states: LifecycleStates, target: ChangeTarget): void { const expected = target.kind === "product" ? "docs/loopy/Project-Definition.md" : target.kind === "engineering" ? "docs/loopy/Engineering-Guide.md" : target.kind === "roadmap-candidate" ? "docs/loopy/Roadmap.md" : states.definition?.definitions.find((item) => item.id === target.targetId)?.artifactPath; if (!expected || target.artifactPath !== expected) throw new ContractError(`${targetKey(target)} must name its exact contained human artifact path.`); resolveInsideWorkspace(states.product.workspaceRoot, target.artifactPath); }

  private targetValue(states: LifecycleStates, target: ChangeTarget): unknown { const root: any = target.kind === "product" ? states.product : target.kind === "engineering" ? states.engineering : target.kind === "roadmap-candidate" ? states.roadmap?.candidates.find((item) => item.id === target.targetId) : states.definition?.definitions.find((item) => item.id === target.targetId); if (!root) throw new ContractError(`Canonical target does not exist: ${targetKey(target)}.`); let cursor = root; for (const part of target.field.split(".")) { if (typeof cursor !== "object" || cursor === null || !(part in cursor)) throw new ContractError(`Canonical target field does not exist: ${target.field}.`); cursor = cursor[part]; } return cursor; }
  private targetValueHash(states: LifecycleStates, target: ChangeTarget): string { return sha256(JSON.stringify(this.targetValue(states, target))); }
  private captureTargetBase(states: LifecycleStates, target: ChangeTarget): ChangeTarget { return { ...clone(target), baseValueHash: this.targetValueHash(states, target) }; }

  private setField(root: any, field: string, value: unknown, allowed: string[], label: string): void { if (!allowed.some((prefix) => field === prefix || field.startsWith(`${prefix}.`))) throw new ContractError(`${label} field is outside the bounded Change Management surface: ${field}.`); const parts = field.split("."); let cursor = root; for (const part of parts.slice(0, -1)) { if (typeof cursor !== "object" || cursor === null || !(part in cursor)) throw new ContractError(`${label} field does not exist: ${field}.`); cursor = cursor[part]; } const last = parts.at(-1)!; if (typeof cursor !== "object" || cursor === null || !(last in cursor)) throw new ContractError(`${label} field does not exist: ${field}.`); cursor[last] = clone(value); }
  private applyTargets(states: LifecycleStates, targets: ChangeTarget[], receipts: Array<{ participant: string; perspective: ChangePerspective }>, routine: boolean): LifecycleStates {
    const next = clone(states); const productTargets = targets.filter((item) => item.kind === "product"); const engineeringTargets = targets.filter((item) => item.kind === "engineering"); const roadmapTargets = targets.filter((item) => item.kind === "roadmap-candidate"); const definitionTargets = targets.filter((item) => item.kind === "milestone-definition");
    if (productTargets.length) { for (const target of productTargets) this.setField(next.product, target.field, target.value, ["product", "decisions", "conditionalDecisions", "roadmap.summary", "roadmap.productNotes"], "Product"); next.product.draftVersion += 1; next.product.revision += 1; next.product.reviewedDraftVersion = next.product.draftVersion; next.product.phase = "product-foundation-confirmed"; next.product.responsibilityConfirmations = unique([...next.product.responsibilityConfirmations, ...receipts.filter((item) => item.perspective === "product").map((item) => "product")]); const withoutHash: Omit<ConfirmedRevision, "contentHash"> = { revision: next.product.revision, draftVersion: next.product.draftVersion, product: clone(next.product.product), decisions: clone(next.product.decisions), conditionalDecisions: clone(next.product.conditionalDecisions), contextGrants: clone(next.product.contextGrants), roadmap: clone(next.product.roadmap), responsibilityConfirmations: clone(next.product.responsibilityConfirmations), roadmapHistoryHead: next.product.roadmapHistoryHead, previousHash: next.product.confirmedHistory.at(-1)?.contentHash ?? null }; next.product.confirmedHistory.push({ ...withoutHash, contentHash: confirmationRevisionHash(withoutHash) }); }
    if (engineeringTargets.length) { if (!next.engineering) throw new ContractError("Engineering foundation does not exist."); for (const target of engineeringTargets) this.setField(next.engineering, target.field, target.value, ["engineering", "decisions"], "Engineering"); next.engineering.draftVersion += 1; next.engineering.revision += 1; next.engineering.reviewedDraftVersion = next.engineering.draftVersion; next.engineering.phase = "engineering-foundation-confirmed"; next.engineering.responsibilityConfirmations = unique([...next.engineering.responsibilityConfirmations, ...receipts.filter((item) => item.perspective === "engineering").map(() => "engineering")]); const changeWithout: Omit<EngineeringChangeRevision, "contentHash"> = { version: next.engineering.changeHistory.length + 1, kind: routine ? "evidence-refresh" : "material", draftVersion: next.engineering.draftVersion, snapshotHash: engineeringChangeSnapshotHash(next.engineering), previousHash: next.engineering.changeHistoryHead }; const changeEntry = { ...changeWithout, contentHash: engineeringChangeHash(changeWithout) }; next.engineering.changeHistory.push(changeEntry); next.engineering.changeHistoryHead = changeEntry.contentHash; }
    if (roadmapTargets.length) { if (!next.roadmap) throw new ContractError("Living Roadmap does not exist."); const before = clone(next.roadmap); for (const target of roadmapTargets) { const candidate = next.roadmap.candidates.find((item) => item.id === target.targetId); if (!candidate) throw new ContractError(`Unknown Roadmap candidate target: ${target.targetId}.`); this.setField(candidate, target.field, target.value, ["title", "outcome", "priority", "rationale", "dependencies", "blockers", "nextShapingStep", "participants", "dispositionReason", "reconsiderWhen"], "Roadmap candidate"); } next.roadmap.revision += 1; const withoutHash: Omit<LivingRoadmapHistoryEntry, "contentHash"> = { version: next.roadmap.history.length + 1, operation: "change-management", summary: routine ? "Applied routine meaning-preserving Roadmap correction." : "Reconciled an accepted material Roadmap change.", beforeHash: livingRoadmapSnapshotHash(before), afterHash: livingRoadmapSnapshotHash(next.roadmap), previousHash: next.roadmap.historyHead }; const entry = { ...withoutHash, contentHash: livingRoadmapHistoryHash(withoutHash) }; next.roadmap.history.push(entry); next.roadmap.historyHead = entry.contentHash; }
    if (definitionTargets.length) { if (!next.definition) throw new ContractError("Milestone Definition state does not exist."); for (const target of definitionTargets) { const definition = next.definition.definitions.find((item) => item.id === target.targetId); if (!definition) throw new ContractError(`Unknown Definition target: ${target.targetId}.`); const before = clone(definition); const existingReceipts = clone(definition.receipts); this.setField(definition, target.field, target.value, ["content", "coherence", "requiredPerspectives", "specialistInputs"], "Milestone Definition"); definition.revision += 1; definition.reviewedRevision = definition.revision; definition.receipts = routine ? existingReceipts.map((receipt) => ({ ...receipt, revision: definition.revision })) : definition.requiredPerspectives.map((perspective) => { const receipt = receipts.find((item) => item.perspective === perspective); if (!receipt) throw new ContractError(`Accepted Definition change requires ${perspective} agreement on the proposal revision.`); return { perspective, participant: receipt.participant, revision: definition.revision }; }); definition.phase = "committed"; const withoutHash: Omit<DefinitionHistoryEntry, "contentHash"> = { version: definition.history.length + 1, operation: "change-management", summary: routine ? `Applied a declared meaning-preserving correction to ${definition.sourceCandidateTitle}.` : `Reconciled accepted Change Management decisions for ${definition.sourceCandidateTitle}.`, beforeHash: definitionSnapshotHash(before), afterHash: definitionSnapshotHash(definition), previousHash: definition.historyHead }; const entry = { ...withoutHash, contentHash: definitionHistoryHash(withoutHash) }; definition.history.push(entry); definition.historyHead = entry.contentHash; } next.definition.revision += 1; }
    this.synchronizeAnchors(next, productTargets.length > 0, engineeringTargets.length > 0, roadmapTargets.length > 0);
    validateState(this.productEngine.contract, next.product); if (next.engineering) validateEngineeringState(this.productEngine.engineeringContract, next.engineering); if (next.roadmap) validateLivingRoadmapState(this.productEngine.livingRoadmapContract, next.roadmap); if (next.definition) validateMilestoneDefinitionState(next.definition); return next;
  }
  private reconcile(states: LifecycleStates, change: MaterialChange): LifecycleStates { return this.applyTargets(states, change.targets, change.receipts, false); }
  private synchronizeAnchors(states: LifecycleStates, productChanged: boolean, engineeringChanged: boolean, roadmapChanged: boolean): void {
    if (productChanged) { const productReceipt = states.product.confirmedHistory.at(-1)!; if (states.engineering) { states.engineering.productRevision = states.product.revision; states.engineering.productConfirmationHash = productReceipt.contentHash; if (!engineeringChanged) { states.engineering.revision += 1; const withoutChange: Omit<EngineeringChangeRevision, "contentHash"> = { version: states.engineering.changeHistory.length + 1, kind: "evidence-refresh", draftVersion: states.engineering.draftVersion, snapshotHash: engineeringChangeSnapshotHash(states.engineering), previousHash: states.engineering.changeHistoryHead }; const changeEntry = { ...withoutChange, contentHash: engineeringChangeHash(withoutChange) }; states.engineering.changeHistory.push(changeEntry); states.engineering.changeHistoryHead = changeEntry.contentHash; } } if (states.roadmap) { const before = clone(states.roadmap); states.roadmap.productRevision = states.product.revision; states.roadmap.productDraftVersion = states.product.draftVersion; states.roadmap.revision += 1; const withoutHash: Omit<LivingRoadmapHistoryEntry, "contentHash"> = { version: states.roadmap.history.length + 1, operation: "change-management", summary: "Synchronized the Roadmap to an accepted Product change without changing additional candidate meaning.", beforeHash: livingRoadmapSnapshotHash(before), afterHash: livingRoadmapSnapshotHash(states.roadmap), previousHash: states.roadmap.historyHead }; const entry = { ...withoutHash, contentHash: livingRoadmapHistoryHash(withoutHash) }; states.roadmap.history.push(entry); states.roadmap.historyHead = entry.contentHash; } }
    if (states.engineering && (productChanged || engineeringChanged)) { const tracked = states.engineering.changeHistory.at(-1); if (tracked && engineeringChanged) { const { contentHash: _oldHash, ...trackedWithoutHash } = tracked; const withoutTracked: Omit<EngineeringChangeRevision, "contentHash"> = { ...trackedWithoutHash, snapshotHash: engineeringChangeSnapshotHash(states.engineering) }; tracked.snapshotHash = withoutTracked.snapshotHash; tracked.contentHash = engineeringChangeHash(withoutTracked); states.engineering.changeHistoryHead = tracked.contentHash; } const last = states.engineering.confirmedHistory.at(-1); if (!last || last.revision !== states.engineering.revision || last.productRevision !== states.engineering.productRevision) { const withoutHash: Omit<EngineeringConfirmedRevision, "contentHash"> = { revision: states.engineering.revision, draftVersion: states.engineering.draftVersion, productRevision: states.engineering.productRevision, productConfirmationHash: states.engineering.productConfirmationHash, engineering: clone(states.engineering.engineering), decisions: clone(states.engineering.decisions), contextGrants: clone(states.engineering.contextGrants), responsibilityConfirmations: clone(states.engineering.responsibilityConfirmations), previousHash: last?.contentHash ?? null }; states.engineering.confirmedHistory.push({ ...withoutHash, contentHash: engineeringConfirmationHash(withoutHash) }); } }
    if (states.definition) { states.definition.productRevision = states.product.revision; states.definition.productDraftVersion = states.product.draftVersion; if (states.engineering) states.definition.engineeringRevision = states.engineering.revision; if (states.roadmap) states.definition.roadmapRevision = states.roadmap.revision; if ((productChanged || engineeringChanged || roadmapChanged) && !states.definition.definitions.some((item) => item.history.at(-1)?.operation === "change-management")) states.definition.revision += 1; }
  }

  private render(state: ChangeManagementState, lifecycle: LifecycleStates): ChangeManagementArtifacts { return renderProjectViews(lifecycle.product, this.templateRoot, lifecycle.engineering, lifecycle.roadmap, lifecycle.definition, state).changeManagement!; }
  private write(workspaceRoot: string, state: ChangeManagementState, lifecycle: LifecycleStates): ChangeManagementArtifacts { const rendered = writeProjectViews({ workspaceRoot, templateRoot: this.templateRoot, productContract: this.productEngine.contract, product: lifecycle.product, engineeringContract: lifecycle.engineering ? this.productEngine.engineeringContract : undefined, engineering: lifecycle.engineering, livingRoadmapContract: lifecycle.roadmap ? this.productEngine.livingRoadmapContract : undefined, livingRoadmap: lifecycle.roadmap, milestoneDefinition: lifecycle.definition, changeManagement: state, writeHooks: this.writeHooks }); return rendered.changeManagement!; }
  private writeStateOnly(workspaceRoot: string, state: ChangeManagementState): void { validateChangeManagementState(state); writeFileSetInsideWorkspace(canonicalWorkspaceRoot(workspaceRoot), [[CHANGE_MANAGEMENT_STATE_PATH, `${JSON.stringify(state, null, 2)}\n`]], this.writeHooks); }
}
