import { existsSync, readFileSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { ContractError } from "./contract.js";
import { ProductStartEngine } from "./engine.js";
import { LivingRoadmapEngine } from "./living-roadmap-engine.js";
import { MilestoneDefinitionEngine } from "./milestone-definition-engine.js";
import { loadMilestonePlanningContract, planGaps, validateMilestonePlanningState, validatePlanningUpdate } from "./milestone-planning-contract.js";
import { planSnapshotHash, planningHistoryHash } from "./milestone-planning-meaning.js";
import { GUIDE_KINDS, type ConditionalGuide, type FoundationAnchors, type GuideConfirmation, type MilestonePlan, type MilestonePlanningArtifacts, type MilestonePlanningContract, type MilestonePlanningState, type PlanningHistoryEntry, type PlanningRevalidation, type PlanningReview, type PlanningUpdate } from "./milestone-planning-types.js";
import { CHANGE_MANAGEMENT_STATE_PATH, MILESTONE_PLANNING_STATE_PATH, loadChangeManagementStateIfPresent, renderProjectViews, writeProjectViews } from "./project-views.js";
import { canonicalWorkspaceRoot, resolveInsideWorkspace, sha256, type FileSetWriteHooks, WorkspaceError, writeFileSetInsideWorkspace } from "./workspace.js";
function clone<T>(v:T):T{return structuredClone(v)}
function text(v:string,l:string):string{if(!/[\p{L}\p{N}]/u.test(v))throw new ContractError(`${l} must contain letters or numbers.`);return v.trim()}
export class MilestonePlanningEngine{
  readonly sourceRoot:string;readonly templateRoot:string;readonly contract:MilestonePlanningContract;readonly productEngine:ProductStartEngine;readonly roadmapEngine:LivingRoadmapEngine;readonly definitionEngine:MilestoneDefinitionEngine;private readonly hooks:FileSetWriteHooks;
  private constructor(root:string,c:MilestonePlanningContract,p:ProductStartEngine,r:LivingRoadmapEngine,d:MilestoneDefinitionEngine,h:FileSetWriteHooks){this.sourceRoot=root;this.templateRoot=join(root,"templates");this.contract=c;this.productEngine=p;this.roadmapEngine=r;this.definitionEngine=d;this.hooks=h}
  static async create(sourceRoot:string,hooks:FileSetWriteHooks={}):Promise<MilestonePlanningEngine>{const root=canonicalWorkspaceRoot(sourceRoot);const [c,p,r,d]=await Promise.all([loadMilestonePlanningContract(join(root,"engine/contracts/interviews/milestone-planning.yaml")),ProductStartEngine.create(root),LivingRoadmapEngine.create(root),MilestoneDefinitionEngine.create(root)]);return new MilestonePlanningEngine(root,c,p,r,d,hooks)}
  initialize(workspaceRoot:string,definitionIds:string[]):MilestonePlanningState{const root=canonicalWorkspaceRoot(workspaceRoot);if(root===this.sourceRoot)throw new WorkspaceError("Loopy source cannot become its own Human project.");if(existsSync(resolveInsideWorkspace(root,MILESTONE_PLANNING_STATE_PATH)))throw new ContractError("Milestone Planning already exists. Use planning-status or planning-resume.");if(!Array.isArray(definitionIds)||!definitionIds.length||new Set(definitionIds).size!==definitionIds.length)throw new ContractError("Planning requires distinct explicitly named committed Definitions.");const product=this.productEngine.loadState(root),engineering=this.productEngine.loadEngineeringStateIfPresent(root),roadmap=this.roadmapEngine.loadState(root),definitions=this.definitionEngine.loadState(root);const selected=definitionIds.map(id=>{const d=definitions.definitions.find(x=>x.id===id);if(!d||d.phase!=="committed")throw new ContractError(`Planning requires a committed Definition: ${id}.`);return d});const plans=selected.sort((a,b)=>a.order-b.order||a.id.localeCompare(b.id)).map((d,i):MilestonePlan=>({id:`plan-${i+1}`,definitionId:d.id,title:d.sourceCandidateTitle,definitionRevision:d.revision,artifactPath:join(dirname(d.artifactPath),"Plan.md"),order:i,phase:"draft",revision:0,reviewedRevision:null,coherence:{status:"draft",basis:""},content:{approach:[],workUnits:[],dependencies:[],parallelism:[],parallelClaims:[],checksAndEvidence:[],evaluationBoundaries:[],risks:[],unknowns:[],releaseImpact:[]},participants:[],workspaceDisposition:{mode:"same-directory",location:"",basis:"Use the current project directory unless Engineering identifies safe independent work."},guideTriggers:[],history:[],historyHead:null}));const guides:ConditionalGuide[]=GUIDE_KINDS.map(kind=>({kind,artifactPath:kind==="architecture"?"docs/loopy/Architecture.md":kind==="demo-strategy"?"docs/loopy/Demo-Strategy.md":"docs/loopy/Release-Strategy.md",status:"not-needed",revision:0,reviewedRevision:null,coherence:{status:"draft",basis:""},requiredPerspective:kind==="architecture"?"architecture":kind==="demo-strategy"?"demo-quality":"release",content:[],receipt:null}));const state:MilestonePlanningState={schemaVersion:1,stage:"milestone-planning",workspaceClass:"human-project",workspaceRoot:root,productRevision:product.revision,engineeringRevision:engineering?.revision??null,roadmapRevision:roadmap.revision,definitionStateRevision:definitions.revision,revision:0,plans,guides,nextActions:[{participant:"Engineering",action:`Plan ${plans[0].title}`,reason:"Establish the bounded delivery approach without changing its committed Definition."}],session:{status:"active",planId:plans[0].id,resumeAction:null},generatedViews:{}};this.write(root,state);return clone(state)}
  loadState(root:string):MilestonePlanningState{const canonical=canonicalWorkspaceRoot(root),value=this.readState(canonical),lifecycle=this.lifecycle(canonical);this.assertCurrentAnchors(value,this.anchors(lifecycle));for(const p of value.plans){const d=lifecycle.definition.definitions.find(x=>x.id===p.definitionId);if(!d||d.phase!=="committed"||d.revision!==p.definitionRevision)throw new ContractError(`${p.title} Plan is stale against its authoritative committed Definition; explicit Host semantic revalidation is required before continuing.`);}return value}
  applyUpdate(root:string,input:PlanningUpdate):MilestonePlanningState{validatePlanningUpdate(input);const current=this.loadState(root),next=clone(current),plan=this.find(next,input.planId),before=clone(plan);if(input.content)plan.content={...plan.content,...clone(input.content)};if(input.coherence)plan.coherence=clone(input.coherence);this.validateCoherentEvaluationBudget(plan);plan.content.evaluationBoundaries.sort((left,right)=>this.evaluationOrder(plan,left)-this.evaluationOrder(plan,right)||left.checkpoint.localeCompare(right.checkpoint));if(input.participants)plan.participants=clone(input.participants);if(input.workspaceDisposition)plan.workspaceDisposition=clone(input.workspaceDisposition);if(input.guideTriggers)plan.guideTriggers=clone(input.guideTriggers);for(const update of input.guides??[]){const guide=next.guides.find(g=>g.kind===update.kind);if(!guide)throw new ContractError("Unknown conditional guide.");guide.content=clone(update.content);guide.coherence=clone(update.coherence);guide.revision+=1;guide.reviewedRevision=null;guide.receipt=null;guide.status="draft";}plan.revision+=1;plan.reviewedRevision=null;this.rephase(plan,next);this.history(before,plan,"update",`Updated ${plan.title} planning from ${input.actor.name}.`);next.revision+=1;next.session={status:"active",planId:plan.id,resumeAction:null};next.nextActions=[this.route(next)];if(plan.phase==="blocked"||planGaps(plan,next.guides).length===0)this.write(root,next);else this.writeStateOnly(root,next);return clone(next)}
  review(root:string,input:PlanningReview):MilestonePlanningState{if((!input.planIds.length&&!(input.guideKinds??[]).length)||new Set(input.planIds).size!==input.planIds.length)throw new ContractError("Planning review requires distinct named Plans or guides.");const current=this.loadState(root),next=clone(current);for(const id of input.planIds){const plan=this.find(next,id),gaps=planGaps(plan,next.guides);if(gaps.length)throw new ContractError(`${plan.title} is not formally reviewable: ${gaps.join(", ")}. Host AI owns semantic coherence.`);}for(const kind of input.guideKinds??[]){const guide=next.guides.find(g=>g.kind===kind)!;if(!guide.content.length||guide.coherence.status!=="coherent")throw new ContractError(`${kind} guide is not reviewable.`);}for(const id of input.planIds){const p=this.find(next,id),before=clone(p);p.reviewedRevision=p.revision;p.phase="ready-for-implementation";this.history(before,p,"review",`Reviewed ${p.title} Plan revision ${p.revision} without adding an approval boundary.`);}for(const kind of input.guideKinds??[]){const g=next.guides.find(x=>x.kind===kind)!;g.reviewedRevision=g.revision;g.status="ready";}next.revision+=1;next.nextActions=[this.route(next)];this.write(root,next);return clone(next)}
  confirmGuides(root:string,requests:GuideConfirmation[]):MilestonePlanningState{if(!requests.length||new Set(requests.map(r=>r.kind)).size!==requests.length)throw new ContractError("Guide confirmation requires distinct named guides.");const current=this.loadState(root),next=clone(current);for(const r of requests){text(r.participant,"participant");const g=next.guides.find(x=>x.kind===r.kind);if(!g||g.requiredPerspective!==r.perspective)throw new ContractError("Guide confirmation responsibility does not match.");if(g.status!=="ready"||g.reviewedRevision!==g.revision)throw new ContractError(`${r.kind} guide is not ready on its current revision.`);g.receipt={participant:r.participant.trim(),perspective:r.perspective,revision:g.revision};g.status="confirmed";}for(const p of next.plans){const before=clone(p);this.rephase(p,next);if(before.phase!==p.phase)this.history(before,p,"update",`Reassessed ${p.title} after required guide confirmation.`);}next.revision+=1;next.nextActions=[this.route(next)];this.write(root,next);return clone(next)}
  revalidateFoundations(root:string,input:PlanningRevalidation):MilestonePlanningState{text(input.actor.name,"actor name");text(input.actor.responsibility,"actor responsibility");const basis=text(input.basis,"revalidation basis"),canonical=canonicalWorkspaceRoot(root),current=this.readState(canonical),lifecycle=this.lifecycle(canonical),actual=this.anchors(lifecycle),changes=this.anchorChanges(current,actual);if(!changes.length)throw new ContractError("Planning foundation revisions are already current; no revalidation is needed.");if(!this.sameAnchors(input.reviewedAnchors,actual))throw new ContractError(`Revalidation must name the exact current foundation revisions: ${this.anchorDescription(actual)}.`);const next=clone(current);next.productRevision=actual.productRevision;next.engineeringRevision=actual.engineeringRevision;next.roadmapRevision=actual.roadmapRevision;next.definitionStateRevision=actual.definitionStateRevision;for(const plan of next.plans){const definition=lifecycle.definition.definitions.find(item=>item.id===plan.definitionId);if(!definition||definition.phase!=="committed")throw new ContractError(`${plan.title} no longer has a committed Definition and cannot be revalidated in Planning.`);const before=clone(plan);plan.definitionRevision=definition.revision;plan.revision+=1;plan.reviewedRevision=null;this.rephase(plan,next);this.history(before,plan,"revalidate",`Revalidated ${plan.title} against ${changes.join(", ")} after ${input.actor.name} reviewed the semantic effect: ${basis}`);}next.revision+=1;next.nextActions=[this.route(next)];this.write(canonical,next);return clone(next)}
  interrupt(root:string,planId:string,resumeAction:string):MilestonePlanningState{const current=this.loadState(root),next=clone(current),p=this.find(next,planId),before=clone(p);p.phase="paused";this.history(before,p,"pause",`Paused planning: ${text(resumeAction,"resumeAction")}`);next.revision+=1;next.session={status:"interrupted",planId,resumeAction:resumeAction.trim()};next.nextActions=[{participant:"Planning participant",action:`Resume: ${resumeAction.trim()}`,reason:"Canonical Plan state and its decision frontier are preserved."}];this.write(root,next);return clone(next)}
  async resume(root:string):Promise<MilestonePlanningState>{const current=this.loadState(root);if(current.session.status!=="interrupted"||!current.session.planId)throw new ContractError("Milestone Planning is not interrupted.");const stale=await this.detectStaleViews(root);if(stale.length)throw new ContractError(`Planning views are stale: ${stale.join(", ")}. Explicitly repair them with planning-render before resuming.`);const next=clone(current),p=this.find(next,current.session.planId),before=clone(p);this.rephase(p,next);this.history(before,p,"resume",`Resumed planning: ${current.session.resumeAction}`);next.revision+=1;next.session={status:"active",planId:p.id,resumeAction:null};next.nextActions=[this.route(next)];this.write(root,next);return clone(next)}
  renderCurrent(root:string):MilestonePlanningArtifacts{return this.write(root,this.loadState(root))}
  status(root:string):MilestonePlanningState{const s=this.loadState(root);this.write(root,s);return clone(s)}
  async detectStaleViews(root:string):Promise<string[]>{const state=this.loadState(root),expected=this.render(root,clone(state)),stale:string[]=[];for(const[path,content]of Object.entries(expected)){const m=state.generatedViews[path];if(!m||m.revision!==state.revision||m.sha256!==sha256(content)){stale.push(path);continue}try{if(await readFile(resolveInsideWorkspace(root,path),"utf8")!==content)stale.push(path)}catch{stale.push(path)}}return stale}
  private find(s:MilestonePlanningState,id:string):MilestonePlan{const p=s.plans.find(x=>x.id===id);if(!p)throw new ContractError(`Unknown Plan identity: ${id}.`);return p}
  private evaluationOrder(plan:MilestonePlan,boundary:MilestonePlan["content"]["evaluationBoundaries"][number]):number{if(boundary.evaluationType==="final-integrated-independent")return Number.MAX_SAFE_INTEGER;if(!boundary.workUnits.length)return Number.MAX_SAFE_INTEGER-1;return Math.max(...boundary.workUnits.map(key=>plan.content.workUnits.find(unit=>unit.key===key)?.order??Number.MAX_SAFE_INTEGER-1))}
  private validateCoherentEvaluationBudget(plan:MilestonePlan):void{if(plan.coherence.status!=="coherent")return;const boundaries=plan.content.evaluationBoundaries,finals=boundaries.filter(boundary=>boundary.evaluationType==="final-integrated-independent");if(finals.length!==1||!finals[0].required||boundaries.at(-1)!==finals[0])throw new ContractError("A coherent Plan update requires exactly one required final integrated independent evaluation boundary supplied last.")}
  private rephase(p:MilestonePlan,s:MilestonePlanningState):void{if(p.phase==="paused")return;const gaps=planGaps(p,s.guides);p.phase=p.coherence.status==="blocked"||p.content.unknowns.some(u=>u.blocking)||gaps.some(g=>g.includes("guide confirmation"))?"blocked":p.reviewedRevision===p.revision&&!gaps.length?"ready-for-implementation":"draft"}
  private history(before:MilestonePlan,after:MilestonePlan,operation:PlanningHistoryEntry["operation"],summary:string):void{const w:Omit<PlanningHistoryEntry,"contentHash">={version:after.history.length+1,operation,summary,beforeHash:planSnapshotHash(before),afterHash:planSnapshotHash(after),previousHash:after.historyHead};const e={...w,contentHash:planningHistoryHash(w)};after.history.push(e);after.historyHead=e.contentHash}
  private route(s:MilestonePlanningState){if(s.session.status==="interrupted")return{participant:"Planning participant",action:`Resume: ${s.session.resumeAction}`,reason:"Planning work is preserved."};const guide=s.guides.find(g=>g.status==="ready");if(guide)return{participant:guide.requiredPerspective,action:`Confirm the ${guide.kind.replaceAll("-"," ")} guide`,reason:"The durable reusable guide is ready on its current revision; no Plan approval is required."};const p=s.plans.slice().sort((a,b)=>a.order-b.order||a.id.localeCompare(b.id)).find(x=>x.phase!=="ready-for-implementation");if(p)return p.phase==="blocked"?{participant:"Responsible planning participant",action:`Resolve the blocker for ${p.title}`,reason:p.coherence.basis||planGaps(p,s.guides).join(", ")}:{participant:"Engineering",action:`Continue planning ${p.title}`,reason:planGaps(p,s.guides).join(", ")||"Review the current Plan."};return{participant:"Implementation participant",action:`Establish the implementation workspace and authority for ${s.plans[0].title}`,reason:"The Plan is ready, but no implementation or tool authority has been granted."}}
  private lifecycle(root:string){return{product:this.productEngine.loadState(root),engineering:this.productEngine.loadEngineeringStateIfPresent(root),roadmap:this.roadmapEngine.loadState(root),definition:this.definitionEngine.loadState(root),change:existsSync(resolveInsideWorkspace(root,CHANGE_MANAGEMENT_STATE_PATH))?loadChangeManagementStateIfPresent(root):undefined}}
  private readState(root:string):MilestonePlanningState{const canonical=canonicalWorkspaceRoot(root),value=JSON.parse(readFileSync(resolveInsideWorkspace(canonical,MILESTONE_PLANNING_STATE_PATH),"utf8"))as unknown;validateMilestonePlanningState(value);if(value.workspaceRoot!==canonical)throw new WorkspaceError("Planning state does not belong to the target workspace.");return value}
  private anchors(lifecycle:ReturnType<MilestonePlanningEngine["lifecycle"]>):FoundationAnchors{return{productRevision:lifecycle.product.revision,engineeringRevision:lifecycle.engineering?.revision??null,roadmapRevision:lifecycle.roadmap.revision,definitionStateRevision:lifecycle.definition.revision}}
  private anchorChanges(state:MilestonePlanningState,current:FoundationAnchors):string[]{const changes:string[]=[];if(state.productRevision!==current.productRevision)changes.push(`Product ${state.productRevision} -> ${current.productRevision}`);if(state.engineeringRevision!==current.engineeringRevision)changes.push(`Engineering ${state.engineeringRevision??"none"} -> ${current.engineeringRevision??"none"}`);if(state.roadmapRevision!==current.roadmapRevision)changes.push(`Roadmap ${state.roadmapRevision} -> ${current.roadmapRevision}`);if(state.definitionStateRevision!==current.definitionStateRevision)changes.push(`Definition state ${state.definitionStateRevision} -> ${current.definitionStateRevision}`);return changes}
  private anchorDescription(anchors:FoundationAnchors):string{return`Product ${anchors.productRevision}, Engineering ${anchors.engineeringRevision??"none"}, Roadmap ${anchors.roadmapRevision}, Definition state ${anchors.definitionStateRevision}`}
  private sameAnchors(left:FoundationAnchors|undefined,right:FoundationAnchors):boolean{return Boolean(left)&&left!.productRevision===right.productRevision&&left!.engineeringRevision===right.engineeringRevision&&left!.roadmapRevision===right.roadmapRevision&&left!.definitionStateRevision===right.definitionStateRevision}
  private assertCurrentAnchors(state:MilestonePlanningState,current:FoundationAnchors):void{const changes=this.anchorChanges(state,current);if(changes.length)throw new ContractError(`Planning foundation revisions changed: ${changes.join("; ")}. Explicit Host semantic revalidation with planning-revalidate is required before any Planning operation.`)}
  private render(root:string,state:MilestonePlanningState):MilestonePlanningArtifacts{const l=this.lifecycle(root);return renderProjectViews(l.product,this.templateRoot,l.engineering,l.roadmap,l.definition,l.change,state).milestonePlanning!}
  private write(root:string,state:MilestonePlanningState):MilestonePlanningArtifacts{validateMilestonePlanningState(state);const l=this.lifecycle(root);return writeProjectViews({workspaceRoot:root,templateRoot:this.templateRoot,productContract:this.productEngine.contract,product:l.product,engineeringContract:l.engineering?this.productEngine.engineeringContract:undefined,engineering:l.engineering,livingRoadmapContract:this.roadmapEngine.contract,livingRoadmap:l.roadmap,milestoneDefinition:l.definition,changeManagement:l.change,milestonePlanning:state,writeHooks:this.hooks}).milestonePlanning!}
  private writeStateOnly(root:string,state:MilestonePlanningState):void{validateMilestonePlanningState(state);writeFileSetInsideWorkspace(canonicalWorkspaceRoot(root),[[MILESTONE_PLANNING_STATE_PATH,`${JSON.stringify(state,null,2)}\n`]],this.hooks)}
}
