import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { dirname, join, relative, sep } from "node:path";
import { ContractError } from "./contract.js";
import { loadMilestoneDemoContract, validateMilestoneDemoState } from "./milestone-demo-contract.js";
import { demoHistoryHash, demoSnapshotHash } from "./milestone-demo-meaning.js";
import { renderMilestoneDemoArtifacts } from "./milestone-demo-render.js";
import { MILESTONE_BUILD_STATE_PATH, MilestoneBuildEngine } from "./milestone-build-engine.js";
import { renderMilestoneBuildArtifacts } from "./milestone-build-render.js";
import { CHANGE_MANAGEMENT_STATE_PATH, loadChangeManagementStateIfPresent, renderProjectViews } from "./project-views.js";
import { canonicalWorkspaceRoot, resolveInsideWorkspace, sha256, type FileSetWriteHooks, WorkspaceError, writeFileSetInsideWorkspace } from "./workspace.js";
import type { BuildCandidate, MilestoneBuild, MilestoneBuildState } from "./milestone-build-types.js";
import type { DemoActivation, DemoAuthority, DemoAuthorization, DemoBlock, DemoDecision, DemoEvidence, DemoHistoryEntry, DemoObservation, DemoResume, MilestoneDemo, MilestoneDemoArtifacts, MilestoneDemoContract, MilestoneDemoState } from "./milestone-demo-types.js";

export const MILESTONE_DEMO_STATE_PATH = ".loopy/milestone-demonstrate-and-accept/state.json";
function clone<T>(value: T): T { return structuredClone(value); }
function text(value: string, label: string): string { if (typeof value !== "string" || !/[\p{L}\p{N}]/u.test(value)) throw new ContractError(`${label} must contain letters or numbers.`); return value.trim(); }
function fingerprint(value: string, label: string): string { if (!/^[a-f0-9]{64}$/.test(value)) throw new ContractError(`${label} must be a SHA-256 fingerprint.`); return value; }
function unique(values: string[], label: string): void { if (new Set(values).size !== values.length) throw new ContractError(`${label} must be unique.`); }
type Lifecycle = ReturnType<MilestoneDemoEngine["lifecycle"]>;

export class MilestoneDemoEngine {
  readonly sourceRoot: string; readonly templateRoot: string; readonly contract: MilestoneDemoContract; readonly buildEngine: MilestoneBuildEngine; private readonly hooks: FileSetWriteHooks;
  private constructor(root: string, contract: MilestoneDemoContract, buildEngine: MilestoneBuildEngine, hooks: FileSetWriteHooks) { this.sourceRoot = root; this.templateRoot = join(root, "templates"); this.contract = contract; this.buildEngine = buildEngine; this.hooks = hooks; }
  static async create(sourceRoot: string, hooks: FileSetWriteHooks = {}): Promise<MilestoneDemoEngine> { const root = canonicalWorkspaceRoot(sourceRoot); const [contract, build] = await Promise.all([loadMilestoneDemoContract(join(root, "engine/contracts/interviews/milestone-demonstrate-and-accept.yaml")), MilestoneBuildEngine.create(root)]); return new MilestoneDemoEngine(root, contract, build, hooks); }

  async initialize(workspaceRoot: string, input: DemoActivation): Promise<MilestoneDemoState> {
    const root = canonicalWorkspaceRoot(workspaceRoot);
    if (root === this.sourceRoot) throw new WorkspaceError("Loopy source cannot become its own Human project.");
    if (existsSync(resolveInsideWorkspace(root, MILESTONE_DEMO_STATE_PATH))) throw new ContractError("Demonstrate and Accept already exists. Use demo-activate for another Milestone.");
    const stale = await this.buildEngine.detectStaleViews(root); if (stale.length) throw new ContractError(`Definition, Plan, or Proof views are stale: ${stale.join(", ")}. Render current Build views before Demonstration entry.`);
    const lifecycle = this.lifecycle(root), demo = this.createDemo(input, lifecycle); this.history(this.emptyDemo(demo), demo, "activate", `Started the exact-candidate Demo for ${demo.title}.`);
    const anchors = this.anchors(lifecycle);
    const state: MilestoneDemoState = { schemaVersion: 1, stage: "milestone-demonstrate-and-accept", workspaceClass: "human-project", workspaceRoot: root, ...anchors, revision: 0, demos: [demo], nextActions: [{ participant: "Demo participant", action: `Begin the first observable scenario for ${demo.title}`, reason: "The exact candidate and bounded Demo authority are current." }], session: { status: "active", demoId: demo.id, resumeAction: null, resumePhase: null }, generatedViews: {} };
    return this.write(root, state).state;
  }

  async activate(root: string, input: DemoActivation): Promise<MilestoneDemoState> {
    const current = this.loadState(root), lifecycle = this.lifecycle(root); const stale = await this.detectStaleViews(root); if (stale.length) throw new ContractError(`Demonstration views are stale: ${stale.join(", ")}. Render them before activating another Demo.`);
    if (current.demos.some((demo) => demo.buildId === input.buildId)) throw new ContractError("This Milestone already has a Demo record; continue it instead of creating another.");
    const next = clone(current), demo = this.createDemo(input, lifecycle); demo.order = next.demos.length; this.history(this.emptyDemo(demo), demo, "activate", `Started the exact-candidate Demo for ${demo.title}.`); next.demos.push(demo); next.session = { status: "active", demoId: demo.id, resumeAction: null, resumePhase: null }; next.revision += 1; next.nextActions = [this.route(next)]; return this.write(root, next).state;
  }

  authorize(root: string, input: DemoAuthorization): MilestoneDemoState {
    const current = this.loadState(root), next = clone(current), demo = this.find(next, input.demoId), before = clone(demo);
    if (["accepted", "correction-requested", "deferred"].includes(demo.phase)) throw new ContractError("A final Demo disposition cannot receive new authority.");
    if (input.explicitAuthorization !== true) throw new ContractError("Changed Demo authority requires explicit authorization.");
    this.assertAuthority(input.authority, demo.candidateId, demo.sourceFingerprint, demo.workspaceFingerprint); text(input.reason, "authorization reason");
    if (JSON.stringify(input.authority) === JSON.stringify(demo.authority)) throw new ContractError("Exact unchanged Demo authority is already reusable; no new authorization is needed.");
    demo.authority = clone(input.authority); demo.phase = "active"; demo.readiness = { status: "active", basis: `Explicitly reauthorized: ${input.reason.trim()}` }; demo.revision += 1; this.history(before, demo, "authorize", `Recorded explicitly changed Demo authority: ${input.reason}`); next.revision += 1; next.session = { status: "active", demoId: demo.id, resumeAction: null, resumePhase: null }; next.nextActions = [this.route(next)]; return this.write(root, next).state;
  }

  observe(root: string, input: DemoObservation): MilestoneDemoState {
    const current = this.loadState(root), next = clone(current), demo = this.find(next, input.demoId), before = clone(demo); this.assertActive(current, demo); this.assertContext(demo, input.sourceFingerprint, input.workspaceFingerprint, input.environmentFingerprint);
    if (input.productMutation !== "none") throw new ContractError("A Demo cannot mutate the product; freeze and prove a new Build Candidate instead.");
    const scenario = demo.scenarios.find((item) => item.key === input.scenario.key); if (!scenario) throw new ContractError("Unknown Demo scenario.");
    if (["accepted", "correction-requested", "deferred"].includes(demo.phase)) throw new ContractError("A final Demo disposition cannot receive new observations.");
    if (!input.scenario.status || !["planned", "in-progress", "demonstrated", "failed", "inaccessible", "unproven"].includes(input.scenario.status)) throw new ContractError("Demo scenario status is invalid.");
    if (!["planned", "in-progress"].includes(input.scenario.status)) text(input.scenario.result, "scenario result");
    unique(input.evidence.map((item) => item.key), "Demo evidence keys"); if (input.evidence.some((item) => demo.evidence.some((existing) => existing.id === item.key))) throw new ContractError("Demo evidence is append-only and keys cannot be reused.");
    const prepared = input.evidence.map((item) => this.prepareEvidence(root, demo, scenario.mode, scenario.key, item));
    this.assertTargetVerification(input, demo, [...demo.evidence, ...prepared]);
    demo.evidence.push(...prepared);
    scenario.status = input.scenario.status; scenario.result = input.scenario.result.trim(); scenario.limitations = clone(input.scenario.limitations); scenario.partialEffects = clone(input.scenario.partialEffects); scenario.evidenceIds = [...new Set([...scenario.evidenceIds, ...input.evidence.map((item) => item.key)])];
    this.validateCoverage(input.coverage, demo, this.definition(root, demo).content.acceptance); demo.coverage = clone(input.coverage); demo.whatDemonstrated = text(input.whatDemonstrated, "what was demonstrated"); demo.observedResult = text(input.observedResult, "observed result"); demo.limitations = clone(input.limitations); demo.unproven = clone(input.unproven); text(input.readiness.basis, "readiness basis"); if (!["active", "ready-for-judgment", "blocked"].includes(input.readiness.status)) throw new ContractError("Demo readiness status is invalid."); demo.readiness = clone(input.readiness);
    demo.phase = input.readiness.status === "ready-for-judgment" ? "ready-for-judgment" : input.readiness.status === "blocked" ? "blocked" : "active"; demo.revision += 1; this.history(before, demo, "observe", `Recorded the observable result for ${scenario.title}.`); next.revision += 1; next.nextActions = [this.route(next)];
    if (demo.phase === "active") { this.writeStateOnly(root, next); return clone(next); } return this.write(root, next).state;
  }

  decide(root: string, input: DemoDecision): MilestoneDemoState {
    const current = this.loadState(root), next = clone(current), demo = this.find(next, input.demoId), before = clone(demo); this.assertContext(demo, input.sourceFingerprint, input.workspaceFingerprint, input.environmentFingerprint);
    if (demo.decision !== null || ["accepted", "correction-requested", "deferred"].includes(demo.phase)) throw new ContractError("The Demo already has a final human disposition.");
    if (current.session.status !== "active" || current.session.demoId !== demo.id) throw new ContractError("Judgment or advisory input requires the exact active Demo session.");
    for (const field of ["participant", "perspectiveContext", "naturalLanguageIntent", "reason"] as const) text(input[field], `decision ${field}`);
    if (input.reviewedRevision !== demo.revision || input.candidateId !== demo.candidateId) throw new ContractError("Human judgment must name the exact current Demo revision and demonstrated candidate.");
    if (!["accept", "request-correction", "defer"].includes(input.decision)) throw new ContractError("Human Demo decision is invalid.");
    if (input.actorKind !== "human") {
      if (!["simulated-participant", "proxy-ai"].includes(input.actorKind) || input.personalJudgment !== false) throw new ContractError("Simulated participant or proxy AI input cannot claim personal human judgment.");
      demo.advisoryInputs.push({ participant: input.participant.trim(), actorKind: input.actorKind, perspectiveContext: input.perspectiveContext.trim(), naturalLanguageInput: input.naturalLanguageIntent.trim(), recommendation: input.decision, personalJudgment: false, demoRevision: demo.revision });
      demo.revision += 1; this.history(before, demo, "assessment", `Recorded ${input.actorKind} input from ${input.participant}; no human disposition or completion followed.`); next.revision += 1; next.nextActions = [this.route(next)]; return this.write(root, next).state;
    }
    if (input.personalJudgment !== true) throw new ContractError("A genuine human decision must explicitly represent that person's own judgment.");
    const definition = this.definition(root, demo); let receipt;
    if (input.decision === "accept") {
      if (demo.phase !== "ready-for-judgment") throw new ContractError("Acceptance requires a Demo ready for human judgment.");
      if (input.acceptedOutcome !== definition.content.outcome || JSON.stringify(input.acceptedBoundary ?? []) !== JSON.stringify(definition.content.acceptance)) throw new ContractError("Acceptance must identify the exact committed outcome and acceptance boundary.");
      if (demo.coverage.length !== definition.content.acceptance.length || definition.content.acceptance.some((criterion) => !demo.coverage.some((row) => row.criterion === criterion && row.status === "demonstrated" && row.evidenceIds.length))) throw new ContractError("Acceptance requires every committed criterion to be demonstrably evidenced for this exact candidate.");
      demo.phase = "accepted"; receipt = this.receipt(input, demo, definition.content.outcome, definition.content.acceptance, null, null);
    } else if (input.decision === "request-correction") {
      if (!input.correctionRoute || !["build", "planning", "change-management"].includes(input.correctionRoute)) throw new ContractError("A correction request must route to Build, Planning, or Change Management.");
      demo.phase = "correction-requested"; receipt = this.receipt(input, demo, null, [], input.correctionRoute, null);
    } else {
      text(input.revisitWhen ?? "", "deferral revisit condition"); demo.phase = "deferred"; receipt = this.receipt(input, demo, null, [], null, input.revisitWhen!.trim());
    }
    demo.decision = receipt; demo.revision += 1; this.history(before, demo, input.decision === "accept" ? "accept" : input.decision === "request-correction" ? "correction" : "defer", `${input.participant} ${input.decision.replaceAll("-", " ")} for the exact demonstrated candidate.`); next.revision += 1; next.nextActions = [this.route(next)]; return this.write(root, next).state;
  }

  block(root: string, input: DemoBlock): MilestoneDemoState { const current = this.loadState(root), next = clone(current), demo = this.find(next, input.demoId), before = clone(demo); if (["accepted", "correction-requested", "deferred"].includes(demo.phase)) throw new ContractError("A final Demo disposition cannot be replaced by a blocker."); text(input.reason, "block reason"); text(input.nextParticipant, "next participant"); text(input.nextAction, "next action"); demo.phase = "blocked"; demo.readiness = { status: "blocked", basis: input.reason.trim() }; demo.revision += 1; this.history(before, demo, "block", `Blocked Demonstration: ${input.reason}`); next.revision += 1; next.nextActions = [{ participant: input.nextParticipant.trim(), action: input.nextAction.trim(), reason: input.reason.trim() }]; return this.write(root, next).state; }
  interrupt(root: string, demoId: string, resumeAction: string): MilestoneDemoState { const current = this.loadState(root), next = clone(current), demo = this.find(next, demoId), before = clone(demo); if (!["preparing", "active", "ready-for-judgment"].includes(demo.phase)) throw new ContractError("Only an active Demo can be paused."); const prior = demo.phase as "preparing" | "active" | "ready-for-judgment"; demo.phase = "paused"; demo.revision += 1; this.history(before, demo, "pause", `Paused Demonstration: ${text(resumeAction, "resume action")}`); next.revision += 1; next.session = { status: "interrupted", demoId, resumeAction: resumeAction.trim(), resumePhase: prior }; next.nextActions = [this.route(next)]; return this.write(root, next).state; }
  async resume(root: string, input: DemoResume): Promise<MilestoneDemoState> { const current = this.loadState(root); if (current.session.status !== "interrupted" || !current.session.demoId || !current.session.resumePhase) throw new ContractError("Demonstration is not interrupted."); const stale = await this.detectStaleViews(root); if (stale.length) throw new ContractError(`Demo views are stale: ${stale.join(", ")}. Explicitly repair them with demo-render before resuming.`); const next = clone(current), demo = this.find(next, current.session.demoId), before = clone(demo); this.assertContext(demo, input.sourceFingerprint, input.workspaceFingerprint, input.environmentFingerprint); unique(input.restartScenarioKeys, "restart scenario keys"); const required = demo.scenarios.filter((scenario) => scenario.status === "in-progress" && !scenario.replayable).map((scenario) => scenario.key); if (required.some((key) => !input.restartScenarioKeys.includes(key)) || input.restartScenarioKeys.some((key) => !required.includes(key))) throw new ContractError("Every interrupted non-replayable scenario, and only those scenarios, must be explicitly restarted."); for (const key of required) { const scenario = demo.scenarios.find((item) => item.key === key)!; scenario.status = "planned"; scenario.result = "Restart required after interruption; prior partial evidence remains preserved."; } demo.phase = current.session.resumePhase; demo.revision += 1; this.history(before, demo, "resume", `Resumed Demonstration: ${current.session.resumeAction}`); next.revision += 1; next.session = { status: "active", demoId: demo.id, resumeAction: null, resumePhase: null }; next.nextActions = [this.route(next)]; return this.write(root, next).state; }
  renderCurrent(root: string): MilestoneDemoArtifacts { return this.write(root, this.loadState(root)).artifacts; }
  status(root: string): MilestoneDemoState { return this.write(root, this.loadState(root)).state; }
  async detectStaleViews(root: string): Promise<string[]> { const state = this.loadState(root), expected = this.render(root, clone(state)), stale: string[] = []; for (const [path, content] of Object.entries(expected)) { const meta = state.generatedViews[path]; if (!meta || meta.revision !== state.revision || meta.sha256 !== sha256(content)) { stale.push(path); continue; } try { if (await readFile(resolveInsideWorkspace(root, path), "utf8") !== content) stale.push(path); } catch { stale.push(path); } } return stale; }
  loadState(root: string): MilestoneDemoState { const state = this.readState(root), lifecycle = this.lifecycle(root); this.assertCurrent(state, lifecycle); return state; }

  private createDemo(input: DemoActivation, lifecycle: Lifecycle): MilestoneDemo {
    const build = lifecycle.build.builds.find((item) => item.id === input.buildId); if (!build || build.phase !== "ready-for-demonstration") throw new ContractError("Demo entry requires one explicitly named Milestone Build ready for Demonstration.");
    const candidate = build.candidates.find((item) => item.id === input.candidateId); if (!candidate || candidate.kind !== "integrated" || candidate.id !== build.candidates.at(-1)?.id) throw new ContractError("Demo entry requires the exact current integrated Milestone Build Candidate.");
    const final = build.evaluations.find((item) => item.candidateId === candidate.id && item.verdict === "pass" && build.evaluationBudget.find((boundary) => boundary.checkpoint === item.checkpoint)?.evaluationType === "final-integrated-independent"); if (!final) throw new ContractError("Demo entry requires the exact candidate's independent final integrated PASS.");
    unique(input.modes, "Demo modes"); if (!input.modes.length || input.modes.some((mode) => !["human-guided", "ai-operated-recorded"].includes(mode))) throw new ContractError("Demo entry requires a supported human-guided or AI-operated recorded mode.");
    for (const field of ["surface", "summary", "basis"] as const) text(input.method[field], `method ${field}`); this.assertAuthority(input.authority, candidate.id, candidate.sourceFingerprint, candidate.workspaceFingerprint);
    unique(input.scenarios.map((scenario) => scenario.key), "scenario keys"); unique(input.scenarios.map((scenario) => String(scenario.order)), "scenario order"); if (!input.scenarios.length) throw new ContractError("Demo entry requires at least one observable scenario.");
    for (const scenario of input.scenarios) { for (const field of ["key", "title", "whatToObserve"] as const) text(scenario[field], `scenario ${field}`); if (!input.modes.includes(scenario.mode) || !Number.isInteger(scenario.order) || scenario.order < 1 || typeof scenario.replayable !== "boolean") throw new ContractError("Each scenario requires an authorized mode, stable positive order, and replayability declaration."); }
    return { id: `demo-${lifecycle.build.builds.indexOf(build) + 1}`, buildId: build.id, definitionId: build.definitionId, planId: build.planId, candidateId: candidate.id, title: build.title, artifactPath: join(dirname(build.artifactPath), "Demo.md"), order: lifecycle.build.builds.indexOf(build), definitionRevision: build.definitionRevision, planRevision: build.planRevision, buildRevision: build.revision, candidateSequence: candidate.sequence, sourceFingerprint: candidate.sourceFingerprint, workspaceFingerprint: candidate.workspaceFingerprint, phase: "preparing", revision: 0, modes: clone(input.modes), method: clone(input.method), authority: clone(input.authority), scenarios: input.scenarios.map((scenario) => ({ ...clone(scenario), status: "planned", result: "", evidenceIds: [], limitations: [], partialEffects: [] })), coverage: [], whatDemonstrated: "", observedResult: "", limitations: [], unproven: [], readiness: { status: "active", basis: "The exact candidate, anchors, method, authority, and expected operated target are ready for verification." }, evidence: [], advisoryInputs: [], decision: null, history: [], historyHead: null };
  }
  private assertAuthority(authority: DemoAuthority, candidateId: string, source: string, workspace: string): void { for (const field of ["participant", "perspectiveContext"] as const) text(authority[field], `authority ${field}`); if (authority.candidateId !== candidateId || fingerprint(authority.sourceFingerprint, "authority source fingerprint") !== source || fingerprint(authority.workspaceFingerprint, "authority workspace fingerprint") !== workspace) throw new ContractError("Demo authority must bind the exact Build Candidate, source, and workspace."); text(authority.environment.name, "environment name"); fingerprint(authority.environment.fingerprint, "environment fingerprint"); text(authority.target.name, "target name"); fingerprint(authority.target.fingerprint, "target fingerprint"); text(authority.target.verificationBasis, "target verification basis"); for (const field of ["tools", "actions", "scope", "externalSystems", "externalEffects", "consequentialPermissions", "accessibilityNeeds"] as const) { unique(authority[field], `authority ${field}`); authority[field].forEach((item) => text(item, `authority ${field}`)); } if (!authority.actions.length || !authority.scope.length || authority.productMutationAllowed !== false) throw new ContractError("Demo authority requires bounded actions and scope and can never authorize product mutation."); if (authority.externalEffects.length && !authority.consequentialPermissions.length) throw new ContractError("External effects require explicit consequential permission."); const forbidden = [...authority.actions, ...authority.scope].join(" "); if (/\b(push|merge|tag|deploy|publish|release|distribute|edit source|modify product)\b/i.test(forbidden)) throw new ContractError("Release, source mutation, deployment, publication, and distribution are outside Demo authority."); }
  private prepareEvidence(root: string, demo: MilestoneDemo, scenarioMode: MilestoneDemo["scenarios"][number]["mode"], scenarioKey: string, item: DemoObservation["evidence"][number]): DemoEvidence {
    for (const field of ["key", "summary", "reference", "action"] as const) text(item[field], `evidence ${field}`);
    fingerprint(item.fingerprint, "evidence fingerprint");
    if (!["command", "output", "log", "screenshot", "recording", "observation", "link"].includes(item.kind) || !["workspace-file", "durable-uri", "ephemeral"].includes(item.referenceKind) || !["passed", "failed", "partial", "unproven"].includes(item.result) || !["human", "host-ai"].includes(item.operator)) throw new ContractError("Demo evidence kind, reference kind, result, or operator is invalid.");
    if ((scenarioMode === "human-guided" && item.operator !== "human") || (scenarioMode === "ai-operated-recorded" && item.operator !== "host-ai")) throw new ContractError("Demo evidence operator must match the scenario mode.");
    if (!demo.authority.actions.includes(item.action) || (item.tool !== null && !demo.authority.tools.includes(item.tool)) || (item.externalSystem !== null && !demo.authority.externalSystems.includes(item.externalSystem))) throw new ContractError("Demo evidence exceeds the exact authorized action, tool, or external-system scope.");
    let reference = item.reference.trim(), accessibility: DemoEvidence["accessibility"] = "inspectable";
    if (item.referenceKind === "workspace-file") {
      if (/^[a-z][a-z0-9+.-]*:/i.test(reference)) throw new ContractError("Workspace evidence must use a workspace-relative file path.");
      const file = resolveInsideWorkspace(root, reference);
      if (!existsSync(file)) throw new ContractError("Workspace-contained Demo evidence does not exist.");
      const actual = createHash("sha256").update(readFileSync(file)).digest("hex");
      if (actual !== item.fingerprint) throw new ContractError("Workspace-contained Demo evidence fingerprint does not match the referenced file.");
      reference = relative(dirname(demo.artifactPath), reference).split(sep).join("/");
    } else if (item.referenceKind === "durable-uri") {
      if (!/^https:\/\/[^\s]+$/i.test(reference)) throw new ContractError("Durable Demo URI evidence must use an independently resolvable HTTPS reference.");
    } else {
      accessibility = "inaccessible";
    }
    return { id: item.key, kind: item.kind, summary: item.summary.trim(), reference, referenceKind: item.referenceKind, accessibility, fingerprint: item.fingerprint, result: item.result, operator: item.operator, tool: item.tool, action: item.action.trim(), externalSystem: item.externalSystem, scenarioKey, candidateId: demo.candidateId, environmentFingerprint: demo.authority.environment.fingerprint, targetFingerprint: demo.authority.target.fingerprint };
  }
  private assertTargetVerification(input: DemoObservation, demo: MilestoneDemo, evidence: DemoEvidence[]): void {
    const expected = fingerprint(input.targetVerification.expectedTargetFingerprint, "expected target fingerprint"), observed = fingerprint(input.targetVerification.observedTargetFingerprint, "observed target fingerprint"); text(input.targetVerification.method, "target verification method"); unique(input.targetVerification.evidenceIds, "target verification evidence");
    if (expected !== demo.authority.target.fingerprint || observed !== expected) throw new ContractError("Demo target mismatch: the operated target does not represent the authorized exact candidate and environment. Treat this as a Demo environment/target failure; retry, reauthorize, or block rather than routing to Build without product evidence.");
    if (!input.targetVerification.evidenceIds.length) throw new ContractError("Target identity verification requires independently inspectable evidence before observation.");
    const records = input.targetVerification.evidenceIds.map((id) => evidence.find((item) => item.id === id));
    if (records.some((item) => !item || item.result !== "passed" || item.accessibility !== "inspectable" || item.targetFingerprint !== expected || item.environmentFingerprint !== demo.authority.environment.fingerprint)) throw new ContractError("Target identity verification requires passing independently inspectable evidence bound to the exact target and environment.");
  }
  private validateCoverage(rows: DemoObservation["coverage"], demo: MilestoneDemo, criteria: string[]): void { unique(rows.map((row) => row.criterion), "coverage criteria"); for (const row of rows) { if (!criteria.includes(row.criterion)) throw new ContractError("Demo coverage cannot exceed the committed acceptance boundary."); if (!["demonstrated", "failed", "deferred", "inaccessible", "unproven"].includes(row.status)) throw new ContractError("Demo coverage status is invalid."); if (row.scenarioKeys.some((key) => !demo.scenarios.some((scenario) => scenario.key === key))) throw new ContractError("Demo coverage must reference known scenarios."); const evidence = row.evidenceIds.map((id) => demo.evidence.find((item) => item.id === id)); if (evidence.some((item) => !item)) throw new ContractError("Demo coverage must reference Demo evidence."); if (row.status === "demonstrated" && (!row.evidenceIds.length || evidence.some((item) => item!.result !== "passed" || item!.accessibility !== "inspectable"))) throw new ContractError("Demonstrated coverage requires only passing independently inspectable evidence."); } }
  private receipt(input: DemoDecision, demo: MilestoneDemo, acceptedOutcome: string | null, acceptedBoundary: string[], correctionRoute: "build" | "planning" | "change-management" | null, revisitWhen: string | null) { return { human: input.participant.trim(), perspectiveContext: input.perspectiveContext.trim(), naturalLanguageIntent: input.naturalLanguageIntent.trim(), personalJudgment: true as const, candidateId: demo.candidateId, demoRevision: demo.revision, decision: input.decision, acceptedOutcome, acceptedBoundary: clone(acceptedBoundary), correctionRoute, reason: input.reason.trim(), revisitWhen }; }
  private assertContext(demo: MilestoneDemo, source: string, workspace: string, environment: string): void { if (fingerprint(source, "source fingerprint") !== demo.sourceFingerprint || fingerprint(workspace, "workspace fingerprint") !== demo.workspaceFingerprint || fingerprint(environment, "environment fingerprint") !== demo.authority.environment.fingerprint) throw new ContractError("Candidate, source, workspace, or Demo environment drift invalidates this Demo; route to the earliest affected stage."); }
  private assertActive(state: MilestoneDemoState, demo: MilestoneDemo): void { if (state.session.status !== "active" || state.session.demoId !== demo.id || !["preparing", "active", "ready-for-judgment", "blocked"].includes(demo.phase)) throw new ContractError("Observation requires the exact active Demo session."); }
  private definition(root: string, demo: MilestoneDemo) { const value = this.buildEngine.definitionEngine.loadState(root).definitions.find((item) => item.id === demo.definitionId); if (!value) throw new ContractError("Demo Definition no longer exists."); return value; }
  private find(state: MilestoneDemoState, id: string): MilestoneDemo { const value = state.demos.find((item) => item.id === id); if (!value) throw new ContractError(`Unknown Demo identity: ${id}.`); return value; }
  private emptyDemo(demo: MilestoneDemo): MilestoneDemo { return { ...clone(demo), history: [], historyHead: null, revision: 0 }; }
  private history(before: MilestoneDemo, after: MilestoneDemo, operation: DemoHistoryEntry["operation"], summary: string): void { const without: Omit<DemoHistoryEntry, "contentHash"> = { version: after.history.length + 1, operation, summary, beforeHash: demoSnapshotHash(before), afterHash: demoSnapshotHash(after), previousHash: after.historyHead }; const entry = { ...without, contentHash: demoHistoryHash(without) }; after.history.push(entry); after.historyHead = entry.contentHash; }
  private lifecycle(root: string) { const build = this.buildEngine.loadState(root); const product = this.buildEngine.productEngine.loadState(root), engineering = this.buildEngine.productEngine.loadEngineeringStateIfPresent(root), roadmap = this.buildEngine.roadmapEngine.loadState(root), definition = this.buildEngine.definitionEngine.loadState(root), planning = this.buildEngine.planningEngine.loadState(root), change = existsSync(resolveInsideWorkspace(root, CHANGE_MANAGEMENT_STATE_PATH)) ? loadChangeManagementStateIfPresent(root) : undefined; return { product, engineering, roadmap, definition, planning, change, build }; }
  private anchors(lifecycle: Lifecycle) { return { productRevision: lifecycle.product.revision, engineeringRevision: lifecycle.engineering?.revision ?? null, roadmapRevision: lifecycle.roadmap.revision, definitionStateRevision: lifecycle.definition.revision, planningStateRevision: lifecycle.planning.revision, buildStateRevision: lifecycle.build.revision, changeRevision: lifecycle.change?.revision ?? null }; }
  private assertCurrent(state: MilestoneDemoState, lifecycle: Lifecycle): void { const actual = this.anchors(lifecycle), captured = { productRevision: state.productRevision, engineeringRevision: state.engineeringRevision, roadmapRevision: state.roadmapRevision, definitionStateRevision: state.definitionStateRevision, planningStateRevision: state.planningStateRevision, buildStateRevision: state.buildStateRevision, changeRevision: state.changeRevision }; if (JSON.stringify(actual) !== JSON.stringify(captured)) throw new ContractError("Demo foundations or Build state changed; the exact Demo is invalid and must route to the earliest affected stage."); for (const demo of state.demos) { const build = lifecycle.build.builds.find((item) => item.id === demo.buildId), candidate = build?.candidates.find((item) => item.id === demo.candidateId); if (!build || !candidate || candidate.sourceFingerprint !== demo.sourceFingerprint || candidate.workspaceFingerprint !== demo.workspaceFingerprint || build.definitionRevision !== demo.definitionRevision || build.planRevision !== demo.planRevision || build.revision !== demo.buildRevision) throw new ContractError("Demo candidate, source, workspace, Definition, Plan, or Proof anchor changed; the Demo is invalid."); } }
  private route(state: MilestoneDemoState) { if (state.session.status === "interrupted") return { participant: "Demo participant", action: `Resume: ${state.session.resumeAction}`, reason: "Canonical Demo observations and exact authority remain preserved." }; const demo = state.demos.slice().sort((a, b) => a.order - b.order || a.id.localeCompare(b.id)).find((item) => !["accepted", "correction-requested", "deferred"].includes(item.phase)) ?? state.demos.at(-1)!; if (demo.phase === "accepted") return { participant: "Human", action: `Choose the next Roadmap or separately authorized Release-preparation step after ${demo.title}`, reason: "The Milestone is Complete but unreleased; no Release, publication, or deployment authority follows." }; if (demo.phase === "correction-requested") { const route = demo.decision!.correctionRoute!; return { participant: route === "build" ? "Build participant" : route === "planning" ? "Engineering participant" : "Responsible participant", action: `Continue ${demo.title} through ${route === "build" ? "Build and Prove" : route === "planning" ? "Milestone Planning" : "Change Management"}`, reason: demo.decision!.reason }; } if (demo.phase === "deferred") return { participant: "Human", action: `Revisit ${demo.title} when ${demo.decision!.revisitWhen}`, reason: demo.decision!.reason }; if (demo.phase === "ready-for-judgment") return { participant: "Authorized human", action: `Judge the exact demonstrated outcome for ${demo.title}`, reason: "Accept, request correction, or defer in ordinary language; a proxy AI cannot decide." }; if (demo.phase === "blocked" || demo.phase === "paused") return { participant: "Human", action: `Resolve or resume the Demo for ${demo.title}`, reason: demo.readiness.basis }; const scenario = demo.scenarios.find((item) => !["demonstrated", "failed", "inaccessible", "unproven"].includes(item.status)); return { participant: "Demo participant", action: `Demonstrate ${scenario?.title ?? demo.title}`, reason: "Use only the exact candidate, environment, actions, tools, and effects in the current Demo authority." }; }
  private readState(root: string): MilestoneDemoState { const canonical = canonicalWorkspaceRoot(root), value = JSON.parse(readFileSync(resolveInsideWorkspace(canonical, MILESTONE_DEMO_STATE_PATH), "utf8")) as unknown; validateMilestoneDemoState(value); if (value.workspaceRoot !== canonical) throw new WorkspaceError("Demonstration state does not belong to the target workspace."); return value; }
  private render(root: string, state: MilestoneDemoState): MilestoneDemoArtifacts { const lifecycle = this.lifecycle(root); const project = renderProjectViews(lifecycle.product, this.templateRoot, lifecycle.engineering, lifecycle.roadmap, lifecycle.definition, lifecycle.change, lifecycle.planning).milestonePlanning!; const build = renderMilestoneBuildArtifacts(project, lifecycle.build, lifecycle.definition, lifecycle.planning, this.templateRoot); return renderMilestoneDemoArtifacts(build, state, lifecycle.definition, lifecycle.build, this.templateRoot); }
  private write(root: string, state: MilestoneDemoState): { state: MilestoneDemoState; artifacts: MilestoneDemoArtifacts } { validateMilestoneDemoState(state); const artifacts = this.render(root, state); state.generatedViews = {}; for (const [path, content] of Object.entries(artifacts)) state.generatedViews[path] = { revision: state.revision, sha256: sha256(content) }; validateMilestoneDemoState(state); writeFileSetInsideWorkspace(canonicalWorkspaceRoot(root), [[MILESTONE_DEMO_STATE_PATH, `${JSON.stringify(state, null, 2)}\n`], ...Object.entries(artifacts)], this.hooks); return { state: clone(state), artifacts }; }
  private writeStateOnly(root: string, state: MilestoneDemoState): void { validateMilestoneDemoState(state); writeFileSetInsideWorkspace(canonicalWorkspaceRoot(root), [[MILESTONE_DEMO_STATE_PATH, `${JSON.stringify(state, null, 2)}\n`]], this.hooks); }
}
