import { readFile } from "node:fs/promises";
import { parse } from "yaml";
import { ContractError } from "./contract.js";
import { demoHistoryHash, demoSnapshotHash } from "./milestone-demo-meaning.js";
import { DEMO_COVERAGE_STATUSES, DEMO_MODES, DEMO_PHASES, DEMO_SCENARIO_STATUSES, type MilestoneDemoContract, type MilestoneDemoState } from "./milestone-demo-types.js";

function object(value: unknown, label: string): asserts value is Record<string, any> { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new ContractError(`${label} must be an object.`); }
function text(value: unknown, label: string): asserts value is string { if (typeof value !== "string" || !/[\p{L}\p{N}]/u.test(value)) throw new ContractError(`${label} must contain letters or numbers.`); }
function texts(value: unknown, label: string): asserts value is string[] { if (!Array.isArray(value)) throw new ContractError(`${label} must be an array.`); value.forEach((item, index) => text(item, `${label}[${index}]`)); }
function integer(value: unknown, label: string): asserts value is number { if (!Number.isInteger(value) || (value as number) < 0) throw new ContractError(`${label} must be a nonnegative integer.`); }
function unique(values: string[], label: string): void { if (new Set(values).size !== values.length) throw new ContractError(`${label} must be unique.`); }
function fingerprint(value: unknown, label: string): void { if (typeof value !== "string" || !/^[a-f0-9]{64}$/.test(value)) throw new ContractError(`${label} must be a SHA-256 fingerprint.`); }

export async function loadMilestoneDemoContract(path: string): Promise<MilestoneDemoContract> {
  const value = parse(await readFile(path, "utf8")) as Record<string, unknown>;
  object(value, "Demonstrate and Accept contract");
  const fields = ["version", "id", "exact_ready_candidate_required", "current_definition_plan_proof_anchors_required", "verified_demo_target_required", "durable_evidence_references_required", "human_guided_and_recorded_modes", "surface_appropriate_method_owned_by_host_ai", "exact_authority_reuse_only", "product_mutation_forbidden", "proxy_ai_cannot_accept", "simulated_input_is_not_human_judgment", "flexible_human_perspective", "natural_language_human_judgment", "evidence_proof_demo_acceptance_distinct", "atomic_complete_unreleased_transition", "append_only_hash_linked_history", "ordinary_updates_may_defer_publication", "rejected_operations_do_not_mutate", "exactly_one_next_action", "release_authority_out_of_scope"];
  if (Object.keys(value).some((key) => !fields.includes(key)) || value.version !== 1 || value.id !== "milestone-demonstrate-and-accept" || fields.slice(2).some((field) => value[field] !== true)) throw new ContractError("Demonstrate and Accept contract does not preserve the approved boundary.");
  return value as unknown as MilestoneDemoContract;
}

export function validateMilestoneDemoState(value: unknown): asserts value is MilestoneDemoState {
  object(value, "Demonstration state");
  if (value.schemaVersion !== 1 || value.stage !== "milestone-demonstrate-and-accept" || value.workspaceClass !== "human-project") throw new ContractError("Demonstration state has an invalid schema or workspace class.");
  text(value.workspaceRoot, "workspaceRoot");
  for (const field of ["productRevision", "roadmapRevision", "definitionStateRevision", "planningStateRevision", "buildStateRevision", "revision"]) integer(value[field], field);
  if (value.engineeringRevision !== null) integer(value.engineeringRevision, "engineeringRevision");
  if (value.changeRevision !== null) integer(value.changeRevision, "changeRevision");
  if (!Array.isArray(value.demos) || !value.demos.length) throw new ContractError("Demonstration state requires at least one Milestone Demo.");
  unique(value.demos.map((demo: any) => demo.id), "Demo identities"); unique(value.demos.map((demo: any) => demo.buildId), "Demo Build identities"); unique(value.demos.map((demo: any) => demo.artifactPath), "Demo artifact paths");
  for (const demo of value.demos) {
    object(demo, "Milestone Demo");
    for (const field of ["id", "buildId", "definitionId", "planId", "candidateId", "title", "artifactPath", "whatDemonstrated", "observedResult"]) { if (["whatDemonstrated", "observedResult"].includes(field) && demo[field] === "") continue; text(demo[field], `Demo ${field}`); }
    for (const field of ["order", "definitionRevision", "planRevision", "buildRevision", "candidateSequence", "revision"]) integer(demo[field], field);
    fingerprint(demo.sourceFingerprint, "Demo source fingerprint"); fingerprint(demo.workspaceFingerprint, "Demo workspace fingerprint");
    if (!DEMO_PHASES.includes(demo.phase)) throw new ContractError("Demo phase is invalid.");
    if (!Array.isArray(demo.modes) || !demo.modes.length || demo.modes.some((mode: any) => !DEMO_MODES.includes(mode))) throw new ContractError("Demo requires a supported mode."); unique(demo.modes, "Demo modes");
    object(demo.method, "Demo method"); for (const field of ["surface", "summary", "basis"]) text(demo.method[field], `method ${field}`);
    object(demo.authority, "Demo authority"); for (const field of ["participant", "perspectiveContext", "candidateId", "sourceFingerprint", "workspaceFingerprint"]) text(demo.authority[field], `authority ${field}`);
    fingerprint(demo.authority.sourceFingerprint, "authority source fingerprint"); fingerprint(demo.authority.workspaceFingerprint, "authority workspace fingerprint");
    if (demo.authority.candidateId !== demo.candidateId || demo.authority.sourceFingerprint !== demo.sourceFingerprint || demo.authority.workspaceFingerprint !== demo.workspaceFingerprint) throw new ContractError("Demo authority must match the exact candidate, source, and workspace.");
    object(demo.authority.environment, "Demo environment"); text(demo.authority.environment.name, "environment name"); fingerprint(demo.authority.environment.fingerprint, "environment fingerprint");
    object(demo.authority.target, "Demo target"); text(demo.authority.target.name, "target name"); fingerprint(demo.authority.target.fingerprint, "target fingerprint"); text(demo.authority.target.verificationBasis, "target verification basis");
    for (const field of ["tools", "actions", "scope", "externalSystems", "externalEffects", "consequentialPermissions", "accessibilityNeeds"]) texts(demo.authority[field], `authority ${field}`);
    if (!demo.authority.actions.length || !demo.authority.scope.length || demo.authority.productMutationAllowed !== false) throw new ContractError("Demo authority requires bounded actions and scope and cannot authorize product mutation.");
    if (demo.authority.externalEffects.length && !demo.authority.consequentialPermissions.length) throw new ContractError("External Demo effects require explicit consequential permission.");
    if (!Array.isArray(demo.scenarios) || !demo.scenarios.length) throw new ContractError("Demo requires at least one observable scenario."); unique(demo.scenarios.map((scenario: any) => scenario.key), "Demo scenario keys"); unique(demo.scenarios.map((scenario: any) => String(scenario.order)), "Demo scenario order");
    for (const scenario of demo.scenarios) { for (const field of ["key", "title", "whatToObserve"]) text(scenario[field], `scenario ${field}`); if (!demo.modes.includes(scenario.mode) || !DEMO_MODES.includes(scenario.mode) || !DEMO_SCENARIO_STATUSES.includes(scenario.status) || typeof scenario.replayable !== "boolean" || !Number.isInteger(scenario.order) || scenario.order < 1) throw new ContractError("Demo scenario mode, status, replayability, or order is invalid."); if (typeof scenario.result !== "string") throw new ContractError("Demo scenario result must be text."); texts(scenario.evidenceIds, "scenario evidence"); texts(scenario.limitations, "scenario limitations"); texts(scenario.partialEffects, "scenario partial effects"); }
    if (!Array.isArray(demo.coverage)) throw new ContractError("Demo coverage must be an array."); unique(demo.coverage.map((row: any) => row.criterion), "Demo coverage criteria");
    for (const row of demo.coverage) { text(row.criterion, "coverage criterion"); if (!DEMO_COVERAGE_STATUSES.includes(row.status)) throw new ContractError("Demo coverage status is invalid."); texts(row.scenarioKeys, "coverage scenarios"); texts(row.evidenceIds, "coverage evidence"); if (typeof row.note !== "string") throw new ContractError("Coverage note must be text."); if (row.scenarioKeys.some((key: string) => !demo.scenarios.some((scenario: any) => scenario.key === key))) throw new ContractError("Coverage references an unknown Demo scenario."); }
    texts(demo.limitations, "Demo limitations"); texts(demo.unproven, "Demo unproven behavior");
    object(demo.readiness, "Demo readiness"); if (!["active", "ready-for-judgment", "blocked"].includes(demo.readiness.status)) throw new ContractError("Demo readiness status is invalid."); text(demo.readiness.basis, "Demo readiness basis");
    if (!Array.isArray(demo.evidence)) throw new ContractError("Demo evidence must be an array."); unique(demo.evidence.map((item: any) => item.id), "Demo evidence identities");
    for (const item of demo.evidence) { for (const field of ["id", "kind", "summary", "reference", "referenceKind", "accessibility", "result", "operator", "action", "scenarioKey", "candidateId"]) text(item[field], `evidence ${field}`); if (!["command", "output", "log", "screenshot", "recording", "observation", "link"].includes(item.kind) || !["workspace-file", "durable-uri", "ephemeral"].includes(item.referenceKind) || !["inspectable", "inaccessible"].includes(item.accessibility) || !["passed", "failed", "partial", "unproven"].includes(item.result) || !["human", "host-ai"].includes(item.operator)) throw new ContractError("Demo evidence kind, reference, accessibility, result, or operator is invalid."); if ((item.referenceKind === "ephemeral") !== (item.accessibility === "inaccessible")) throw new ContractError("Ephemeral Demo evidence must remain visibly inaccessible."); fingerprint(item.fingerprint, "evidence fingerprint"); if (item.tool !== null) text(item.tool, "evidence tool"); if (item.externalSystem !== null) text(item.externalSystem, "evidence external system"); fingerprint(item.environmentFingerprint, "evidence environment fingerprint"); fingerprint(item.targetFingerprint, "evidence target fingerprint"); if (item.candidateId !== demo.candidateId || item.targetFingerprint !== demo.authority.target.fingerprint || !demo.scenarios.some((scenario: any) => scenario.key === item.scenarioKey)) throw new ContractError("Demo evidence must match the exact candidate, target, and a known scenario."); }
    for (const scenario of demo.scenarios) if (scenario.evidenceIds.some((id: string) => !demo.evidence.some((item: any) => item.id === id))) throw new ContractError("A Demo scenario references unknown evidence.");
    for (const row of demo.coverage) { const records = row.evidenceIds.map((id: string) => demo.evidence.find((item: any) => item.id === id)); if (records.some((item: any) => !item)) throw new ContractError("Coverage references unknown Demo evidence."); if (row.status === "demonstrated" && (!row.evidenceIds.length || records.some((item: any) => item.result !== "passed" || item.accessibility !== "inspectable"))) throw new ContractError("Demonstrated coverage requires passing independently inspectable evidence."); }
    if (!Array.isArray(demo.advisoryInputs)) throw new ContractError("Demo advisory inputs must be an array.");
    for (const input of demo.advisoryInputs) { object(input, "Demo advisory input"); for (const field of ["participant", "actorKind", "perspectiveContext", "naturalLanguageInput", "recommendation"]) text(input[field], `advisory ${field}`); integer(input.demoRevision, "advisory Demo revision"); if (!["simulated-participant", "proxy-ai"].includes(input.actorKind) || input.personalJudgment !== false || !["accept", "request-correction", "defer"].includes(input.recommendation)) throw new ContractError("Advisory input must preserve simulated or proxy provenance and cannot be personal human judgment."); }
    if (demo.decision !== null) { object(demo.decision, "Demo decision"); for (const field of ["human", "perspectiveContext", "naturalLanguageIntent", "candidateId", "decision", "reason"]) text(demo.decision[field], `decision ${field}`); integer(demo.decision.demoRevision, "decision Demo revision"); if (demo.decision.personalJudgment !== true || demo.decision.candidateId !== demo.candidateId || !["accept", "request-correction", "defer"].includes(demo.decision.decision)) throw new ContractError("Demo decision requires exact personal human judgment."); texts(demo.decision.acceptedBoundary, "accepted boundary"); }
    if ((demo.phase === "accepted") !== (demo.decision?.decision === "accept") || (demo.phase === "correction-requested") !== (demo.decision?.decision === "request-correction") || (demo.phase === "deferred") !== (demo.decision?.decision === "defer")) throw new ContractError("Final Demo phase and human decision do not agree.");
    if (!Array.isArray(demo.history)) throw new ContractError("Demo history must be an array."); let previous: string | null = null;
    demo.history.forEach((entry: any, index: number) => { if (entry.version !== index + 1 || entry.previousHash !== previous || demoHistoryHash({ version: entry.version, operation: entry.operation, summary: entry.summary, beforeHash: entry.beforeHash, afterHash: entry.afterHash, previousHash: entry.previousHash }) !== entry.contentHash) throw new ContractError("Demo history integrity failed."); previous = entry.contentHash; });
    if (demo.historyHead !== previous || (demo.history.length && demo.history.at(-1).afterHash !== demoSnapshotHash(demo as MilestoneDemoState["demos"][number]))) throw new ContractError("Demo history anchor is invalid.");
  }
  if (!Array.isArray(value.nextActions) || value.nextActions.length !== 1) throw new ContractError("Demonstration state requires exactly one next action."); for (const field of ["participant", "action", "reason"]) text(value.nextActions[0][field], `next action ${field}`);
  object(value.session, "Demo session"); if (!["active", "interrupted"].includes(value.session.status)) throw new ContractError("Demo session status is invalid."); if (value.session.demoId !== null) text(value.session.demoId, "session demoId"); if (value.session.resumeAction !== null) text(value.session.resumeAction, "session resumeAction");
  object(value.generatedViews, "generated views");
}
