import type { NextAction } from "./types.js";
import type { FoundationAnchors, PlanEvaluationBoundary } from "./milestone-planning-types.js";

export const BUILD_PHASES = ["active", "blocked", "paused", "ready-for-demonstration"] as const;
export const BUILD_ROLES = ["orchestrator", "builder", "focused-evaluator", "final-evaluator"] as const;
export const EVALUATION_VERDICTS = ["pass", "fail", "blocked", "uncertain"] as const;
export const SOURCE_CONTROL_OPERATIONS = ["edit", "check", "branch", "worktree", "commit"] as const;
export type BuildPhase = (typeof BUILD_PHASES)[number];
export type BuildRole = (typeof BUILD_ROLES)[number];
export type EvaluationVerdict = (typeof EVALUATION_VERDICTS)[number];
export type SourceControlOperation = (typeof SOURCE_CONTROL_OPERATIONS)[number];

export interface ModelChoice { role: BuildRole; host: string; model: string; settingsProfile: string; available: true; recommended: boolean; qualification: "untested" | "tested" | "release-qualified"; unverifiedNotice: string | null }
export interface EvaluationWorkspace { location: string; fingerprint: string; clean: true; disposable: true }
export interface ExecutionGrant { participant: string; responsibilities: string[]; workUnits: string[]; workspace: { mode: "same-directory" | "separate-workspace"; location: string; fingerprint: string }; allowedTools: string[]; sourceControlOperations: SourceControlOperation[]; externalSystems: string[]; modelChoices: ModelChoice[]; costChoice: string; sourceFingerprint: string }
export interface ActivatedEvaluationBoundary extends PlanEvaluationBoundary { attempts: number; correctionCycles: number; status: "pending" | "passed" | "failed" | "blocked" | "uncertain" }
export interface BuildWorkUnit { key: string; title: string; order: number; status: "not-started" | "in-progress" | "completed" | "blocked"; owner: string | null; lastSummary: string; lastCandidateId: string | null }
export interface TaskAssignment extends ModelChoice { id: string; participant: string; responsibility: string; workUnits: string[]; checkpoint: string | null; sourceFingerprint: string; workspaceFingerprint: string; taskContextIdentity: string; evaluationWorkspace: EvaluationWorkspace | null; recommendationBasis: string }
export interface EvidenceRecord { id: string; candidateId: string | null; kind: "command" | "interaction" | "observation" | "artifact"; summary: string; reference: string; result: "passed" | "failed" | "skipped" | "unproven"; host: string; model: string; settingsProfile: string }
export interface BuildCandidate { id: string; kind: "focused" | "integrated"; checkpoint: string; sourceFingerprint: string; workspaceFingerprint: string; workUnits: string[]; builderParticipants: string[]; parentCandidateId: string | null; sequence: number }
export interface EvaluationCoverage { item: string; evidenceIds: string[]; status: "supported" | "failed" | "skipped" | "unproven" }
export interface EvaluationCharter { definitionRevision: number; planRevision: number; candidateId: string; candidateFingerprint: string; workUnits: string[]; acceptanceCriteria: string[]; plannedChecks: string[]; allowedTools: string[]; neutralPosture: "unproven" }
export interface EvaluationRecord { id: string; candidateId: string; checkpoint: string; evaluator: string; responsibility: string; assignmentId: string; charter: EvaluationCharter; verdict: EvaluationVerdict; acceptanceCoverage: EvaluationCoverage[]; checkCoverage: EvaluationCoverage[]; evidenceIds: string[]; findings: string[]; limitations: string[]; skips: string[]; unproven: string[]; sequence: number }
export interface BuildHistoryEntry { version: number; operation: "activate" | "assign" | "work" | "freeze" | "evaluate" | "adjust-budget" | "pause" | "resume" | "revalidate" | "render"; summary: string; beforeHash: string; afterHash: string; previousHash: string | null; contentHash: string }
export interface MilestoneBuild { id: string; planId: string; definitionId: string; title: string; artifactPath: string; order: number; definitionRevision: number; planRevision: number; phase: BuildPhase; revision: number; grant: ExecutionGrant; evaluationBudget: ActivatedEvaluationBoundary[]; workUnits: BuildWorkUnit[]; assignments: TaskAssignment[]; candidates: BuildCandidate[]; evaluations: EvaluationRecord[]; evidence: EvidenceRecord[]; failures: string[]; limitations: string[]; skips: string[]; unproven: string[]; history: BuildHistoryEntry[]; historyHead: string | null }
export interface MilestoneBuildState { schemaVersion: 1; stage: "milestone-build-and-prove"; workspaceClass: "human-project"; workspaceRoot: string; productRevision: number; engineeringRevision: number | null; roadmapRevision: number; definitionStateRevision: number; planningStateRevision: number; changeRevision: number | null; revision: number; builds: MilestoneBuild[]; nextActions: NextAction[]; session: { status: "active" | "interrupted"; buildId: string | null; resumeAction: string | null }; generatedViews: Record<string, { revision: number; sha256: string }> }
export interface BuildActivation { planId: string; participant: string; responsibilities: string[]; workUnits: string[]; workspace: ExecutionGrant["workspace"]; allowedTools: string[]; sourceControlOperations: SourceControlOperation[]; externalSystems: string[]; modelChoices: ModelChoice[]; costChoice: string; sourceFingerprint: string; evaluationBudget: PlanEvaluationBoundary[] }
export interface TaskAssignmentInput { buildId: string; role: BuildRole; participant: string; responsibility: string; workUnits: string[]; checkpoint: string | null; host: string; model: string; settingsProfile: string; sourceFingerprint: string; workspaceFingerprint: string; taskContextIdentity: string; evaluationWorkspace: EvaluationWorkspace | null; recommendationBasis: string }
export interface WorkEvidenceInput { key: string; kind: EvidenceRecord["kind"]; summary: string; reference: string; result: EvidenceRecord["result"] }
export interface BuildWorkUpdate { buildId: string; workUnitKey: string; participant: string; responsibility: string; status: "in-progress" | "completed" | "blocked"; tool: string; sourceControlOperation: SourceControlOperation; externalSystem: string | null; workspaceLocation: string; workspaceFingerprint: string; sourceFingerprintBefore: string; sourceFingerprintAfter: string; summary: string; evidence: WorkEvidenceInput[]; effect: { status: "none" | "completed" | "partial" | "uncertain"; detail: string }; boundaryDisposition: "within-plan" | "plan-adjustment-required" | "definition-change-required"; coordination: { checked: boolean; conflicts: string[] } }
export interface FreezeCandidateInput { buildId: string; kind: "focused" | "integrated"; checkpoint: string; workUnits: string[]; sourceFingerprint: string; workspaceFingerprint: string; parentCandidateId: string | null }
export interface EvaluationInput { buildId: string; candidateId: string; checkpoint: string; assignmentId: string; evaluator: string; responsibility: string; charter: EvaluationCharter; verdict: EvaluationVerdict; evidence: WorkEvidenceInput[]; acceptanceCoverage: EvaluationCoverage[]; checkCoverage: EvaluationCoverage[]; findings: string[]; limitations: string[]; skips: string[]; unproven: string[] }
export interface BudgetAdjustment { buildId: string; participant: string; boundaries: PlanEvaluationBoundary[]; explicitIncreaseJudgment: boolean; reason: string }
export interface BuildAnchors extends FoundationAnchors { planningStateRevision: number; changeRevision: number | null; definitionRevision: number; planRevision: number }
export interface BuildRevalidation { buildId: string; participant: string; responsibility: string; reviewedAnchors: BuildAnchors; sourceFingerprint: string; workspaceFingerprint: string; basis: string }
export interface MilestoneBuildContract { version: 1; id: "milestone-build-and-prove"; ready_plan_required: true; scoped_execution_grant_required: true; exact_anchor_reuse_only: true; active_session_assignment_only: true; no_redundant_active_assignment: true; explicit_authority_dimensions: true; sequential_default_explicit_safe_parallel_only: true; plan_evaluation_budget_activated_at_entry: true; independent_evaluator_required: true; exact_candidate_verdicts: true; correction_candidate_requires_changed_snapshot: true; fresh_evaluator_context_and_workspace: true; final_integrated_pass_required: true; evidence_is_not_proof: true; semantic_readiness_owned_by_host_ai: true; append_only_hash_linked_history: true; ordinary_updates_may_defer_publication: true; rejected_operations_do_not_mutate: true; exactly_one_next_action: true; later_stages_out_of_scope: true }
export type MilestoneBuildArtifacts = Record<string, string>;
